### ISSUE TITLE
Internal error on running queries (pg 9.6)

### ISSUE THREAD

**Issue by nnn-dev** [dalibo/temboard#1]
Hello

I use the master branch of temboard-agent

On dashboard on postgresql 9.6 instance,  the action Activity>Running queries doesn't work (internal error 500)

On the temboard-agent log, I see the postgresql error sql 42703 (undefined_column)

I suppose the problem is the "waiting" column of pg_stat_activity. This column doesn't exists on 9.6

PS: the action works on my 9.4 instance

Best regards

**Comment by julmon** [comment]
Hello,

The last commit (https://github.com/dalibo/temboard/commit/d62b7ad139843e1446f7b1fcd2c9bb73dc813e8b) should fix this.

Regards,

**Comment by nnn-dev** [comment]
It's works.
Thanks
