### ISSUE TITLE
Display application_name in activity table

### ISSUE THREAD

**Issue by lpofredc** [dalibo/temboard#1014]
It would be interesting to display `application_name` value, if available, in activity table.

![Screenshot 2022-03-24 at 09-50-05 SRV-GEONATUREBDD lpo local 5432 - Activity _ Running queries](https://user-images.githubusercontent.com/22891423/159878284-e4f48cdd-16b0-4ba6-b2d3-56f346a7dbe0.png)

**Comment by daamien** [comment]
good idea thanks !
