### ISSUE TITLE
use anosql or an adhoc sql file loader

### ISSUE THREAD

**Issue by dlax** [dalibo/temboard#1017]
There is a lot of SQL queries as python strings in the code base. [anosql](https://anosql.readthedocs.io/) is a nice tool to embed SQL in python code as queries can be written in plain `.sql` files with documentation and syntax highlighting. This would improves the readability and testeability.

**Comment by bersace** [comment]
Done. https://github.com/dalibo/temboard/blob/master/ui/temboardui/toolkit/queries.py
