### ISSUE TITLE
Hide header API

### ISSUE THREAD

**Issue by MakarovDmitri** [dalibo/temboard#1041]
Hello! Please help me with the following question. I need to hide the python version in the http header when calling an API. How can I do that.
![image](https://user-images.githubusercontent.com/90038400/169001095-d4a33da9-aa8d-4109-9383-28e5d2545fd7.jpg)

**Comment by bersace** [comment]
Hi @MakarovDmitri , it's not configurable for now. We'll take an eye on this feature request.

**Comment by bersace** [comment]
Reopening to consider the need.

**Comment by daamien** [comment]
Fixed by the Bottle MR https://github.com/dalibo/temboard/pull/1079
