### ISSUE TITLE
temboard agent replication query has syntax error

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#1042]
I've notices this in the PG logs on repmgr standby database:

2022-05-18 00:00:18 UTC [285150]: [1-1] user=temboard,db=postgres,app=temboard-agent,client=[local] ERROR:  syntax error at or near "CASE" at character 52
2022-05-18 00:00:18 UTC [285150]: [2-1] user=temboard,db=postgres,app=temboard-agent,client=[local] STATEMENT:  SELECT 'redacted-host-name' AS upstream
        CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END AS connected
        FROM pg_stat_wal_receiver
        WHERE status='streaming' AND
                conninfo LIKE '%host=redacted-host-name%'

I think your SQL query is missing a comma, shouldn't it be:

SELECT 'redacted-host-name' AS upstream, <--- comma here
CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END AS connected
FROM pg_stat_wal_receiver
WHERE status='streaming' AND
conninfo LIKE '%host=redacted-host-name%'

$ temboard-agent --version
 INFO: Starting temboard-agent 7.10.
temBoard agent 7.10
System CentOS Linux 7 (Core)
Python 3.6.6 (/usr/bin/python3)
psycopg2 2.8.5 (dt dec pq3 ext lo64) libpq 13.2

**Comment by bersace** [comment]
Yes, it's fixed in 7.11 we're about to release

**Comment by daamien** [comment]
https://github.com/dalibo/temboard/releases/tag/7.11
