### ISSUE TITLE
 Temboard service Permission denied

### ISSUE THREAD

**Issue by decadenet** [dalibo/temboard#1065]
Hi,

After installing temboard on Debian and starting the service, and going to temboard web UI (port 8888)  I receive an ERR_TIMED_OUT.
the command "systemctl status temboard" command showed this error :

temboard.service - temBoard Web UI
     Loaded: loaded (/lib/systemd/system/temboard.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2022-06-11 14:36:00 CEST; 16s ago
   Main PID: 15245 (python3.9)
      Tasks: 5 (limit: 154559)
     Memory: 55.9M
        CPU: 630ms
     CGroup: /system.slice/temboard.service
             ├─15245 temboard: web
             ├─15247 temboard: worker pool
             └─15248 temboard: scheduler

juin 11 14:36:11 OSBI env[15245]:     handler_func(fileobj, events)
juin 11 14:36:11 OSBI env[15245]:   File "/usr/lib/temboard/lib/python3.9/site-packages/tornado/netutil.py", line 276, in accept_handler
juin 11 14:36:11 OSBI env[15245]:     callback(connection, address)
juin 11 14:36:11 OSBI env[15245]:   File "/usr/lib/temboard/lib/python3.9/site-packages/temboardui/autossl.py", line 177, in _handle_connection
juin 11 14:36:11 OSBI env[15245]:     connection = ssl_wrap_socket(connection,
juin 11 14:36:11 OSBI env[15245]:   File "/usr/lib/temboard/lib/python3.9/site-packages/tornado/netutil.py", line 608, in ssl_wrap_socket
juin 11 14:36:11 OSBI env[15245]:     context = ssl_options_to_context(ssl_options)
juin 11 14:36:11 OSBI env[15245]:   File "/usr/lib/temboard/lib/python3.9/site-packages/tornado/netutil.py", line 576, in ssl_options_to_context
juin 11 14:36:11 OSBI env[15245]:     context.load_cert_chain(
juin 11 14:36:11 OSBI env[15245]: PermissionError: [Errno 13] Permission denied

The Server and the agent are on the same server.

Thanks a lot

**Comment by bersace** [comment]
Hi @decadenet , thanks for reaching.

It looks like your SSL files are not accessible from `temboard` unix user. What's the output of : `sudo -u temboard namei -om *PATH-TO-SSL-FILES*` ?

temBoard should show a clean error instead of a traceback.

**Comment by daamien** [comment]
Hi @decadenet 

Any news on this ?
