### ISSUE TITLE
Deleted database nor in the UI but data exists in the repository

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#1074]
We seem to have a database that was been "deleted" - it doesn't appear in the UI **but** there does appear to be data in the repository database for it - is there a way to remove all data for a host & instance from the repository database via plsql to tidy this up?

**Comment by bersace** [comment]
Hi @dgiffin . temBoard can purge data if you set `[monitoring] purge_after` setting in temBoard configuration.

Do you have *No purge policy, end.* message in your logs ?

**Comment by dgiffin** [comment]
You mean in the temboard.conf file? I don't have a [monitoring] section.

In the temboard logs all I can find are entries like this:

2022-06-22 13:49:04,684 temboardui[5132]: [statements] INFO: Old statements purged successfully.

**Comment by bersace** [comment]
> You mean in the temboard.conf file? I don't have a [monitoring] section.

Yes, I mean in temboard.conf or temboard.conf.d/

**Comment by dgiffin** [comment]
Yup - no [monitoring] section in /etc/temboard/temboard.conf

**Comment by bersace** [comment]
> Yup - no [monitoring] section in /etc/temboard/temboard.conf

Ok, set this in temboard configuration:

``` ini
[monitoring]
purge_after = 180  # days
```

Put it in /etc/temboard/temboard.conf.d/monitoring.conf and restart temBoard.

**Comment by dgiffin** [comment]
Ok, done - and this should eventually remove the entries from (say) monitoring.metric_db_size_history etc?

**Comment by bersace** [comment]
> Ok, done - and this should eventually remove the entries from (say) monitoring.metric_db_size_history etc?

Yes, for all instances, all data older than 180 days will be removed.

**Comment by dgiffin** [comment]
Ok, I set this yesterday:

cat /etc/temboard/temboard.conf
<CUT>
[monitoring]
purge_after = 30

But if I check the repository I am seeing much older data than 30 days:

temboard=# select history_range from monitoring.metric_db_size_history where instance_id=16 order by 1 asc limit 10;
                           history_range
-------------------------------------------------------------------
 ["2019-01-09 09:00:03.755605+00","2019-01-09 10:39:41.396393+00")
 ["2019-01-09 09:00:03.755605+00","2019-01-09 10:39:41.396393+00")
 ["2019-01-09 09:00:03.755605+00","2019-01-09 10:39:41.396393+00")
 ["2019-01-09 10:40:41.804431+00","2019-01-09 13:39:49.562807+00")
 ["2019-01-09 10:40:41.804431+00","2019-01-09 13:39:49.562807+00")
 ["2019-01-09 10:40:41.804431+00","2019-01-09 13:39:49.562807+00")
 ["2019-01-09 13:40:49.967813+00","2019-01-09 16:39:58.516393+00")
 ["2019-01-09 13:40:49.967813+00","2019-01-09 16:39:58.516393+00")
 ["2019-01-09 13:40:49.967813+00","2019-01-09 16:39:58.516393+00")
 ["2019-01-09 16:40:58.914219+00","2019-01-09 19:40:07.372305+00")
(10 rows)

**Comment by bersace** [comment]
Can you share debug log output ?

**Comment by dgiffin** [comment]
I've just set the log level to DEBUG - how long do you want me to leave that running before I send you the log? overnight?

**Comment by bersace** [comment]
Hi @dgiffin , the purge task is scheduled every 24h.

**Comment by dgiffin** [comment]
Log files for the last day attached. 
[temboard.log-20220701.gz](https://github.com/dalibo/temboard/files/9025649/temboard.log-20220701.gz)
[temboard.log-20220630.gz](https://github.com/dalibo/temboard/files/9025650/temboard.log-20220630.gz)

**Comment by dgiffin** [comment]
Any thoughts?

**Comment by bersace** [comment]
Hi @dgiffin, sorry for the delay.

```
2022-06-30 08:07:45,476 temboardui[30107]: [taskmanager] DEBUG: Activate worker purge_data_worker
2022-06-30 08:07:45,476 temboardui[30107]: [taskmanager] DEBUG: Activate worker notify_state_change
2022-06-30 08:07:45,476 temboardui[30107]: [taskmanager] DEBUG: Activate worker schedule_collector
2022-06-30 08:07:45,476 temboardui[30107]: [taskmanager] DEBUG: Activate worker collector
2022-06-30 08:07:45,476 temboardui[30107]: [taskmanager] DEBUG: Activate worker pull_data_worker
2022-06-30 08:07:45,476 temboardui[30107]: [taskmanager] DEBUG: Activate worker purge_data_worker
```

It looks like you're not running 7.11. 

Can you share `temboard --version` output ?

**Comment by bersace** [comment]
Please upgrade to 7.11, it has a fix regarding purge.
