### ISSUE TITLE
Upgrade steps 7.10 to 7.11?

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#1075]
I can't see the upgrade steps on readthedocs for 7.10 to 7.11 for the temboard UI and the temboard-agent - what do I need to know?

**Comment by wsescu** [comment]
Dear @dgiffin 

in the following blog I have documented the way I used to upgrade to 7.11.

https://ptdb.ch/2022/05/21/postgresql-temboard-version-7-11-released-with-huge-performance-boost/

Cheers
William

**Comment by dgiffin** [comment]
Thanks William, just what I was looking for.

**Comment by bersace** [comment]
Hi,

@dgiffin thanks for the report. I'll update the upgrade documentation to fix the miss.

@wsescu your article is awesome, thanks !

The upgrade from 7.9 to 7.10 and 7.11 is pretty straightforward : stop, update, restart. PR comming soon.

Regards,
Étienne

**Comment by dgiffin** [comment]
Thanks! We want to go to 8 when it's GA but 7.11 gives us good improvements now ;-)

**Comment by bersace** [comment]
Done. https://temboard.readthedocs.io/en/v7/server_upgrade/#upgrade-79-or-710-to-711

**Comment by dgiffin** [comment]
No repository upgrade? awesome, thank you!

**Comment by bersace** [comment]
the commit is here : https://github.com/dalibo/temboard/commit/30ca1fa6cc96c65af7ee2ec5b59fd908c5b42320
