### ISSUE TITLE
FATAL: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"

### ISSUE THREAD

**Issue by HapipHaekal** [dalibo/temboard#1181]
Hello

I am using postgresql 15 as a repository and after installing temboard 8 there is a problem that is it fails to connect to the database.

I tried to call the script _auto_configure.sh_ there is an error :

> WARNING:  model: Connection to the database failed: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"
> 
> WARNING:  model: Please check your configuration.
> FATAL: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"
> 
> + catchall
> + local rc=10
> + trap - INT EXIT TERM
> + set +x

I checked my postgresql is still running with no problem.

Thanks

**Comment by bersace** [comment]
Closing in favor of #1185
