### ISSUE TITLE
Download inventory as CSV - not working as expected

### ISSUE THREAD

**Issue by wsescu** [dalibo/temboard#1182]
Dear Dalibo Support

the Download inventory as CSV is not working as expected (temBoard version 8.0).

I found 3 issues. The first one is, that the PGDATA field in the csv file is always empty.

Hostname;Port;PGDATA;Version;Groups;Agent Address;Agent Port;Plugins
"host01";"56001";;"""PostgreSQL 14.4""";"entw";"host01";"44001";"activity,dashboard,maintenance,monitoring,pgconf,statements"

The second one is, that the comment field is not exported at all.

And the third issue is, that if I limit in the search field the number of instances, e.g.
only instances starting with the letter T*, I would expect that the exported csv shows only the
instances I have searched for. However, it does not export any instance at all.

Cheers
William

**Comment by vidierr** [comment]
Hello Wsescu,
I don't have the third issue. I limit whith the search field and export only theses instances, not all.
I make a pull request for correct the two others issues.

Have a good day,

**Comment by bersace** [comment]
Thanks @vidierr for the fix. I'll check the search bug. A guick look at the code didn't raised a particular bug. I'll need more investigation. Thanks @wsescu for the report !

**Comment by bersace** [comment]
@wsescu I cant' reproduce the search bug. I tested various pattern andCan you describe me precisely how you endup with a bad CSV ?

**Comment by wsescu** [comment]
Dear @bersace 

I can reproduce that issue anytime I want. I simply click on instances, than I type e.g. MTX in the search field to get all MTX instances. Than I click on the download inventory button, however the csv file is empty.

Cheers
William

**Comment by bersace** [comment]
@wsescu , thanks for the confirmation. Can you share me the browser you are using ? Do you have messages in Browser javascript console ?

**Comment by wsescu** [comment]
Dear @bersace 

I am using Chrome Version 107.x.x.x.x

No, I don't see any errors in the Javascript Console.

Cheers
William

**Comment by wsescu** [comment]
Dear @bersace 

starting with temBoard version 8.1, the download of the inventory works perfectly.
Thanks for fixing that issue.

Cheers
William

**Comment by bersace** [comment]
@wsescu thanks for the feedback !
