### ISSUE TITLE
Fetch UI signing key

### ISSUE THREAD

**Issue by HapipHaekal** [dalibo/temboard#1185]
Dear Dalibo

I got a problem when I sudo -u postgres temboard-agent -c /etc/temboard-agent/13/main/temboard-agent.conf fetch-key

The problem is like this:
```
INFO:  fetch_key: Requesting public key from https://10.10.10.10:8888.
ERROR:  app: Unhandled error:
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/temboardagent/toolkit/app.py", line 351, in entrypoint
            retcode = self.main(argv, environ)
          File "/usr/lib/python3/dist-packages/temboardagent/cli/app.py", line 135, in main
            return command.main(args)
          File "/usr/lib/python3/dist-packages/temboardagent/cli/fetch_key.py", line 41, in main
            response = ui_client.get('/signing.key')
          File "/usr/lib/python3/dist-packages/temboardagent/toolkit/http.py", line 148, in get
            return self.request('GET', path, headers)
          File "/usr/lib/python3/dist-packages/temboardagent/toolkit/http.py", line 128, in request
            conn.request(method, path, body, headers)
          File "/usr/lib/python3.9/http/client.py", line 1255, in request
            self._send_request(method, url, body, headers, encode_chunked)
          File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
            self.endheaders(body, encode_chunked=encode_chunked
          File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
            self._send_output(message_body, encode_chunked=encode_chunked)
          File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
            self.send(msg)
          File "/usr/lib/python3.9/http/client.py", line 950, in send
            self.connect()
          File "/usr/lib/python3.9/http/client.py", line 1417, in connect
            super().connect()
          File "/usr/lib/python3.9/http/client.py", line 921, in connect
            self.sock = self._create_connection(
          File "/usr/lib/python3.9/socket.py", line 843, in create_connection
            raise err
          File "/usr/lib/python3.9/socket.py", line 831, in create_connection
            sock.connect(sa)
        ConnectionRefusedError: [Errno 111] Connection refused
ERROR:  app: temboardagent version is 8.0.
ERROR:  app: This is a bug!
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!
```

**Comment by pirlgon** [comment]
It looks like the agent server is not allowed to access the UI server. Did you allow it in the firewall? Is there a running UI at https://10.10.10.10:8888 ?

**Comment by HapipHaekal** [comment]
There is no firewall running

**Comment by vidierr** [comment]
Does the temboard server is running ?
I had the same error but it was the temboard server was'nt running.

**Comment by HapipHaekal** [comment]
Yes, the temboard server is running

I already checked _systemctl status temboard_ :
```
● temboard.service - temBoard Server
     Loaded: loaded (/lib/systemd/system/temboard.service; disabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-11-18 14:40:02 WIB; 1 weeks 3 days ago
   Main PID: 269614 (python3.9)
      Tasks: 6 (limit: 4650)
     Memory: 92.8M
        CPU: 1h 18min 43.656s
     CGroup: /system.slice/temboard.service
             ├─269614 temboard: web
             ├─269618 temboard: worker pool
             └─269619 temboard: scheduler

Nov 28 23:10:56 TestingLinux temboard[618919]: statements: No instances to pull data from.
Nov 28 23:11:57 TestingLinux temboard[618943]: monitoring: Starting collector scheduler.
Nov 28 23:11:57 TestingLinux temboard[618943]: monitoring: End of collector scheduler.
Nov 28 23:11:58 TestingLinux temboard[618942]: statements: No instances to pull data from.
Nov 28 23:12:58 TestingLinux temboard[618965]: monitoring: Starting collector scheduler.
Nov 28 23:12:58 TestingLinux temboard[618965]: monitoring: End of collector scheduler.
Nov 28 23:12:58 TestingLinux temboard[618964]: statements: No instances to pull data from.
Nov 28 23:13:59 TestingLinux temboard[618999]: monitoring: Starting collector scheduler.
Nov 28 23:13:59 TestingLinux temboard[618999]: monitoring: End of collector scheduler.
Nov 28 23:13:59 TestingLinux temboard[618998]: statements: No instances to pull data from.
```

**Comment by daamien** [comment]
@HapipHaekal: Thanks for the info

Can you try to contact the server from the PostgreSQL VM with something like:

```
curl -k https://10.10.10.10:8888/
```

And give the output

**Comment by HapipHaekal** [comment]
Here the output : 
```
<!doctype html>
<html lang=en>
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to the target URL: <a href="/home">/home</a>. If not, click the link.
```

**Comment by bersace** [comment]
@HapipHaekal you have a network issue, please contact your network or system administrator. Please keep this issue opened as temBoard must at least better handle such error.

Can you enable DEBUG level in temBoard server and share logs ?

**Comment by HapipHaekal** [comment]
Here _temboard-auto-configure.log_ :
```
+ setup_pq
+ local psql
+ export PGHOST=repository
+ PGHOST=repository
+ export PGPORT=5435
+ PGPORT=5435
+ export PGUSER=postgres
+ PGUSER=postgres
+ '[' -d repository ']'
+ psql=(psql)
+ psql -tc 'SELECT '\''Postgres connection working.'\'';'
psql: error: could not translate host name "repository" to address: Name or service not known
+ fatal 'Can'\''t connect to Postgres cluster.'
+ echo -e '\e[1;31mCan'\''t connect to Postgres cluster.\e[0m'
+ tee -a /dev/fd/3
tee: /dev/fd/3: Permission denied
Can't connect to Postgres cluster.
+ catchall
+ local rc=1
+ trap - INT EXIT TERM
+ set +x
tee: /dev/fd/3: Permission denied
Failure. See /var/log/temboard-auto-configure.log for details.
```

**Comment by bersace** [comment]
PGHOST seems wrong. Can you confirm this ?

**Comment by HapipHaekal** [comment]
Well
Actually, I did something like this 
```
export PGHOST=repository
export PGUSER=postgres
export PGPASSWORD=postgres,
export TEMBOARD_LOGGING_LEVEL=DEBUG 
```
Before doing the Post installation stage and I saw it from docker-compose temboard. Then I did Post Installation like this `PGPORT=5433 /usr/share/temboard/auto_configure.sh`

Previously, I went straight to the Post Installation stage after installing the temboard but it failed and I forgot what the error was like.

**Comment by bersace** [comment]
If you can run psql, you can run auto_configure.sh. With the special case that if PGUSER exists as a UNIX user, auto_configure.sh does `sudo` automatically to use peer auth.

**Comment by HapipHaekal** [comment]
Okay, thanks for the response.
Now I'm trying to start over from the beginning without using the configuration from docker-compose.

I have installed Postgresql 15 and checked `sudo -u postgres psql` is running, then install temboard and run `sudo /usr/share/temboard/auto_configure.sh` there is a failure:

```
INFO:  app: Using config file /etc/temboard/temboard.conf.
INFO:  migrator: temBoard database is up-to-date.
++ whoami
+ '[' root '!=' temboard ']'
+ run_as_temboard=(sudo -Enu "$SYSUSER")
+ dsn=postgres://temboard:2bda41f3feb1b012b2d04e0471846d44@/temboard
+ sudo -Enu temboard psql -Atc 'SELECT '\''CONNECTED'\'';' postgres://temboard:2bda41f3feb1b012b2d04e0471846d44@/temboard
+ grep -q CONNECTED
+ TEMBOARD_CONFIGFILE=/etc/temboard/temboard.conf
+ sudo -Enu temboard temboard generate-key
INFO:  app: Using config file /etc/temboard/temboard.conf.
WARNING:  model: Failed to connect to database: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"

INFO:  model: Retrying in 1s.
WARNING:  model: Failed to connect to database: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"

INFO:  model: Retrying in 2s.
WARNING:  model: Failed to connect to database: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"

INFO:  model: Retrying in 3s.
WARNING:  model: Failed to connect to database: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"

INFO:  model: Retrying in 4s.
WARNING:  model: Failed to connect to database: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"

INFO:  model: Retrying in 5s.
WARNING:  model: Failed to connect to database: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"

INFO:  model: Retrying in 6s.
WARNING:  model: Failed to connect to database: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"

INFO:  model: Retrying in 7s.
WARNING:  model: Failed to connect to database: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"

INFO:  model: Retrying in 8s.
WARNING:  model: Connection to the database failed: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"

WARNING:  model: Please check your configuration.
FATAL: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"

+ catchall
+ local rc=10
+ trap - INT EXIT TERM
+ set +x
Failure. See /var/log/temboard-auto-configure.log for details.
```

When I check the temboard:
`app: Failed to load signing key: [Errno 2] No such file or directory: '/etc/temboard/signing-private.pem'`

**Comment by bersace** [comment]
That's odd, it seems that temboard.conf is configured to connect with `postgres` role instead of `temboard` ? Can you confirm this ?

**Comment by azsan01** [comment]
is it noraml that i can access this page while my temboard status is not active ?
![admin](https://user-images.githubusercontent.com/79525639/227917851-d8957bab-e6ef-46b8-9e82-5839cdbb94a7.PNG)
(url)

**Comment by azsan01** [comment]
![stat](https://user-images.githubusercontent.com/79525639/227917918-fbfc2a90-d10e-496c-af77-d992457c704b.png)

**Comment by azsan01** [comment]
`root@vmi934386:~# systemctl status temboard
● temboard.service - temBoard Server
     Loaded: loaded (/usr/local/lib/systemd/system/temboard.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-03-27 17:05:12 CEST; 4s ago
   Main PID: 3948727 (temboard)
      Tasks: 1 (limit: 9479)
     Memory: 51.9M
     CGroup: /system.slice/temboard.service
             └─3948727 /usr/bin/python3 /usr/local/bin/temboard -c /etc/temboard/temboard.conf serve

Mar 27 17:05:12 vmi934386.contaboserver.net systemd[1]: Started temBoard Server.
Mar 27 17:05:13 vmi934386.contaboserver.net temboard[3948727]: INFO:  app: Using config file /etc/temboard/temboard.conf.
Mar 27 17:05:13 vmi934386.contaboserver.net temboard[3948727]: model: Failed to connect to database: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  the database system is shutting down
Mar 27 17:05:13 vmi934386.contaboserver.net temboard[3948727]: model: Retrying in 1s.
Mar 27 17:05:14 vmi934386.contaboserver.net temboard[3948727]: model: Failed to connect to database: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  the database system is shutting down
Mar 27 17:05:14 vmi934386.contaboserver.net temboard[3948727]: model: Retrying in 2s.
Mar 27 17:05:16 vmi934386.contaboserver.net temboard[3948727]: model: Failed to connect to database: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  the database system is shutting down
Mar 27 17:05:16 vmi934386.contaboserver.net temboard[3948727]: model: Retrying in 3s.
root@vmi934386:~#
`

I can't connect to postgres

**Comment by bersace** [comment]
@azsan01 what's on your postgresql logs ? Why is it shutting down ?

**Comment by azsan01** [comment]
![tem](https://user-images.githubusercontent.com/79525639/232002496-f638e7c0-68b1-4099-8506-eea6968f14bf.PNG)
temboard is active but i have this warning about postgres

**Comment by azsan01** [comment]
![post](https://user-images.githubusercontent.com/79525639/232002984-35cfbb86-d3b7-44fd-b916-7d6f4c429430.PNG)
I don't have error in postgres logs, or it is not what you want to see ?

**Comment by bersace** [comment]
What is returned by `namei -om /var/run/postgresql/.s.PGSQL.5433` ?

**Comment by bersace** [comment]
Closing stale issue.
