### ISSUE TITLE
unable to give login/password parameter in command line of register

### ISSUE THREAD

**Issue by vidierr** [dalibo/temboard#1191]
Hello,
i would like to automate the installation and configuration of temboard agent.
When i need to register the agent, i can't give login/password as parameters in command line.

Is there any solution ?

**Comment by bersace** [comment]
Hi @vidierr I suggest you to call `temboard register-instance` on temBoard UI host.

Otherwise, you can set login and password using environment variables `TEMBOARD_UI_USER` and `TEMBOARD_UI_PASSWORD` as used in agent Docker entrypoint.

**Comment by vidierr** [comment]
it work fine, thank you.
