### ISSUE TITLE
Error when fetch-key: Validating PEM data

### ISSUE THREAD

**Issue by fathoniinsansilmi** [dalibo/temboard#1194]
hi, this error appears when i execute config fetch-key, deatails below:
```
[postgres@ipa ~]$ temboard-agent --config=/etc/temboard-agent/11/data/temboard-agent.conf fetch-key
INFO:  app: Using config file /etc/temboard-agent/11/data/temboard-agent.conf.
INFO:  fetch_key: Requesting public key from https://10.10.2.41:8888.
INFO:  fetch_key: Validating PEM data.
ERROR:  app: Unhandled error:
        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/app.py", line 351, in entrypoint
            retcode = self.main(argv, environ)
          File "/usr/lib/python3.6/site-packages/temboardagent/cli/app.py", line 135, in main
            return command.main(args)
          File "/usr/lib/python3.6/site-packages/temboardagent/cli/fetch_key.py", line 48, in main
            with open(pub, 'wb') as fo:
        PermissionError: [Errno 13] Permission denied: '/etc/temboard-agent/11/data/signing-public.pem'
ERROR:  app: temboardagent version is 8.0.
ERROR:  app: This is a bug!
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!
```

any suggestion for this bug?

**Comment by bersace** [comment]
Can you share the output of `namei -om /etc/temboard-agent/11/data/signing-public.pem` ?

**Comment by fathoniinsansilmi** [comment]
hi @bersace this the output
[root@ipa ~]# namei -om /etc/temboard-agent/11/data/signing-public.pem
f: /etc/temboard-agent/11/data/signing-public.pem
 dr-xr-xr-x root     root     /
 drwxr-xr-x root     root     etc
 drwxr-xr-x postgres postgres temboard-agent
 drwxr-xr-x postgres postgres 11
 drwxr-xr-x root     root     data
                              signing-public.pem - No such file or directory

**Comment by bersace** [comment]
Run `chown postgres: /etc/temboard-agent/11/data` and rereun fetch-key. I'll check if this is a bug in auto_configure.sh

**Comment by fathoniinsansilmi** [comment]
hi @bersace 

[root@ipa ~]# chown postgres: /etc/temboard-agent/11/data
[root@ipa ~]# su - postgres
Last login: Tue Dec 13 17:49:26 WIB 2022 on pts/0
[postgres@ipa ~]$ temboard-agent --config=/etc/temboard-agent/11/data/temboard-agent.conf fetch-key
INFO:  app: Using config file /etc/temboard-agent/11/data/temboard-agent.conf.
INFO:  fetch_key: Requesting public key from https://10.10.2.41:8888.
INFO:  fetch_key: Validating PEM data.
INFO:  fetch_key: /etc/temboard-agent/11/data/signing-public.pem updated from https://10.10.2.41:8888.
INFO:  fetch_key: Please reload agent service if running.
[postgres@ipa ~]$ temboard-agent --config=/etc/temboard-agent/11/data/temboard-agent.conf tasks flush
INFO:  app: Using config file /etc/temboard-agent/11/data/temboard-agent.conf.
INFO:  taskmanager: Flushed 2 tasks.

[root@ipa ~]# systemctl restart temboard-agent@11-data.service
[root@ipa ~]# systemctl status temboard-agent@11-data.service
● temboard-agent@11-data.service - PostgreSQL Remote Control Agent 11/data
   Loaded: loaded (/usr/lib/systemd/system/temboard-agent@.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2022-12-21 10:20:56 WIB; 1s ago
  Process: 89514 ExecStart=/usr/bin/temboard-agent -c /etc/temboard-agent/11/data/temboard-agent.conf (code=exited, status=1/FAILURE)
 Main PID: 89514 (code=exited, status=1/FAILURE)

Dec 21 10:20:56 ipa.postgre02.lab temboard-agent[89514]: serve: Starting main process.
Dec 21 10:20:56 ipa.postgre02.lab temboard-agent[89514]: services: Starting worker pool.
Dec 21 10:20:56 ipa.postgre02.lab temboard-agent[89514]: services: Starting web.
Dec 21 10:20:56 ipa.postgre02.lab temboard-agent[89514]: services: Starting scheduler.
Dec 21 10:20:56 ipa.postgre02.lab temboard-agent[89514]: taskmanager: Aborting jobs on SIGTERM.
Dec 21 10:20:56 ipa.postgre02.lab temboard-agent[89514]: services: worker pool terminated.
Dec 21 10:20:56 ipa.postgre02.lab temboard-agent[89514]: services: scheduler terminated.
Dec 21 10:20:56 ipa.postgre02.lab temboard-agent[89514]: app: Failed to setup SSL: [Errno 13] Permission denied.
Dec 21 10:20:56 ipa.postgre02.lab systemd[1]: temboard-agent@11-data.service: Main process exited, code=exited, status=1/FAILURE
Dec 21 10:20:56 ipa.postgre02.lab systemd[1]: temboard-agent@11-data.service: Failed with result 'exit-code'.
[root@ipa ~]#

**Comment by bersace** [comment]
Hi @fathoniinsansilmi you need to check whether postgres user has access to SSL certificates. Get pem and key files from temboard-agent.conf file. Then, diagnostic access using namei -om. Then fix access on files or privileges on postgres user.

**Comment by fathoniinsansilmi** [comment]
hi @bersace i've change the ownership oh those files to postgres, and the service started, but i've found another error on log, and when i checking temboard dashboard, it showing me wrong postgres port, and cannot access all monitoring plugins, although  it showing me uptime of postgres database



2022-12-22 14:19:58 WIB temboardagent[867586] ERROR:  monitoring: Probe failure: FATAL:  relation mapping file "base/16384/pg_filenode.map" contains invalid data

2022-12-22 14:19:58 WIB temboardagent[867586] ERROR:  taskmanager: <class 'psycopg2.OperationalError'>: FATAL:  relation mapping file "base/16384/pg_filenode.map" contains invalid data
        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/taskmanager.py", line 627, in exec_worker
            res = fun(*args, **kws)
          File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/taskmanager.py", line 802, in wrapper
            return function(self.app, *a, **kw)
          File "/usr/lib/python3.6/site-packages/temboardagent/plugins/monitoring/__init__.py", line 129, in monitoring_collector_worker
            data = run_probes(probes, pool, [instance])
          File "/usr/lib/python3.6/site-packages/temboardagent/plugins/monitoring/probes.py", line 90, in run_probes
            out += p.run(pool.getconn(dbname=dbname), conninfo)
          File "/usr/lib/python3.6/site-packages/temboardagent/postgres.py", line 123, in getconn
            conn = retry_connect(connect, self.postgres.app, **pqvars)
          File "/usr/lib/python3.6/site-packages/temboardagent/postgres.py", line 276, in retry_connect
            conn = connect(*a, **kw)
          File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
            conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
        psycopg2.OperationalError: FATAL:  relation mapping file "base/16384/pg_filenode.map" contains invalid data

![image](https://user-images.githubusercontent.com/89531166/209080391-504cee3b-1e5a-4091-b87e-a52218b21656.png)

**Comment by bersace** [comment]
You have a corruption in your database.

**Comment by fathoniinsansilmi** [comment]
> You have a corruption in your database.

on database agent?

**Comment by bersace** [comment]
It seems that monitored instance has corrupted data.

**Comment by fathoniinsansilmi** [comment]
> It seems that monitored instance has corrupted data.

ok so the issue is on temboard ui side, not the agent am i right?

**Comment by bersace** [comment]
No, the issue seems on monitored PostgreSQL side.

**Comment by fathoniinsansilmi** [comment]
hi @bersace i've been trying to delete and re-init postgresql database with the same port and the problem still the same, what should i do?

**Comment by bersace** [comment]
Do you still have `invalid data` error from PostgreSQL ?

**Comment by bersace** [comment]
Closing. Please reopen if needed.
