### ISSUE TITLE
Temboard agent fail to start after an update

### ISSUE THREAD

**Issue by wolverin26** [dalibo/temboard#1197]
Hello,

Due to new update of temboard agent from 7.8 version to 7.11, agent can't be started and shows these errors below : 

[root@u3antu131 temboard-agent]# systemctl status -l temboard-agent
● temboard-agent.service - temBoard agent for PostgreSQL
   Loaded: loaded (/usr/lib/systemd/system/temboard-agent.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2023-02-01 10:30:26 CET; 3s ago
  Process: 11028 ExecStart=/usr/bin/temboard-agent -c /etc/temboard-agent/temboard-agent.conf (code=exited, status=1/FAILURE)
 Main PID: 11028 (code=exited, status=1/FAILURE)

Feb 01 10:30:26 u3antu131 temboard-agent[11028]: ERROR:     now=datetime.utcnow()
Feb 01 10:30:26 u3antu131 temboard-agent[11028]: ERROR:   File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/tasklist/sqlite3_engine.py", line 253, in recover
Feb 01 10:30:26 u3antu131 temboard-agent[11028]: ERROR:     raise StorageEngineError("Could not recover tasks.")
Feb 01 10:30:26 u3antu131 temboard-agent[11028]: ERROR: temboardagent.toolkit.errors.StorageEngineError: Could not recover tasks.
Feb 01 10:30:26 u3antu131 temboard-agent[11028]: ERROR: temboardagent version is 7.11.
Feb 01 10:30:26 u3antu131 temboard-agent[11028]: ERROR: This is a bug!
Feb 01 10:30:26 u3antu131 temboard-agent[11028]: ERROR: Please report traceback to https://github.com/dalibo/temboard-agent! Thanks!
Feb 01 10:30:26 u3antu131 systemd[1]: temboard-agent.service: main process exited, code=exited, status=1/FAILURE
Feb 01 10:30:26 u3antu131 systemd[1]: Unit temboard-agent.service entered failed state.
Feb 01 10:30:26 u3antu131 systemd[1]: temboard-agent.service failed.

Please, do you have an idea to how to resolve this issue ?

Sincerely,

**Comment by bersace** [comment]
Hi,

You are using the old single installation `temboard-agent.service` file. You should use `temboard-agent@.service` template unit. 

You may want to reconfigure agent using `auto_configure.sh`. Follow agent installation instruction. 
https://temboard.readthedocs.io/en/latest/agent_install/#setup-one-instance

**Comment by wolverin26** [comment]
Hi,

Thank you for your response ! Yes right, after using the new template unit the agent service is up now. Except that, i had a new error which is : 
[root@u3antu131 temboard-agent]# systemctl status -l temboard-agent@main.service
● temboard-agent@main.service - PostgreSQL Remote Control Agent main
   Loaded: loaded (/usr/lib/systemd/system/temboard-agent@.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2023-02-01 11:59:34 CET; 1min 19s ago
 Main PID: 15627 (temboard-agent)
   CGroup: /system.slice/system-temboard\x2dagent.slice/temboard-agent@main.service
           ├─15627 temboard-agent: main: main process
           ├─15629 temboard-agent: main: worker pool
           └─15630 temboard-agent: main: scheduler

Feb 01 12:00:41 u3antu131 env[15627]: client: 10.178.195.2 request: "GET /dashboard/config?key=0258776638911985230384799874617 HTTP/1.1" 401 - 4.34ms
Feb 01 12:00:46 u3antu131 env[15627]: {'error': 'Invalid key'}
Feb 01 12:00:46 u3antu131 env[15627]: Traceback (most recent call last):
Feb 01 12:00:46 u3antu131 env[15627]:   File "/usr/lib/python3.6/site-packages/temboardagent/httpd.py", line 136, in response
Feb 01 12:00:46 u3antu131 env[15627]:     (code, message) = self.route_request()
Feb 01 12:00:46 u3antu131 env[15627]:   File "/usr/lib/python3.6/site-packages/temboardagent/httpd.py", line 260, in route_request
Feb 01 12:00:46 u3antu131 env[15627]:     raise HTTPError(401, "Invalid key")
Feb 01 12:00:46 u3antu131 env[15627]: temboardagent.errors.HTTPError: Invalid key
Feb 01 12:00:46 u3antu131 env[15627]: {'error': 'Invalid key'}
Feb 01 12:00:46 u3antu131 env[15627]: client: 10.178.195.2 request: "GET /dashboard/config?key=0258776638911985230384799874617 HTTP/1.1" 401 - 0.86ms

And beside this, i couldn't run this command : 
sudo -u postgres temboard-agent -c /etc/temboard-agent/14/main/temboard-agent.conf register --groups default

because there is no register option in the temboard-agent command. See below : 

[root@u3antu131 temboard-agent]# sudo -u postgres temboard-agent -c /etc/temboard-agent/main/temboard-agent.conf register --groups default
 INFO: Starting temboard-agent 7.11.
usage: temboard-agent [-h] [-c CONFIGFILE] [--debug [LOGGER,LOGGER,...]] [-V]
                      [-d] [-p TEMBOARD_PIDFILE]
temboard-agent: error: unrecognized arguments: register --groups default


Thank you so much !

**Comment by bersace** [comment]
You are running temboard-agent 7.11. I should have point you to https://temboard.readthedocs.io/en/v7/agent_install/#setup-one-instance, sorry.

Do you consider upgrading to 8 ?

**Comment by wolverin26** [comment]
Thank you ! Yes I'm using temboard-agent 7.11. For the moment, we are only using this version but we consider to upgrade to 8 later and not now.

Thank you so much !

**Comment by bersace** [comment]
You're welcome.
