### ISSUE TITLE
Migrate temboard repository to new server?

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#1203]
I need to migrate my temboard server to another host, what's the recommended process?

**Comment by dgiffin** [comment]
Any update?

**Comment by dgiffin** [comment]
And we can just dump/load the repository schema?

**Comment by dgiffin** [comment]
Finally, anything I need to do with the agents as the temboard server has moved to a new host?

**Comment by bersace** [comment]
> Finally, anything I need to do with the agents as the temboard server has moved to a new host?

Hi @dgiffin . As long as the signing key has not changed, you are good to go. The exchanges between agent and UI are initiated by UI. Thus, agent can ignore where is the UI effectively.

**Comment by dgiffin** [comment]
Thanks for your help.
