### ISSUE TITLE
Documentation - temboard-agent - PG env variables

### ISSUE THREAD

**Issue by robinportigliatti** [dalibo/temboard#1228]
Hello,

In the documentation you don't specify we can set environment variable as PGHOST (needs to be a directory), PGUSER, and so on like PGDATA, PGUSER and can also set SYSUSER, ETCDIR, VARDIR, LOGDIR, LOGFILE etc...

Robin,

**Comment by bersace** [comment]
https://temboard.readthedocs.io/en/latest/agent_install/#setup-one-instance

> You must run this script as root, with PG* env vars set to connect to the Postgres cluster you want to manage. By default, the script uses postgres UNIX user to connect to Postgres cluster.

*DIR vars are used for tests in CI and development environment.
