### ISSUE TITLE
temboard-agent fetch-key 405 Not Allowed

### ISSUE THREAD

**Issue by laurentnadot45** [dalibo/temboard#1232]
Hello,

I have a problem during the next installation temBoard  agent :

Version temboard  8.0
Rockylinux 8
```
[postgres@PG152] $ hostnamectl
   Static hostname: repmgr15201
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 94e2b8ec396c4567b1ce6ac3a0f4cd26
           Boot ID: dc3789a438e748b79fa0da77ddec314d
    Virtualization: kvm
  Operating System: Rocky Linux 8.7 (Green Obsidian)
       CPE OS Name: cpe:/o:rocky:rocky:8:GA
            Kernel: Linux 4.18.0-425.13.1.el8_7.x86_64
      Architecture: x86-64
```

```
 PGINST  PG152
 PGPORT  5432
 PGHOME  /usr/pgsql-15
 PGREL   15.2
 PGDATA  /var/lib/pgsql/PG152/data
 PGWAL   /var/lib/pgsql/PG152/data/pg_wal
 PGARCH  /var/lib/pgsql/PG152/archives
 PGADMIN /var/lib/pgsql/admin
 PGLOG   /var/log/postgresql/PG152
```
 L'instance PG152 est démarrée.

```
[root] # /usr/share/temboard-agent/auto_configure.sh  https://172.16.7.81:8888
Using hostname Temboard.lnadot.
Configuring for PostgreSQL user postgres.
Configuring for cluster on port 5432.
Configuring for cluster at /var/lib/pgsql/PG152/data.
Using /usr/pgsql-15/bin/pg_ctl.
Cluster name is PG152.
Configuring temboard-agent in /etc/temboard-agent/PG152/temboard-agent.conf .
Configuring temboard-agent to run on port 2345.
Configuring systemd unit temboard-agent@PG152.service.
Success. You now need to fetch UI signing key using:
    sudo -u postgres temboard-agent -c /etc/temboard-agent/PG152/temboard-agent.conf fetch-key
Then start agent service using:
    systemctl enable --now temboard-agent@PG152.service
See documentation for detailed instructions.


[root] # sudo -u postgres temboard-agent -c /etc/temboard-agent/PG152/temboard-agent.conf fetch-key
INFO:  app: Using config file /etc/temboard-agent/PG152/temboard-agent.conf.
INFO:  fetch_key: Requesting public key from https://172.16.7.81:8888.
ERROR:  app: Unhandled error:
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/app.py", line 351, in entrypoint
	    retcode = self.main(argv, environ)
	  File "/usr/lib/python3.6/site-packages/temboardagent/cli/app.py", line 135, in main
	    return command.main(args)
	  File "/usr/lib/python3.6/site-packages/temboardagent/cli/fetch_key.py", line 42, in main
	    response.raise_for_status()
	  File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/http.py", line 175, in raise_for_status
	    raise TemboardHTTPError(self)
	temboardagent.toolkit.http.TemboardHTTPError: 405: Method Not Allowed
ERROR:  app: temboardagent version is 8.0.
ERROR:  app: This is a bug!
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!
```

thanks a lot for your help

Laurent

**Comment by bersace** [comment]
Bonjour,

Avez-vous un pare-feu entre l'agent et l'UI ?

**Comment by laurentnadot45** [comment]
Bonjour, Non. J'ai également désactivé SELINUX

**Comment by bersace** [comment]
Ça ressemble à un doublon de #1185 et #1180.

**Comment by bersace** [comment]
@laurentnadot45 pouvez-vous nous envoyer les traces DEBUG de temBoard UI ? depuis le redémarrage de l'UI jusqu'à l'erreur 405 ?

**Comment by laurentnadot45** [comment]
Hello,

[root] # journalctl -f -u temboard.service
-- Logs begin at Thu 2023-06-22 11:32:12 CEST. --
juin 28 11:28:20 temboard env[4924]: Starting web.
juin 28 11:28:20 temboard env[4929]: Starting scheduler.
juin 28 11:28:20 temboard env[4929]: Update Task aggregate_data with options={}
juin 28 11:28:20 temboard env[4924]: Serving temboardui on https://0.0.0.0:8888
juin 28 11:28:20 temboard env[4929]: Update Task history_tables with options={}
juin 28 11:28:20 temboard env[4929]: Update Task purge_data with options={}
juin 28 11:28:20 temboard env[4929]: Update Task schedule_collector with options={}
juin 28 11:28:20 temboard env[4929]: Update Task statementsdata with options={}
juin 28 11:28:20 temboard env[4929]: Update Task statements_purge_data with options={}
juin 28 11:28:20 temboard env[4929]: Entering scheduler loop.
juin 28 11:28:26 temboard env[4929]: Pushing task to the worker queue
juin 28 11:28:26 temboard env[4929]: {'worker_name': 'pull_data_worker', 'options': {}, 'status': 2, 'start_datetime': datetime.datetime(2023, 6, 28, 9, 28, 26, 975997), 'redo_interval': 60, 'stop_datetime': None, 'id': 'statementsdata', 'output': '', 'expire': 3600}
juin 28 11:28:26 temboard env[4929]: Pushing task to the worker queue
juin 28 11:28:26 temboard env[4928]: Add Task statementsdata to worker 'pull_data_worker' queue
juin 28 11:28:26 temboard env[4929]: {'worker_name': 'schedule_collector', 'options': {}, 'status': 2, 'start_datetime': datetime.datetime(2023, 6, 28, 9, 28, 26, 975997), 'redo_interval': 60, 'stop_datetime': None, 'id': 'schedule_collector', 'output': '', 'expire': 3600}
juin 28 11:28:26 temboard env[4929]: Pushing task to the worker queue
juin 28 11:28:26 temboard env[4929]: {'worker_name': 'pull_data_worker', 'options': {}, 'status': 2, 'start_datetime': datetime.datetime(2023, 6, 28, 9, 28, 26, 975997), 'redo_interval': 60, 'stop_datetime': None, 'id': 'statements_pull_data', 'output': '', 'expire': 3600}
juin 28 11:28:26 temboard env[4936]: Starting new worker temboardui.plugins.statements.pull_data_worker
juin 28 11:28:26 temboard env[4929]: Received Message={'type': 1, 'content': {'task_id': 'statementsdata', 'status': 4}}
juin 28 11:28:27 temboard env[4928]: Add Task schedule_collector to worker 'schedule_collector' queue
juin 28 11:28:27 temboard env[4928]: Add Task statements_pull_data to worker 'pull_data_worker' queue
juin 28 11:28:27 temboard env[4937]: Starting new worker temboardui.plugins.monitoring.schedule_collector
juin 28 11:28:27 temboard env[4937]: Starting collector scheduler.
juin 28 11:28:27 temboard env[4929]: Received Message={'type': 1, 'content': {'task_id': 'statementsdata', 'status': 8}}
juin 28 11:28:27 temboard env[4929]: Received Message={'type': 1, 'content': {'task_id': 'schedule_collector', 'status': 4}}
juin 28 11:28:27 temboard env[4937]: End of collector scheduler.
juin 28 11:28:27 temboard env[4929]: Received Message={'type': 1, 'content': {'task_id': 'schedule_collector', 'status': 8}}
juin 28 11:28:27 temboard env[4929]: Received Message={'type': 1, 'content': {'task_id': 'statements_pull_data', 'status': 4}}
juin 28 11:28:27 temboard env[4928]: Job schedule_collector is dead
juin 28 11:28:27 temboard env[4928]: Job output : {'type': (5,), 'content': None}
juin 28 11:28:27 temboard env[4928]: Job statementsdata is dead
juin 28 11:28:27 temboard env[4928]: Job output : {'type': (5,), 'content': None}
juin 28 11:28:27 temboard env[4929]: Received Message={'type': 1, 'content': {'task_id': 'schedule_collector', 'status': 16, 'output': None, 'stop_datetime': datetime.datetime(2023, 6, 28, 9, 28, 27, 110128)}}
juin 28 11:28:27 temboard env[4942]: Starting new worker temboardui.plugins.statements.pull_data_worker
juin 28 11:28:27 temboard env[4929]: Received Message={'type': 1, 'content': {'task_id': 'statementsdata', 'status': 16, 'output': None, 'stop_datetime': datetime.datetime(2023, 6, 28, 9, 28, 27, 110772)}}
juin 28 11:28:27 temboard env[4929]: Received Message={'type': 1, 'content': {'task_id': 'statements_pull_data', 'status': 8}}
juin 28 11:28:27 temboard env[4928]: Job statements_pull_data is dead
juin 28 11:28:27 temboard env[4928]: Job output : {'type': (5,), 'content': None}
juin 28 11:28:27 temboard env[4929]: Received Message={'type': 1, 'content': {'task_id': 'statements_pull_data', 'status': 16, 'output': None, 'stop_datetime': datetime.datetime(2023, 6, 28, 9, 28, 27, 215763)}}
juin 28 11:28:34 temboard env[4924]: 405 GET /signing.key (172.16.17.90) 2.05ms

**Comment by bersace** [comment]
Que retourne `temboard --version` ?

**Comment by bersace** [comment]
Ainsi que `temboard routes`.

**Comment by laurentnadot45** [comment]
[root] # temboard-agent --version
temBoard agent 8.0 (/usr/bin/temboard-agent)
System Rocky Linux 8.7 (Green Obsidian)
Python 3.6.8 (/usr/libexec/platform-python)
bottle 0.12.21
cryptography 3.2.1
libpq 15.2
psycopg2 2.8.5 (dt dec pq3 ext lo64)

[root] # temboard --version
 INFO: Starting temboard 7.11.
temBoard 7.11
System Rocky Linux 8.7 (Green Obsidian)
Python 3.6.8 (/usr/libexec/platform-python)
Tornado 6.0.2
psycopg2 2.8.5 (dt dec pq3 ext lo64)
libpq 15.3
SQLAlchemy 1.3.2
alembic 1.0.11

Zut , je crois que je n'ai pas installé le RPM en v8 . Je reviens vers vous. Merci

**Comment by laurentnadot45** [comment]
Bonjour à vous,
Après avoir installé le serveur en version 8.0 tout est OK
[root] # sudo -u postgres temboard-agent -c /etc/temboard-agent/PG152/temboard-agent.conf fetch-key
INFO:  app: Using config file /etc/temboard-agent/PG152/temboard-agent.conf.
INFO:  fetch_key: Requesting public key from https://temboard.lnadot:8888.
INFO:  fetch_key: Validating PEM data.
INFO:  fetch_key: /etc/temboard-agent/PG152/signing-public.pem updated from https://temboard.lnadot:8888.
INFO:  fetch_key: Please reload agent service if running.

Merci à vous

**Comment by bersace** [comment]
C'est malheureux ce 405 plutôt que 404. Merci pour la remontée.
