### ISSUE TITLE
Docker temboard-agent

### ISSUE THREAD

**Issue by MakarovDmitri** [dalibo/temboard#1252]
Hi! Please help me with next question. 
I'm trying to start a container with a Tembord agent, but I get an error in the container log:
2023-09-22 10:05:21 ++ stat -c %u /var/lib/postgresql/data
2023-09-22 10:05:21 stat: cannot statx '/var/lib/postgresql/data': No such file or directory
2023-09-22 10:05:21 + POSTGRES_UID=

Here is my container startup line:
docker run --network network_test --name test -e PGHOST=x.x.x.x -e PGPASSWORD=password -e PGPORT=5432 -e PGUSER=postgres -e TEMBOARD_UI_URL=https://x.x.x.x:8888 -e TEMBOARD_UI_USER=user -e TEMBOARD_UI_PASSWORD= password -e TEMBOARD_GROUPS=default -e TEMBOARD_HOSTNAME=pg_test.xx.xx -d dalibo/temboard-agent:latest
All containers (database, server Temboard and agent Temboard) are located on the same network.
What am I doing wrong?

**Comment by Hugues-Antoine** [comment]
Hello,

The agent needs the data directory of the database, as shown in the example below : https://github.com/dalibo/temboard/blob/master/docker/docker-compose.yml#L62

**Comment by MakarovDmitri** [comment]
> Hello,
> 
> The agent needs the data directory of the database, as shown in the example below : https://github.com/dalibo/temboard/blob/master/docker/docker-compose.yml#L62

Hello!
That’s right, the container Posgresql to which I’m trying to connect the teamboard agent has a directory with a database at the following path - /var/lib/postgresql/data. I'm using the official image from Postgres.

**Comment by bersace** [comment]
Hi @MakarovDmitri . Note that temboard-agent image is not designed for production.

Closing. Please reopen if needed.
