### ISSUE TITLE
Content security policy violation [was: Blank screen after connecting to Temboard]

### ISSUE THREAD

**Issue by jeanloesch** [dalibo/temboard#1266]
Hi,

I had a temboard server 8.0 running on a CentOS7.9 on my testing VM.
redhatrelease
CentOS-7.9-x86_64
uname -a
Linux lyn3e620.tlt 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

It worked very well but when yesterday when I tried to log in to Temboard UI a blank screen is displayed (see attachment).
If I keep clicking very quickly on the Settings button, the list of my Postgres instances is displayed but it disappears straight away.

I upgraded to Temboard 8.1 but I still have the same problem.
rpm -qa|grep -i temboard
temboard-8.1.0-1.el7.noarch

There is no error in the log file (see attachment).
[temboard.zip](https://github.com/dalibo/temboard/files/12866804/temboard.zip)
![Temboard_blank_screen](https://github.com/dalibo/temboard/assets/24730628/1e5ca6e6-c6dd-41bf-8d3c-38461846ba3b)

In my production VM, Temboard 8.0 on CentOS-7.9-x86_64 kernel 3.10.0-1160.88.1.el7.x86_64 works fine.
![Temboard_blank_screen](https://github.com/dalibo/temboard/assets/24730628/e1c87609-2085-442f-a1ae-674667f91b00)

Could you please help ?

Best regards.
[temboard.zip](https://github.com/dalibo/temboard/files/12866812/temboard.zip)

**Comment by bersace** [comment]
Do you have errors in browser console ? (Type F12 to open it).

**Comment by jeanloesch** [comment]
It seems I do (see attachment).
![Browser_console](https://github.com/dalibo/temboard/assets/24730628/cfb83ecb-d5e1-4021-ab79-eeeeaac46252)

**Comment by bersace** [comment]
Did you upgrade your browser ? What browser are you using ?

**Comment by jeanloesch** [comment]
I tested with Chrome, FireFox, MS Edge on my Windows 10 Pro laptop.
My colleague have the same problem on his Ubuntu laptop with Chrome and firefox.

**Comment by bersace** [comment]
Is your SSL certificate validated by the browser ?

**Comment by jeanloesch** [comment]
Yes.
![Browser_certificate](https://github.com/dalibo/temboard/assets/24730628/cb78ff52-a319-4e0b-8be3-315b06103409)

**Comment by bersace** [comment]
Utilisez-vous un mandataire HTTPS devant temBoard ?

**Comment by pgiraud** [comment]
Can you please search for a "Content-Security-Policy" header in the web developer console for the "home" request?

You should be able to find the headers in the network tab. See following picture.

![Screenshot from 2023-10-11 11-57-37](https://github.com/dalibo/temboard/assets/319774/b7833e89-ed7f-4f34-9cd3-eb4c5d0f83bb)

**Comment by jeanloesch** [comment]
The issue was on our side, we added Control Security Policies to our apache configuration which disallowed the use the javascript eval() function. Allowing it again solved the issue.

Thank you very much.

**Comment by bersace** [comment]
Thanks for the feedback. Does apache overwrite CSP for app or is it just a default ?

**Comment by jeanloesch** [comment]
We're using apache 2.4 which doesn't define any CSP by default. Those are just ones we added by ourselves, following a most restrictive approach first

**Comment by bersace** [comment]
Fixed for 8.2. Closing.

Merci @jeanloesch !
