### ISSUE TITLE
Temboard UI does not display metrics for all agents on the main page

### ISSUE THREAD

**Issue by casinoazino** [dalibo/temboard#1321]
Hi Dalibo team. 
I have some problems with temBoard UI.

My main page displays 32 pgsql servers, the first 18 are displayed correctly along with metrics. 
The remaining servers are displayed only with the name, pgsql version and problem type, but the metrics are not displayed.
If I enter in the search a server on which metrics were not displayed, the metric will be displayed.
Is this a bug or does the temBoard server lack resources?
VM spec: 4Gb RAM, 2CPU

Example of display on the main page and after entering the server in the search :
![image](https://github.com/dalibo/temboard/assets/134931863/01fd43cb-495d-4bc6-ae68-d0c72707e10f)
![image](https://github.com/dalibo/temboard/assets/134931863/bc937ef2-3963-40f5-8148-c5a4913343c9)

**Comment by pirlgon** [comment]
Hi it's an in code limitation, only the first 18 instances have graph on them (corresponding to 3 lines of 6 instances) to avoid too many requests.

**Comment by casinoazino** [comment]
Thx!)
