### ISSUE TITLE
Statements not working 

### ISSUE THREAD

**Issue by casinoazino** [dalibo/temboard#1324]
Hi TemBoard team. 
I've been trying for many hours to enable the display statements in TemBoard.

I installed last postgresql-contrib on server.
In the configuration /opt/db/postgresql.conf
turned on
shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.max = 10000
pg_stat_statements.track = top

I did the same inside the database itself.
CREATE EXTENSION pg_stat_statements;
after that I restarted postgresql-11.service

if i look from database SELECT * FROM pg_stat_statements;
 values displayed, but there is no statements menu in TemBoard, and it is also not in the Plugins list, although in fact it is installed and working.

info about specs in the screenshot
Perhaps someone has encountered a similar problem.
![fortemboadissue](https://github.com/dalibo/temboard/assets/134931863/08e350a4-5b3a-4235-9b56-5dcf10b4d9d1)

**Comment by bersace** [comment]
`statements` is missing from `plugins` in temboard agent configuration.

**Comment by casinoazino** [comment]
yeah !) txh .
i need /usr/share/temboard-agent/share/purge.sh   and install configuration again
