### ISSUE TITLE
Question temboard supports pg-xl？

### ISSUE THREAD

**Issue by gh-Devin** [dalibo/temboard#1326]
hey bro, I would like to ask if temboard supports pg-xl? I am using OpenTenBase and plan to incorporate temboard into the ecosystem.

https://github.com/OpenTenBase/OpenTenBase

**Comment by daamien** [comment]
Hi @gh-Devin !

Temboard should work fine with most PostgreSQL forks, although we did not run any specific test on the ones you mention.

Regards,

**Comment by gh-Devin** [comment]
great， Let's me try install

**Comment by daamien** [comment]
Hi @gh-Devin 

Unless you have further question, we are closing this issue.
