### ISSUE TITLE
Compatibilty with Red Hat 9

### ISSUE THREAD

**Issue by egaultier** [dalibo/temboard#1337]
Hello

Have you any information about RedHat9 compatibility for the tembaord-agent ?

Thank you

Emmanuel

**Comment by daamien** [comment]
Hi @egaultier 

Temboard 8 is compatible with RHEL 7 and RHEL 8

More details here:
https://temboard.readthedocs.io/en/latest/compatibility_guide/


We're currently working on Temboard 9 which will support RHEL 8 and RHEL 9

There is no release date at the moment but it's under active development.

**Comment by egaultier** [comment]
Hi @daamien 

Thank for your reply.
I will wait.
