### ISSUE TITLE
Typo: temBoard: SUCESS should be SUCCESS

### ISSUE THREAD

**Issue by wsescu** [dalibo/temboard#1362]
Dear temBoard team

there is a little typo when you try to edit any threshold. SUCESS should be SUCCESS.

![image](https://github.com/dalibo/temboard/assets/54099545/05f83bdf-4315-490f-9fc8-4534e54d92da)

Cheers
William

**Comment by daamien** [comment]
Thanks

Typo is here:
https://github.com/dalibo/temboard/blob/fb588b6c983d5db2f7a8cb43d5b0a16e345f2d3b/ui/temboardui/static/src/components/AlertingChart.vue#L321
