### ISSUE TITLE
Ubuntu noble

### ISSUE THREAD

**Issue by MickaelTheCat** [dalibo/temboard#1485]
Hello

I have to install temboard agent on Ubuntu noble.

Can you update repository ?

Regards

**Comment by daamien** [comment]
@MickaelTheCat hello !

Thanks for this request. 

* Temboard 8 is not officially supported on Ubuntu Noble 24.04 
* Temboard 9 will be officially supported on Ubuntu Jammy 22.04 and Ubuntu Noble 24.04

We're currently preparing the release of Temboard 9. The packages should be available soon

**Comment by MickaelTheCat** [comment]
Hello

Ok for waiting Temboard 9 but will temboard server 9 be compatible with existing agent 8 ? Or agent 9 with temboard server 8 ?

Regards

**Comment by daamien** [comment]
That's a good question.

Temboard server 9 will work with agent 8 and agent 9.

The full update process will be in 3 steps

* upgrade all temboard agents 7 to temboard agents 8
* upgrade temboard server 8 to temboard server 9
* upgrade all temboard agents 8 to temboard agents 9
