### ISSUE TITLE
 error when installing on ubuntu 22 when there will be a release on postgres 16

### ISSUE THREAD

**Issue by Muhtarhan27** [dalibo/temboard#1489]
error when installing on ubuntu 22 when there will be a release on postgres 16

**Comment by daamien** [comment]
Hi @Muhtarhan27 !

Thanks for your request

* Temboard 8 is not officially supported on Ubuntu Jammy 22.04 but packages are available.  It works work with PostgreSQL 10 to 14

* Temboard 9 will be officially supported on Ubuntu Jammy 22.04 and Ubuntu Noble 24.04. It will work with PostgreSQL 12 to 17

We're currently preparing the release of Temboard 9. The packages should be available soon.
