### ISSUE TITLE
The name of the cluster is not displayed in the Dashboard of temboard

### ISSUE THREAD

**Issue by Hindossa** [dalibo/temboard#1492]
Hello,

Is it possible to display the cluster name instead of the server name in the Temboard UI? Each server hosts multiple instances, and it is difficult  to differentiate between them without the name of the cluster.

Thank you.

BR,

**Comment by Qazaq159** [comment]
![image](https://github.com/user-attachments/assets/0193a815-951e-451d-bd3d-ba2b6fbc4939)

more [here](https://temboard-agent.readthedocs.io/en/v7/configuration.html#temboard-section)

/etc/temboard-agent/14/main/temboard-agent.conf here  you need change in **Postgres** section variable **instance**

**Comment by Hindossa** [comment]
[postgresql]
# UNIX socket directory where PostgreSQL is listening.
host = /tmp
# PostgreSQL listening port.
port = 5432
# PostgreSQL connection role.
user = intgtest
# PostgreSQL password if peer authentication is disabled.
# password =
# Default database for connection.
dbname = postgres
instance= integtest


I added the instance variable but i have always the server name in the Temboard UI like : fr-in-test-x.domain:5432

**Comment by Hindossa** [comment]
Hello,

Do you have any suggestions to fix this problem?

Thank you.

BR,

**Comment by Hindossa** [comment]
hello,

Any help for this issue please ? is it possible or not ?

Thank you.

Br,

**Comment by ZhanserikKalmukhambet** [comment]
Hi,

It is possible to set cluster names if you have several instances of some server. Inside temboard agent configuration file (in my case temboard-agent.conf) - you have to modify **temboard** section.

![Screenshot from 2024-10-09 18-44-41](https://github.com/user-attachments/assets/76e3819b-1eec-4a85-a46c-6b9489511bfd)

Here, responsible field for cluster name - **hostname**. Change it to desired cluster name

**Comment by Hindossa** [comment]
hello,

I change the hostname to cluster.hostname and i restarted the agent but there is no effect.
Please, could you help us?

Thank you.
