### ISSUE TITLE
Huge performance problem since upgrading to TemBoard 9 

### ISSUE THREAD

**Issue by MickaelTheCat** [dalibo/temboard#1527]
Hello

At this time (03h48 PM), many hours lag with metrics update :

![image](https://github.com/user-attachments/assets/a00a39fd-8cc6-4f50-8470-1387eecfee49)

Maybe problem with this sql (inside function monitoring.append_state_changes):

temboard=# explain (analyze,buffers) SELECT * FROM monitoring.state_changes WHERE check_id = 31 AND key = 'core_ccam' ORDER BY datetime DESC LIMIT 1;
                                                                 QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=43990.33..43990.33 rows=1 width=40) (actual time=3588.106..3588.165 rows=1 loops=1)
   Buffers: shared hit=84 read=24985
   ->  Sort  (cost=43990.33..43990.33 rows=1 width=40) (actual time=3588.104..3588.163 rows=1 loops=1)
         Sort Key: datetime DESC
         Sort Method: quicksort  Memory: 25kB
         Buffers: shared hit=84 read=24985
         ->  Gather  (cost=1000.00..43990.32 rows=1 width=40) (actual time=3588.073..3588.133 rows=1 loops=1)
               Workers Planned: 2
               Workers Launched: 2
               Buffers: shared hit=81 read=24985
               ->  Parallel Seq Scan on state_changes  (cost=0.00..42990.22 rows=1 width=40) (actual time=2546.982..3469.786 rows=0 loops=3)
                     Filter: ((check_id = 31) AND ((key)::text = 'core_ccam'::text))
                     Rows Removed by Filter: 955978
                     Buffers: shared hit=81 read=24985
 Planning:
   Buffers: shared hit=105 read=11
 Planning Time: 13.012 ms
 Execution Time: 3588.235 ms

--> Index missing ?

temboard=# \d monitoring.state_changes
                    Table "monitoring.state_changes"
  Column  |            Type             | Collation | Nullable | Default
----------+-----------------------------+-----------+----------+---------
 datetime | timestamp with time zone    |           |          |
 check_id | integer                     |           | not null |
 state    | monitoring.check_state_type |           |          |
 key      | character varying(64)       |           |          |
 value    | real                        |           |          |
 warning  | real                        |           |          |
 critical | real                        |           |          |
Indexes:
    "idx_state_changes" btree (datetime, check_id, key)
Foreign-key constraints:
    "state_changes_check_id_fkey" FOREIGN KEY (check_id) REFERENCES monitoring.checks(check_id) ON DELETE CASCADE

temboard=# \dt+ monitoring.state_changes
                                         List of relations
   Schema   |     Name      | Type  |  Owner   | Persistence | Access method |  Size  | Description
------------+---------------+-------+----------+-------------+---------------+--------+-------------
 monitoring | state_changes | table | temboard | permanent   | heap          | 196 MB |
(1 row)

Regards

**Comment by daamien** [comment]
Thanks for reporting this, we 'll investigate quickly

**Comment by MickaelTheCat** [comment]
I had index but that not enough, Linux freeze after few minutes.

Maybe temBoard parallelism is too high for this vm (2 vcpu) : 

temboard    3130    1140  1 15:19 ?        00:00:12 temboard: worker pool
temboard    3906    3130 18 15:20 ?        00:02:54 temboard: task temboardui.plugins.monitoring.collector_batch
postgres    3907    1500 13 15:20 ?        00:02:09 postgres: temboard temboard [local] COMMIT
temboard    4067    3130 19 15:21 ?        00:02:53 temboard: task temboardui.plugins.monitoring.collector_batch
postgres    4068    1500 14 15:21 ?        00:02:08 postgres: temboard temboard [local] idle in transaction
temboard    4234    3130 21 15:22 ?        00:02:55 temboard: task temboardui.plugins.monitoring.collector_batch
postgres    4235    1500 15 15:22 ?        00:02:08 postgres: temboard temboard [local] COMMIT
temboard    5273    3130 20 15:23 ?        00:02:39 temboard: task temboardui.plugins.monitoring.collector_batch
postgres    5274    1500 15 15:23 ?        00:02:01 postgres: temboard temboard [local] idle in transaction
temboard    6223    3130 19 15:24 ?        00:02:17 temboard: task temboardui.plugins.monitoring.collector_batch
postgres    6226    1500 15 15:24 ?        00:01:53 postgres: temboard temboard [local] COMMIT
temboard    7176    3130 17 15:25 ?        00:01:55 temboard: task temboardui.plugins.monitoring.collector_batch
postgres    7178    1500 16 15:25 ?        00:01:47 postgres: temboard temboard [local] idle in transaction
temboard    8091    3130 16 15:26 ?        00:01:37 temboard: task temboardui.plugins.monitoring.collector_batch
postgres    8092    1500 17 15:26 ?        00:01:41 postgres: temboard temboard [local] idle
temboard    8996    3130 15 15:27 ?        00:01:22 temboard: task temboardui.plugins.monitoring.collector_batch
postgres    8998    1500 18 15:27 ?        00:01:38 postgres: temboard temboard [local] idle
temboard   10094    3130 15 15:28 ?        00:01:10 temboard: task temboardui.plugins.monitoring.collector_batch
postgres   10096    1500 18 15:28 ?        00:01:24 postgres: temboard temboard [local] COMMIT
temboard   10936    3130 13 15:29 ?        00:00:56 temboard: task temboardui.plugins.monitoring.collector_batch
postgres   10938    1500 16 15:29 ?        00:01:07 postgres: temboard temboard [local] COMMIT
temboard   11511    3130 13 15:30 ?        00:00:46 temboard: task temboardui.plugins.monitoring.collector_batch
postgres   11512    1500 16 15:30 ?        00:00:56 postgres: temboard temboard [local] SELECT
temboard   12291    3130 12 15:31 ?        00:00:36 temboard: task temboardui.plugins.monitoring.collector_batch
postgres   12293    1500 14 15:31 ?        00:00:41 postgres: temboard temboard [local] SELECT
temboard   12958    3130 12 15:32 ?        00:00:27 temboard: task temboardui.plugins.monitoring.collector_batch
postgres   12961    1500 14 15:32 ?        00:00:32 postgres: temboard temboard [local] idle in transaction
postgres   13506    2269  0 15:33 ?        00:00:00 temboard-agent: task temboardagent.plugins.dashboard.dashboard_collector_batch_worker
temboard   13871    3130 12 15:33 ?        00:00:19 temboard: task temboardui.plugins.monitoring.collector_batch
postgres   13872    1500 14 15:33 ?        00:00:22 postgres: temboard temboard [local] COMMIT
temboard   14585    3130 12 15:35 ?        00:00:11 temboard: task temboardui.plugins.monitoring.collector_batch
postgres   14586    1500 13 15:35 ?        00:00:13 postgres: temboard temboard [local] COMMIT
postgres   15116    1500  0 15:35 ?        00:00:00 postgres: temboard temboard [local] idle
postgres   15117    1500  0 15:35 ?        00:00:00 postgres: temboard temboard [local] idle
postgres   15123    1500  0 15:35 ?        00:00:00 postgres: temboard temboard [local] idle
postgres   15125    1500  0 15:35 ?        00:00:00 postgres: temboard temboard [local] idle
temboard   16166    3130 12 15:36 ?        00:00:04 temboard: task temboardui.plugins.monitoring.collector_batch
postgres   16167    1500 12 15:36 ?        00:00:04 postgres: temboard temboard [local] COMMIT
temboard   16689    3130 14 15:36 ?        00:00:00 temboard: task temboardui.plugins.statements.pull_data_worker

**Comment by MickaelTheCat** [comment]
We added this index : monitoring.state_changes (check_id, key, datetime DESC)

**Comment by bersace** [comment]
How many instances do you manage with temBoard ?

**Comment by MickaelTheCat** [comment]
--> 9 instances

temboard=# select count(*) from monitoring.state_changes;
  count
---------
 3009750
(1 row)

temboard=# \dt+ monitoring.state_changes
                                         List of relations
   Schema   |     Name      | Type  |  Owner   | Persistence | Access method |  Size  | Description
------------+---------------+-------+----------+-------------+---------------+--------+-------------
 monitoring | state_changes | table | temboard | permanent   | heap          | 207 MB |

**Comment by bersace** [comment]
@MickaelTheCat closed by #1538, waiting for 9.0.1 release.

**Comment by bersace** [comment]
@MickaelTheCat do you still have performances issues with the index ?

**Comment by MickaelTheCat** [comment]
No more problem !
