### ISSUE TITLE
Some fields in the instance form should be read-only

### ISSUE THREAD

**Issue by pgiraud** [dalibo/temboard#163]
Fields such as "number of CPU", "Memory size", etc... should be read only.

**Comment by julmon** [comment]
I'd like to keep them editable. This could be useful when the agent can't be reached when registering it.

**Comment by pgiraud** [comment]
What we decided to do is the following:
 - rename the "get instance's information" to "test instance". This will just check if the instance is reachable.
 - remove instance information fields (we don't actually need to show nor edit them),
 - "save" button should get the instance information before saving. If there is any error when trying to get instance information, the user won't be able to create or edit the instance.

**Comment by pgiraud** [comment]
There's actually no need for a "test instance" button anymore since the "save" button is eventually doing the discovering itself.
