### ISSUE TITLE
Auto-register fails if "local_instances" group doesn't exist

### ISSUE THREAD

**Issue by pgiraud** [dalibo/temboard#187]
Please close the current issue if this is intended.

`temboard-agent-register` is called with `--groups local_instances`. This group may not be available in temboard UI reposistory database.
In my opinion, this should not prevent the agent to auto register.

**Comment by julmon** [comment]
Default value for option `--groups` should be set to `default`.

**Comment by pgiraud** [comment]
This is where the `temboard-agent-register` is called:
https://github.com/dalibo/temboard-agent/blob/master/docker/entrypoint.sh#L76

**Comment by julmon** [comment]
@pgiraud is this issue still relevant ?

**Comment by pgiraud** [comment]
@julmon it's still relevant. Calling the auto register command with a wrong value for --groups results in a 400 Bad Request from the UI.
We could also consider this as a blocker for registering an instance and close the current issue. I can live with it.
