### ISSUE TITLE
Multiple PostgreSQL Instances on a Host?

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#190]
I was wondering how/if the temboard agent could be configured to monitor multiple PostgreSQL instances on the same host? I couldn't find any mention of this is the documentation.

Thanks,

  David

**Comment by bersace** [comment]
Hi,

Managing multiple instances in a single agent can looks easier for user, but actually it tight couple Postgres instance and lead to additionnal codes for something easier to manage outside the project.

Do you have issue spawning several agents on same host ?

Regards,

**Comment by dgiffin** [comment]
No, I could run up 2 tempboard-agents, one to monitor each PostgreSQL instance - any suggestions on the best way to do that please?

**Comment by bersace** [comment]
Hi,

I suggest you to create two directories in `/etc/temboard-agent`, one for each agent. The next step is to have a instanced service unit. We don't provide yet et instanced unit. see http://0pointer.de/blog/projects/instances.html and systemd manual.

**Comment by dgiffin** [comment]
Not bothered (yet) about system controlling the temboard-agent :-) I can work with this I think, 2 config files etc - thanks very much for your quick response!

**Comment by bersace** [comment]
Note that pathes in temboard-agent.conf can be relative to `.conf` file. This make it easier to move a `.conf` file. Keep us tuned if you succeed and how :)

**Comment by dgiffin** [comment]
That worked fine as per your suggestion - thanks.
