### ISSUE TITLE
temboard-agent: [supervision_sender_worker] ERROR: HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard#191]
This error repeats in temboard-agent.log and supervision charts are empty.

Please let me know what information you need to diagnose.

We have agents where supervision charts work and agents where they do not work. There are no notable differences in .conf files.

**Comment by bersace** [comment]
@bsislow thanks for the report. Can you post a full traceback ?

cc @julmon

**Comment by julmon** [comment]
Hi,

@bsislow could you please update to the last versions : 
- temboard-agent: https://github.com/dalibo/temboard-agent/releases/tag/1.0a5
- temboard: https://github.com/dalibo/temboard/releases/tag/1.0a2

Please send us a full traceback extracted from temboard UI logs.

Regards,

**Comment by bsislow** [comment]
When you say "traceback" - can you provide steps to do this or do you simply want me to upload a portion of the temboard-agent.log file?

**Comment by bersace** [comment]
@bsislow just the full log output if you have. I think you have to enable debug logging to have the full traceback.

**Comment by bsislow** [comment]
Hello - sorry for the late reply. We are just going to try the newer version instead.

**Comment by julmon** [comment]
Hi,

Can we close this issue ? Do you have any other question on this subject ?

Regards,

**Comment by bsislow** [comment]
You may close this issue.

**Comment by bsislow** [comment]
Please re-open this as the new version is having some issues as well.
We need to have the charts working in the current release.
