### ISSUE TITLE
Not picking up port from config file

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#192]
Setting up the temboard server on a new host and have a problem, it doesn't see to be reading the postgresql port number from the config file:

[root@pem01 dgiffin]# temboard -c /etc/temboard/temboard.conf --debug
FATAL: (OperationalError) could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

[root@pem01 dgiffin]# grep port /etc/temboard/temboard.conf
# Bind port
port = 8888
# PG port number.
port = 45221
[root@pem01 dgiffin]#
[root@pem01 dgiffin]# ls -la /var/run/postgresql/
total 4
drwxrwxr-x  2 postgres postgres   80 Aug  4 14:53 .
drwxr-xr-x 29 root     root     1000 Aug  9 05:47 ..
srwxrwxrwx  1 postgres postgres    0 Aug  9 05:20 .s.PGSQL.45221
-rw-------  1 postgres postgres   55 Aug  9 05:20 .s.PGSQL.45221.lock
[root@pem01 dgiffin]#

Any thoughts?

Also - is there a --version option to check the version we are running?

**Comment by dgiffin** [comment]
Hmm, if I export PGPORT=45221 then I get a bit further so that port setting on 45221 in the config file does not seem to be read - weird!

**Comment by dgiffin** [comment]
Anyone? This is stopping our deployment.

**Comment by dgiffin** [comment]
If it's any help I'm uploading the log file and config file, the run command I used was:

/usr/bin/temboard -c /etc/temboard/temboard.conf -p /var/run/temboard/temboard.pid --debug

[root@pem01 run]# /usr/bin/temboard -c /etc/temboard/temboard.conf -p /var/run/temboard/temboard.pid --debug
FATAL: (OperationalError) could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by dgiffin** [comment]
[temboard_conf.txt](https://github.com/dalibo/temboard/files/1231063/temboard_conf.txt)
[temboard_log.txt](https://github.com/dalibo/temboard/files/1231064/temboard_log.txt)

**Comment by dgiffin** [comment]
and the output from strace...
[temboard_strace.txt](https://github.com/dalibo/temboard/files/1231086/temboard_strace.txt)

**Comment by julmon** [comment]
Hi,

Sorry for this late reply. Just took a look at your configuration file and it seems this file is not well formatted: line 22 must not be commented.

Regards,

**Comment by dgiffin** [comment]
Thanks for that, but it doesn't seem to have helped, I'm still getting the same error.

temboard[12046]: [temboardui.utils        ]  WARNING: Failed to connect to database: (OperationalError) could not connect to server: No such file or directory
temboard[12046]: [temboardui.utils        ]  WARNING:   Is the server running locally and accepting
temboard[12046]: [temboardui.utils        ]  WARNING:   connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
temboard[12046]: [temboardui.utils        ]  WARNING:  None None
temboard[12046]: [temboardui.utils        ]     INFO: Retrying in 8s.
temboard[12046]: [temboardui              ]  WARNING: Connection to the database failed: (OperationalError) could not connect to server: No such file or directory
temboard[12046]: [temboardui              ]  WARNING:   Is the server running locally and accepting
temboard[12046]: [temboardui              ]  WARNING:   connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
temboard[12046]: [temboardui              ]  WARNING:  None None
temboard[12046]: [temboardui              ]  WARNING: Please check your configuration.
FATAL: (OperationalError) could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
[temboard_conf.txt](https://github.com/dalibo/temboard/files/1241076/temboard_conf.txt)

**Comment by dgiffin** [comment]
Ah ha! I changed the Unix socket path setup from:
[repository]
# Unix socket path.
host = /var/run/postgresql

to:
[repository]
# Unix socket path.
host=127.0.0.1

and the process is running now.
