### ISSUE TITLE
FATAL: local variable 'fp_s' referenced before assignment

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#194]
Wondered if anyone could tell me what this error means and how I can address it?

temboard-agent -p /var/lib/temboard-agent/main/temboard-agent.pid
FATAL: local variable 'fp_s' referenced before assignment

Many thanks,

  David

**Comment by dgiffin** [comment]
/etc/temboard-agent(postgres:45221)$ temboard-agent -p /var/lib/temboard-agent/main/temboard-agent-pid -c /etc/temboard-agent/temboard-agent.conf
FATAL: local variable 'fp_s' referenced before assignment

strace -o strace.txt temboard-agent -p /var/lib/temboard-agent/main/temboard-agent-pid -c /etc/temboard-agent/temboard-agent.conf

In the strace.txt file:
stat("/usr/lib/python2.7/site-packages/temboardagent/plugins/supervision/compat", 0x7ffffd602310) = -1 ENOENT (No such file or directory)

/usr/lib/python2.7/site-packages/temboardagent/plugins(postgres:45221)$ ls -lh
total 12K
drwxr-xr-x 2 root root  150 Aug  3 13:27 activity
drwxr-xr-x 2 root root  146 Aug  3 13:27 administration
drwxr-xr-x 2 root root  111 Aug  3 13:27 dashboard
drwxr-xr-x 2 root root   43 Aug  3 13:27 hello
-rw-r--r-- 1 root root    0 Aug  3 13:27 __init__.py
-rw-r--r-- 1 root root  157 Aug  3 13:27 __init__.pyc
drwxr-xr-x 2 root root 4.0K Aug  3 13:27 monitoring
drwxr-xr-x 2 root root 4.0K Aug  3 13:27 pgconf

That directory (supervision) doesn't exist:
ln -s administration supervision

Now it works

**Comment by bersace** [comment]
Hi @dgiffin,

`supervision` is the old name of `monitoring`. You should replace any `supervision` with `monitoring` in any configuration file.

**Comment by dgiffin** [comment]
Does to be clear:

1) remove the symbolic link

2) update the following in temboard-agent.conf to replace supervision with monitoring:

# Plugins in use.
plugins = ["supervision", "dashboard", "settings", "administration", "activity"]

[supervision]
# Supervision plugin part.

# Collector URL.
collector_url = https://10.175.6.41:8888/supervision/collector

(not sure about that last one)

**Comment by bersace** [comment]
Yes, the collector URL too if temboard ui is uptodate.

Which versions of temboard and temboard-agent do you use ?

**Comment by dgiffin** [comment]
How can I tell?

**Comment by bersace** [comment]
`pip freeze` should do the trick.

**Comment by dgiffin** [comment]
there's no '--version' option

**Comment by bersace** [comment]
@dgiffin yes, it's missing :(

**Comment by dgiffin** [comment]
temboard==1.0a3
temboard-agent==0.0.2

**Comment by bersace** [comment]
Thanks @dgiffin !

You should update the agent with `pip install --pre --upgrade temboard-agent`.

**Comment by dgiffin** [comment]
Ok, seems to be working now with 1 exception, in the GUI the Configuration option for an instance gives me a "URL not found" error - any ideas?

**Comment by bersace** [comment]
@dgiffin do you run `temboard` and `temboard-agent with debug messages ? This will show traceback. Can you post the traceback ?

**Comment by dgiffin** [comment]
[temboard.log.gz](https://github.com/dalibo/temboard/files/1310668/temboard.log.gz)
[temboard-agent.log.gz](https://github.com/dalibo/temboard/files/1310667/temboard-agent.log.gz)

**Comment by bersace** [comment]
Thanks @dgiffin you should also rename `settings` with `pgconf`. cf. #142

**Comment by dgiffin** [comment]
Sorry, I don't understand what you mean.

**Comment by bersace** [comment]
Le lundi 18 septembre 2017 à 13:04 +0000, dgiffin a écrit :
> Sorry, I don't understand what you mean.

No worry :-)

In both `.conf` files, ensure you don't have `settings` in `plugins`
but rather `pgconf`.

Étienne

**Comment by dgiffin** [comment]
Made the change to the config file but still get the URL not found error for the instance Configuration

**Comment by bersace** [comment]
Can you point me configurations and logs ?

**Comment by dgiffin** [comment]
Don't think I restarted - all good now - thanks very much.

**Comment by bersace** [comment]
@dgiffin nice ! Thanks for giving it a try ! :-)
