### ISSUE TITLE
Showing swap activity on dashboard ?

### ISSUE THREAD

**Issue by nnn-dev** [dalibo/temboard#2]
(improvement)

Can you add a graph for swap activity on dashboard?
We use it to know if the server suffers.

Regards

**Comment by julmon** [comment]
Hello,

Yes, I can do it. Perhaps a simple gauge showing swap usage (%) should be sufficient.

Regards,

**Comment by nnn-dev** [comment]
Hello

Yes. It's perfect.

Thanks

**Comment by ioguix** [comment]
Hi,

I would suggest a swapIn/swapOut. A gauge with swap usage is quite useless if the swap activity was in the past and the swap not acceded anymore. Visualizing that swapIn/SwapOut are active in real time is much more interesting.

**Comment by julmon** [comment]
@ioguix +1

**Comment by nnn-dev** [comment]
@ioguix +1 it's a great idea

**Comment by bersace** [comment]
Should be done now. Closing.
