### ISSUE TITLE
PostgreSQL Include config file not being read

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#200]
We use an 'include' configuration file and noticed that in the Configuration page for an instance this isn't being checked, so we see warning (for example) that the port for the instance has changes pending and that the instance should be restarted, but this is false as the port in postgresql.conf is overwritten by the value in our include file.

We can fix this by commenting out the parameters from the postgresql.conf file that we overwrite in our include file, but thought I should point this out as potentially giving rise to instance restarts that are not needed.

**Comment by bersace** [comment]
@dgiffin thanks for the report. Yes, that's misleading.

temBoard uses PostgreSQL queries to manage settings ( see https://github.com/dalibo/temboard-agent/blob/master/temboardagent/plugins/pgconf/functions.py#L421 ).

What happen if you change a settings through `ALTER SYSTEM SET` rather than editing `postgresql.conf` ?

**Comment by dgiffin** [comment]
Then the value I have set gets reported:

(Value not initially specified anywhere)
alter system set wal_keep_segments=10;

The Configuration page for the database shows this as a warning:
Current value blank
Pending value 10

and says I need to reload the configuration.

**Comment by bersace** [comment]
@dgiffin this is a base feature of PostgreSQL : the `pg_settings` view have `pending_restart` attribute telling whether the cluster need reload or restart.

``` sql
> SELECT name, setting, pending_restart FROM pg_settings WHERE name = 'wal_keep_segments';
```

**Comment by julmon** [comment]
Commit  https://github.com/dalibo/temboard-agent/commit/6c201147363ce736ac685f3d64619a9cadb4331f fixes the issue.

**Comment by julmon** [comment]
`1.2` is out, including this fix.
