### ISSUE TITLE
Upgrade Documentation

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#213]
We need documentation on how to upgrade, in particular what needs to be done to the repository database as we upgrade from earlier versions (we have both 0.0.1 and 0/1.0a3 installed). We want to be on the current version across our estate.

Thanks,

**Comment by julmon** [comment]
Hi,

We're working on releasing version 1.1, including RPM packages. Release notes will include the upgrade documentation.

Regards,

**Comment by dgiffin** [comment]
That's great news! We'll wait for the 1.1 release and plan to upgrade to that, out SysAdmins will be happy it will be an RPM too ;-)

**Comment by dgiffin** [comment]
Do you have a rough ETA for v1.1 so I can pencil it into our work schedule?

**Comment by dgiffin** [comment]
Any update on the ETA for v1.1?

**Comment by dgiffin** [comment]
Any update on this?

**Comment by julmon** [comment]
Hi,

I'm back with good news, temboard 1.1 is out. RPM packages are up-to-date on https://packages.temboard.io/yum/

Upgrade documentation and process are ready : 

- For the agent : http://temboard-agent.readthedocs.io/en/latest/temboard-agent-upgrade.html
- For the UI/repository : http://temboard.readthedocs.io/en/latest/temboard-upgrade-0.0.1-1.1/

1.0a to 1.1 upgrade only needs package update.

Regards,

**Comment by dgiffin** [comment]
Thant's great news, thanks!

What about upgrading from version 0 (pip installed) to 1.1?

[dgiffin@pem01 ~]$ pip list|grep temboard
temboard (1.0a3)
temboard-agent (0)

**Comment by julmon** [comment]
For upgrading from 0 to 1.1 (agent), you can follow this (excepting for RPM parts) http://temboard.readthedocs.io/en/latest/temboard-upgrade-0.0.1-1.1/
I'd recommend to make a backup of your configuration files before. Upgrade with pip can be done by `pip install temboard-agent --upgrade`

**Comment by julmon** [comment]
@dgiffin I'm closing this one. Feel free to reopen it if needed.
