### ISSUE TITLE
v1.1 temboard server socket problem

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#246]
I am getting an error trying to start the temboard server:

2018-01-09 06:52:17,581 temboard[13904]: [temboardui.utils] WARNING: Failed to connect to database: (OperationalError) could not connect to server: No such file or directory
2018-01-09 06:52:17,581 temboard[13904]: [temboardui.utils] WARNING:    Is the server running locally and accepting
2018-01-09 06:52:17,581 temboard[13904]: [temboardui.utils] WARNING:    connections on Unix domain socket "/var/run/postgresql//.s.PGSQL.5432"?

My database is listening on a different port:

# PG port number.
port = 45221

and therefore obviously my socket files are named accordingly:
# Unix socket path.
host = /var/run/postgresql

[root@pem01 temboard]# ls -lah /var/run/postgresql/
total 4.0K
drwxrwxr-x  2 postgres postgres   80 Jan  9 06:59 .
drwxr-xr-x 30 root     root     1.1K Jan  9 06:58 ..
srwxrwxrwx  1 postgres postgres    0 Jan  9 06:59 .s.PGSQL.45221
-rw-------  1 postgres postgres   55 Jan  9 06:59 .s.PGSQL.45221.lock

So why isn't temboard using the correct socket files?

**Comment by dgiffin** [comment]
Found it, the temboard.conf file as supplied in the RPM as the repository line commented out:

# Let's use defaults / env var for repository
# [repository]

Can I suggest that you change that for a future release to

# Let's use defaults / env var for repository
[repository]

??

**Comment by julmon** [comment]
Hi,

My bad, I forgot to include the RPM dedicated configuration file...

https://github.com/dalibo/temboard/commit/9fe1ad0d6b74df078b404eca88020aa98edd6df9
https://github.com/dalibo/temboard/commit/34107fc545e1e6a2534d6cb470ee87f969a6d07f

Going to release 1.2 ASAP because default configuration file from RPM package is not fine.

**Comment by julmon** [comment]
`1.2` is out, including this fix.
