### ISSUE TITLE
Cache Hit Ratio display is wrong

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#250]
v1.1
repmgr primary database - not sure if this is significant but it's the only one of 7 monitored databases where I see this.

The Cache Hot Ratio display in the Dashboard is wrong, showing read 122% and hit -22%.
<img width="1007" alt="cache_hit_ratio" src="https://user-images.githubusercontent.com/4103061/34877816-7f1cdf7c-f79f-11e7-8a41-29d100a55a27.png">

**Comment by julmon** [comment]
Shame on me... hitratio formula from dahsboard plugin was totally wrong. This is now fixed : https://github.com/dalibo/temboard-agent/commit/7eea3bf5a7175059d8751bb5bb62b275bfaf33ff

**Comment by julmon** [comment]
1.2 is out, including this fix.
