### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/temboard#257]
Hi,

I don't see a changelog. 

For example, it would be handy to know if and when temboard is PG10-compatible.

**Comment by julmon** [comment]
Hi,

That's right, there is no changelog for the moment. I'll take care of it for the next release.
BTW, PG10 support have been introduced by this commit https://github.com/dalibo/temboard-agent/commit/aff7c22e65927f2467c2148307ccb0511fb655dc

Thank you

**Comment by julmon** [comment]
We don't plan to maintain a changelog file, but you can check the release page on github: https://github.com/dalibo/temboard/releases
