### ISSUE TITLE
Updates to spec file and patches

### ISSUE THREAD

**Issue by devrimgunduz** [dalibo/temboard#277]
Hi,

While pushing temboard to PostgreSQL RPM repo, I made lots of changes to spec file, unit file, patch, etc:

https://git.postgresql.org/gitweb/?p=pgrpms.git;a=tree;f=rpm/redhat/master/temboard/master;h=ab7f823685f8fb1783edb68b977726421742507f;hb=HEAD

Now the package works out of the box. Feel free to commit all of these under rpm/ directory.

Regards, Devrim

**Comment by julmon** [comment]
Hi @devrimgunduz !

Big thanks ! Anyway, it seems that temboard-agent package is missing from PGDG repo : https://github.com/dalibo/temboard-agent/tree/master/rpm

Regards,

**Comment by devrimgunduz** [comment]
Oh! Sorry about that. Will fix.

**Comment by devrimgunduz** [comment]
Hi,

Pushed temboard-agent to repos. They will appear in next 1 hour. I almost rewrote the spec file and the conf patch, so feel free to grab it from here:

https://git.postgresql.org/gitweb/?p=pgrpms.git;a=tree;f=rpm/redhat/master/temboard-agent/master;h=5da170f8597dc201b82117e44b2d49c9908c46e8;hb=HEAD

Regards, Devrim
