### ISSUE TITLE
Purge old data?

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#282]
How is old data purged from the temboard server database?

**Comment by julmon** [comment]
Hi,

For the moment, there is no mechanism to purge old data.

Regards,

**Comment by blogh** [comment]
Hi,

In the mean time, is it safe to purge via  history_range  in the metric_*_history tables ?

Regards,

**Comment by julmon** [comment]
Hi,

We are going to work on partitioning `*_history` tables in version 3, this will help a lot for the purge of old data, but.. will require a DB repository upgrade to postgres 10.

**Comment by madtibo** [comment]
proposal in https://github.com/dalibo/temboard/pull/627

**Comment by bsislow** [comment]
Any traction here? Our temboard instance is getting very slow and it may be due to a lack of purging.
