### ISSUE TITLE
Error running /usr/share/temboard/sql/upgrade-0.0.1-1.1.sql

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#283]
I am upgrading the repository as part of a temboard upgrade. I run /usr/share/temboard/sql/monitoring.sql successfully, but get and error when running the upgrade script:

devpg-temp01.chi:/home/postgres(postgres:45221)$ psql -U temboard -d temboard -f /usr/share/temboard/sql/upgrade-0.0.1-1.1.sql
BEGIN
ALTER SCHEMA
DO
GRANT
GRANT
GRANT
INSERT 0 0
INSERT 0 0
INSERT 0 0
INSERT 0 0
INSERT 0 0
INSERT 0 0
INSERT 0 0
INSERT 0 0
INSERT 0 0
INSERT 0 0
INSERT 0 0
INSERT 0 0
INSERT 0 0
INSERT 0 0
INSERT 0 0
INSERT 0 0
INSERT 0 0
psql:/usr/share/temboard/sql/upgrade-0.0.1-1.1.sql:45: ERROR:  function metric_tables_config() does not exist
LINE 1: SELECT metric_tables_config()->json_object_keys(metric_table...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT metric_tables_config()->json_object_keys(metric_tables_config())
CONTEXT:  PL/pgSQL function monitoring.history_tables() line 10 at FOR over SELECT rows
ROLLBACK
devpg-temp01.chi:/home/postgres(postgres:45221)$

**Comment by julmon** [comment]
Hi,

Could you retry with:
```console
$ PGOPTIONS="--search_path=monitoring,public" psql -U temboard -d temboard -f \
     /usr/share/temboard/sql/upgrade-0.0.1-1.1.sql
```

Regards,

**Comment by dgiffin** [comment]
That fixed the problem, many thanks.
