### ISSUE TITLE
New instance does not show up if not in "default" instance group

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard#288]
hello - we have a brand new installation of temboard server and temboard-agent.

when we added the first new instance, we did not put it in the "default" instance group and created a new group called "admin."

it does not show up on the home page when we only have it in "admin." if we add it to "default" AND "admin," it shows up.

if we do not have it in _any_ groups, we still do not see it.

so - it appears "default" is required? is this expected behavior?

**Comment by julmon** [comment]
Hello,

What user groups are associated to `admin` instance group ? You can check that by going to `Settings` -> `Instance groups`. I guess you'd associate `admin` user group to your `admin` instance group.

Regards,

**Comment by bsislow** [comment]
admin is in the admin group only

i believe you can close this as this is all expected behavior...

If the database is in NO instance groups it doesn’t appear on the home page

If the database is in ANY instance group it DOES appear on the home page IF the instance group is assigned to the user group you are logged in as

**Comment by julmon** [comment]
That's right, this is the expected behaviour.
