### ISSUE TITLE
Update instance information automatically

### ISSUE THREAD

**Issue by pgiraud** [dalibo/temboard#299]
The instance information (hostname, PG version, number of CPU, etc...) are either discovered ("get instance information" button) or manually set by user when adding an instance in the settings section.
Some of these information may not stay accurate over time.
We need to add a service that will populate the directory database with the additionnal information automatically.
Moreover this should not be user's mission to get this updated so this should be done on a regular basis so that instance changes (for example an upgrade) get shown in the UI.
See #118

**Comment by pgiraud** [comment]
See also #666

**Comment by daamien** [comment]
this will be closed by https://github.com/dalibo/temboard/issues/955
