### ISSUE TITLE
Improve contrast in activity tables

### ISSUE THREAD

**Issue by pgiraud** [dalibo/temboard#314]
![screenshot from 2018-04-13 10-56-20](https://user-images.githubusercontent.com/319774/38726042-52237d9e-3f09-11e8-96e9-31766f08396e.png)

This may not be easy to read.

**Comment by pgiraud** [comment]
@ioguix Would the following be sufficiently contrasted in your opinion?
![screenshot from 2018-04-18 11-42-32](https://user-images.githubusercontent.com/319774/38924604-af7df418-42fd-11e8-9c6b-352624c9af7f.png)

**Comment by pgiraud** [comment]
I understand what you mean by clear theme. I also think that those cells with a bright background colors are a bit agressive.
One option would be to change the success / danger colors globaly.
Using lightened colors as cell background doesn't seem to work well.

What about this:
![screenshot from 2018-04-19 15-04-50](https://user-images.githubusercontent.com/319774/38993463-013665b0-43e4-11e8-93e2-3debc1fa0ec4.png)


One important thing here: I think I miss the user needs. I don't know how important those cells are compared to others. How useful it is for the user to be able to immediatly identify the corresponding backends with an "idle in transaction" state.

**Comment by ioguix** [comment]
I think it's better. However, green/light might not be that readable.

Did you tried with black text on washed-color background?

I would say "idle in xact" is worrying if the xact was inactive for X amount of time, but it depend on the application behavior...
