### ISSUE TITLE
repository vs pgsql cluster

### ISSUE THREAD

**Issue by pmpetit** [dalibo/temboard#336]
Hello,
Something not very clear in my mind :

I guess, the agent is running queries on the cluster and sent result to the repo. Data on the repo are aggregated on year for exmaple...

Do all metrics comes from the repository, or do the UI execute qry on the monitored cluster (thrgough the agent) to get active session in real time for example ?

Thanks

**Comment by julmon** [comment]
Hi,

Not all metrics are coming from the repo, only those used in monitoring and alerting plugin.
