### ISSUE TITLE
powa plugin

### ISSUE THREAD

**Issue by pmpetit** [dalibo/temboard#345]
Hello,
in the "Graph. Tools Dev Meeting - PGConfEU 2017", you said that maybe there will be a powa plugin for temboard.

Do you have more information about when the first beta release will be available ?
if possible, we'd like to participate, with you as leader...
thanks

**Comment by julmon** [comment]
Hello,

We still plan to add a way to track and display slow queries, but not sure how for the moment: powa plugin ? pure pg_stat_statements plugin ? log parsing ?
About the roadmap, we're currently working on releasing version 2, this release will be focused on alerting and monitoring stuffs. So, I don't know exactly when this will be done and when we can start to work on slow queries.

We stay in touch about this topic in few weeks.

Thanks,

**Comment by julmon** [comment]
Not relevant anymore, please see #632
