### ISSUE TITLE
"No data available" on Monitoring Page for >1 Day

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard#346]
Versions installed:
temboard.noarch              1.2.1-1.el7.centos      @temboard-rhel7
temboard-agent.noarch        1.2-1.el7.centos        @temboard-rhel7

We get the following if we choose more than 24 hours of historical viewing for the Monitoring page:

![image](https://user-images.githubusercontent.com/30243584/40723452-9527f3c2-63e4-11e8-965f-0fe58cea0809.png)

How do we prevent this?

What do you need to see from our .conf files?

Thanks.

**Comment by julmon** [comment]
Hello,

It seems that the process in charge of aggregating and history data do not do its job anymore.
Could you try to remove this file `/var/lib/temboard/task_list` and then restart `temboard` ?

Regards,

**Comment by bsislow** [comment]
Thanks, I've done that. Do we have to wait for new data to aggregate or should this allow for us to see old data immediately?

We still see "No data available" on the same agent/host that we sent a screenshot on above.

**Comment by julmon** [comment]
Depending on the amount of data to process, it could take age.
Could you show me temboard logs please ?

**Comment by bsislow** [comment]
Can we send the logs to an email address to keep the contents private please?

**Comment by julmon** [comment]
Sure, here's mine: julmon at gmail dot com

**Comment by bsislow** [comment]
Email sent with attachment temboard.zip - please confirm receipt.

**Comment by julmon** [comment]
Let's continue here. 

It seems to be related to performance issues when `temboard` is trying to aggregate data if the volume of data to process is quite large (~70 days).

This PR #355 should fix it by limiting amount of data to 1 day max.

@bsislow could you try this fix ?

To proceed:
 - SSH to `temboard` UI machine
 - fetch this file https://raw.githubusercontent.com/julmon/temboard/44aa007871b38fedd691aeceaabad713519e67be/share/sql/upgrade-1.2.1-1.2.2.sql
 - apply this script to `temboard` DB: `$ sudo -u postgres psql temboard -f upgrade-1.2.1-1.2.2.sql`
 - and let's see what this SQL query returns : `SET search_path TO monitoring; SELECT * FROM aggregate_data();`

**Comment by bsislow** [comment]
Killed existing hung process, applied fix above, and reran query... resulted in an ERROR:

`temboard=# \c temboard temboard
Password for user temboard:
You are now connected to database "temboard" as user "temboard".
temboard=# \timing on
Timing is on.
temboard=# SET search_path TO monitoring;
SET
Time: 0.204 ms
temboard=# SELECT * FROM aggregate_data();
NOTICE:  WITH expand AS (SELECT datetime, instance_id, dbname, record FROM metric_sessions_current WHERE datetime <@ '["2018-03-27 10:00:00-05","2018-03-28 10:00:00-05")'::TSTZRANGE UNION SELECT (hist_query.record).datetime, instance_id, dbname, hist_query.record FROM (SELECT instance_id, dbname, unnest(records)::metric_sessions_record AS record FROM metric_sessions_history WHERE history_range && '["2018-03-27 10:00:00-05","2018-03-28 10:00:00-05")'::TSTZRANGE) AS hist_query) SELECT * FROM expand WHERE datetime <@ '["2018-03-27 10:00:00-05","2018-03-28 10:00:00-05")'::TSTZRANGE ORDER BY datetime ASC;
NOTICE:  WITH expand AS (SELECT datetime, instance_id, dbname, record FROM metric_sessions_current WHERE datetime <@ '["2018-03-27 00:00:00-05","2018-03-28 00:00:00-05")'::TSTZRANGE UNION SELECT (hist_query.record).datetime, instance_id, dbname, hist_query.record FROM (SELECT instance_id, dbname, unnest(records)::metric_sessions_record AS record FROM metric_sessions_history WHERE history_range && '["2018-03-27 00:00:00-05","2018-03-28 00:00:00-05")'::TSTZRANGE) AS hist_query) SELECT * FROM expand WHERE datetime <@ '["2018-03-27 00:00:00-05","2018-03-28 00:00:00-05")'::TSTZRANGE ORDER BY datetime ASC;
...
...
ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
CONTEXT:  SQL statement " INSERT INTO metric_filesystems_size_30m_current   SELECT     truncate_time(datetime, '30m') AS datetime,     host_id,     mount_point,     ROW(       NULL,       AVG((r).used),       AVG((r).total),       (r).device     )::metric_filesystems_size_record,     COUNT(*) AS w   FROM     expand_data('metric_filesystems_size', (SELECT tstzrange(MAX(datetime), MAX(datetime) + '1 day'::interval) FROM metric_filesystems_size_30m_current))     AS (       datetime timestamp with time zone,       host_id integer,       mount_point text,       r metric_filesystems_size_record     )   WHERE     truncate_time(datetime, '30m') < truncate_time((SELECT MAX(datetime) + '1 day'::interval FROM metric_filesystems_size_30m_current), '30m')   GROUP BY 1,2,3,(r).device   ORDER BY 1,2,3 ON CONFLICT (datetime, host_id, mount_point) DO UPDATE SET w = EXCLUDED.w, record = EXCLUDED.record WHERE metric_filesystems_size_30m_current.w < EXCLUDED.w "
PL/pgSQL function aggregate_data() line 18 at EXECUTE
Time: 37159.116 ms (00:37.159)`
