### ISSUE TITLE
Activity: query list should be sorted by numeric value (not string repr.) of Write/s and Read/s columns

### ISSUE THREAD

**Issue by julmon** [dalibo/temboard#366]
Please see the screenshot below:
![bug-sort-write](https://user-images.githubusercontent.com/920753/41594136-ade40aca-73c2-11e8-9499-192ec9c7c570.png)

**Comment by pgiraud** [comment]
Currently temboard-agent sends human readable values for read/s and write/s.
One option would be to have the agent send raw value. It would then be client's job to humanize the values.
On this topic, I don't think that the memory values are humanized nor on server neither on client side.

The second option is to deshumanize values client side when sorting values. PR in progress: https://github.com/dalibo/temboard/pull/367

**Comment by pgiraud** [comment]
Fixed via #367
