### ISSUE TITLE
Confused with agent users and UI users

### ISSUE THREAD

**Issue by mrechte** [dalibo/temboard#368]
Hello,
In the UI settings, one has to declare users.
When setting-up each agent, one has to declare users.
I am not clear: do we have to declare the same users on both sides (providing they are allowed to monitor the DB) ?
Thanks

**Comment by julmon** [comment]
Hi,

That's right, you have to declare users on both UI and agent. This is required because we need to do users access control on both.
We are working on trying to make it more easy and intuitive.

Regards,
