### ISSUE TITLE
Issue with long PGDATA path

### ISSUE THREAD

**Issue by julmon** [dalibo/temboard#376]
When PGDATA path is quite long, other fields looks to be truncated:
![long-pgdata-issue](https://user-images.githubusercontent.com/920753/41860641-6df4d16a-789f-11e8-8f77-cf6a813382e7.png)

**Comment by pgiraud** [comment]
We have several options to solve this issue:

1 - break long words (here the path is one word)
![capture du 2018-06-26 10-41-08](https://user-images.githubusercontent.com/319774/41900002-ff219c70-792d-11e8-8a7a-80a046f67637.png)

2 - hide overflow and use ellipsis
![capture du 2018-06-26 10-43-53](https://user-images.githubusercontent.com/319774/41900032-0d2e0d80-792e-11e8-95cd-e2cf843004fc.png)

2 bis - show only the relevant part (right side of the path)
![capture du 2018-06-26 10-44-12](https://user-images.githubusercontent.com/319774/41900067-258d6092-792e-11e8-8ace-13fe685e41e5.png)

**Comment by julmon** [comment]
I would say point 2. Is it possible to get the full path through a tooltip if truncated ?
