### ISSUE TITLE
monitoring view: metrics not shown with some predefined time range filters

### ISSUE THREAD

**Issue by mrechte** [dalibo/temboard#387]
Hello,

I have a problem with the monitoring view with some predefined time range filters: This week*, This month*, This year*, Previous*, Last*: they return no metrics.

For example:

This Week metrics
query: https://<server:port>/server/<agent>/<agent_port>/monitoring/data/cpu?start=2018-07-07T22:00:00.000Z&end=2018-07-14T21:59:59.999Z&noerror=1
Returns:
date,user,system,iowait,steal

Whereas Today's metrics
Query: https://<server:port>/server/<agent>/<agent_port>/monitoring/data/cpu?start=2018-07-10T22:00:00.000Z&end=2018-07-11T21:59:59.999Z&noerror=1
Returns:
date,user,system,iowait,steal
2018-07-10 22:00:08+00,1.6,2.8,0.0,0.0
...
2018-07-11 13:08:26+00,1.6,2.5,0.0,0.0

I am using code from git revision:
commit 115769c6e876918e050ca58457b5242016811264
Date:   Fri Jun 29 14:08:47 2018 +0200

Thanks
Marc

**Comment by pgiraud** [comment]
Hi Marc,

What may happen in your case is that you don't have enough data in the monitoring tables on the repository database. In temBoard, in order to be able to display monitoring data in an efficient way, the data is aggregated (for 30m and 6h periods). If there's not enough data on which to do an average there may be no data to send to browser.

I just started temBoard with an empty database, and the same happens.

Can you please confirm that the problem disapear after a while?

**Comment by mrechte** [comment]
Hello Pierre,

The agent has been set up for while (several weeks), and for instance if I run "This week" I get "no data available" on all charts.

Merci.
Marc

**Comment by pgiraud** [comment]
Can you please check if you have data in the table where the metrics are aggregated for zoom level 1 (> 1 day and <= 31 days)?

``` sql                   
SELECT m.*, h.hostname
FROM monitoring.metric_cpu_30m_current AS m
JOIN monitoring.hosts AS h
ON h.host_id = m.host_id
WHERE h.hostname = 'the_instance_s_hostname'
AND datetime between '2018-07-07T22:00:00.000Z' AND '2018-07-14T21:59:59.999Z'
ORDER BY datetime;
```

Can you please also provide the logs from temboard UI? There may be some relevant information there.

**Comment by mrechte** [comment]
```
select count(*) from monitoring.metric_cpu_30m_current;
 count 
-------
     0
(1 ligne)

```
While log shows:
```
 INFO: 200 POST /monitoring/collector (137.129.47.76) 93.22ms
 INFO: 200 POST /monitoring/collector (137.129.47.76) 92.03ms
 INFO: 304 GET /server/bdu1.meteo.fr/3000/monitoring/data/memory?start=2018-07-07T22:00:00.000Z&end=2018-07-14T21:59:59.999Z&noerror=1 (137.129.6.32) 99.87ms
 INFO: 304 GET /server/bdu1.meteo.fr/3000/monitoring/data/loadavg?start=2018-07-07T22:00:00.000Z&end=2018-07-14T21:59:59.999Z&noerror=1 (137.129.6.32) 87.12ms
 INFO: 304 GET /server/bdu1.meteo.fr/3000/monitoring/data/sessions?start=2018-07-07T22:00:00.000Z&end=2018-07-14T21:59:59.999Z&noerror=1 (137.129.6.32) 98.84ms
 INFO: 304 GET /server/bdu1.meteo.fr/3000/monitoring/data/tps?start=2018-07-07T22:00:00.000Z&end=2018-07-14T21:59:59.999Z&noerror=1 (137.129.6.32) 99.59ms
 INFO: 304 GET /server/bdu1.meteo.fr/3000/monitoring/data/fs_usage?start=2018-07-07T22:00:00.000Z&end=2018-07-14T21:59:59.999Z&noerror=1 (137.129.6.32) 102.30ms
 INFO: 304 GET /server/bdu1.meteo.fr/3000/monitoring/data/cpu?start=2018-07-07T22:00:00.000Z&end=2018-07-14T21:59:59.999Z&noerror=1 (137.129.6.32) 88.40ms
```

**Comment by pgiraud** [comment]
I guess that it's the same for the metric_cpu_6h_current table.

Can you please check if there are relevant error entries in the logs (repository postgresql logs) giving details about why the data is not aggregated?
You should be able to find something like `Running SQL function monitoring.aggregate_data` or `Could not aggregate montitoring data`.

**Comment by pgiraud** [comment]
@mrechte any logs to provide? See previous comment. Thanks for your help.

**Comment by mrechte** [comment]
Yes:
```
select count(*) from monitoring.metric_cpu_6h_current;
 count 
-------
     0
(1 ligne)

```
Actually I was logging to the screen, did not have much history, and could not find any relevant error. I just started logging to a file and let you know tomorrow if I can find such message.

Thanks

**Comment by mrechte** [comment]
Pierre,
I have no interesting lines in the log file:
`2018-07-20 12:49:39,648 temboard-agent[2470]: [temboardui] INFO: 200 POST /monitoring/collector (137.129.47.76) 96.89ms`
All lines starts with the same prefix (temboard-agent[2470]: [temboardui]).
I have a few lines with:
`2018-07-19 14:33:04,477 temboard-agent[2470]: [temboardui] ERROR:     raise TemboardUIError(302, "Authentication cookie is missing.")`
Probably due to a browser pointing to the server with expired credential.
I could not find the word "SQL" nor "aggregate" in the log.

**Comment by pgiraud** [comment]
Can you try to turn the logging level to DEBUG? The aggregate_data task should happen every 30 minutes.

**Comment by pgiraud** [comment]
@mrechte Hello, we suspect an issue with the scheduler.

Is it possible for you to upgrade your code to match the latest stable release (2.0b1)? Also please make sure that the scheduler submodule is up-to-date.

```
git submodule sync
git submodule update 
```

**Comment by pgiraud** [comment]
@mrechte Anything new on this topic? Have you tried to do the update as advised?

**Comment by mrechte** [comment]
Hello,
Sorry I missed your former inputs. I just did the pull.
So far no change, but I assume one has to wait for data to accumulate ?
Thanks

**Comment by julmon** [comment]
Hi @mrechte 

Could you please restart the UI, wait few minutes and send us the logs ?

Thanks,

**Comment by mrechte** [comment]
[temboard.log.gz](https://github.com/dalibo/temboard/files/2317284/temboard.log.gz)

Hello,
Please find attached the today's log. Actually the software was updated yesterday (and restarted).
It seems the problem is still present:
```
select count(*) from monitoring.metric_cpu_30m_current;
 count 
-------
     0
(1 ligne)

```
Marc

**Comment by julmon** [comment]
Hi,

Actually, the interesting log part would be right after the restart. Anyway, could you try this:

- stop temboard UI
- remove this file `/tmp/.tm.task_list`. This is the default path, `home` parameter of `temboard.conf` file defines its parent dir. location.
- start temboard UI
- take a look at `temboard.log` file

**Comment by mrechte** [comment]
[temboard.log](https://github.com/dalibo/temboard/files/2318178/temboard.log)

Here it is, but it does not look much exciting !

**Comment by pgiraud** [comment]
After some more work, we finally found that the problem was the same as raised in https://github.com/dalibo/temboard/issues/346. Problem solved with an upgrade of the database using https://temboard.readthedocs.io/en/latest/temboard-upgrade-1.2-2.0/
