### ISSUE TITLE
ERROR: Invalid FQDN: localhost

### ISSUE THREAD

**Issue by daamien** [dalibo/temboard#4]
I'm having trouble with the temboard agent. When I start the agent I get the following error every second. 

```
2016-10-22 09:59:38,364 temboard-agent[25756]: [dashboard_collector] ERROR: Invalid FQDN: localhost
```

I didn't modify the dashboard section in the temboard-agent.conf file... I'm using the default self signed SSL certificates

**Comment by daamien** [comment]
I disabled the dashboard plugin and the agent starts with no errors.

But then when I send the discovery request with `è curl -k https://127.0.0.1:2345/discover``

I get a similar  error :

```
2016-10-22 10:04:54,210 temboard-agent[25799]: [api] INFO: Starting discovery.
2016-10-22 10:04:54,276 temboard-agent[25799]: [api] ERROR: Invalid FQDN: localhost
2016-10-22 10:04:54,277 temboard-agent[25799]: [api] INFO: Discovery failed.
```

**Comment by daamien** [comment]
I've set the ``hostname`` option in temboard-agent.conf like this:

````
hostname = something.somedomain.net
````

And everything works fine. 

We whould either make it work with no defined hostname or write this in the config doc page

**Comment by julmon** [comment]
`hostname`  is used as primary key in `temboard` repository to identify machines. Forcing it as a valid FQDN looks to be the only way to minimize collision risks when dealing with many hosts/machines.

Yes, you can overwrite system value by using parameter `hostname` in `temboard-agent` configuration file.

**Comment by daamien** [comment]
Understood. 

I think we need a clear message about the ``hostname`` and push users to configure it very early during the first steps of the agent configuration. Advanced users can leave the parameter empty but in my cases the systemwide hostname will be ``localhost`` and it will create problems either in short term with the supervision plugin, or in long term with other plugins...

Here's a patch that's tries to drive users into configuring the hostname for the agent.

**Comment by daamien** [comment]
https://github.com/dalibo/temboard/pull/16
