### ISSUE TITLE
ImportError: No module named scheduler

### ISSUE THREAD

**Issue by Laayem** [dalibo/temboard#405]
Hello, 

We would like to try temboad but we have been blocked with an import error from python. 
We have follow the doc (https://temboard.readthedocs.io/en/latest/temboard-install-rpm/) for the installation in an CentOS 7 server with PostGreSQL 10 instance, SELinux on permissive and port 2345 and 8888 open in FirewallD. 

This is the command : 
`
temboard -c /etc/temboard/temboard.conf -p /var/run/temboard/temboard.pid
`
This is the error: 
`
Traceback (most recent call last):
  File "/bin/temboard", line 16, in <module>
    from temboardui.scheduler import taskmanager
ImportError: No module named scheduler
`
If someone have an idea to install temboardui.scheduler, I haven't found anything yet.
Thank you.

**Comment by julmon** [comment]
Hello,

This is probably due to the broken RPM package shipped on PGDG repo.

Could you try to remove temboard package with yum remove and reinstall it with: `sudo yum  --enablerepo=dalibolabs --disablerepo=pgdg10 install temboard`

Regards,

**Comment by Laayem** [comment]
It's working! Thank you for your quick reply.
Now I have to configure agent.
