### ISSUE TITLE
Upgrade 1.2 to 2.0 Problems

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#406]
I am running the temboard upgrade from 1.2 to 2.0 as per the docs, and after the RPM was updated I ran the scripts to upgrade the repository. I got some warnings from the /usr/share/temboard/sql/alerting.sql script:

SET
BEGIN
psql:/usr/share/temboard/sql/alerting.sql:5: NOTICE:  type "check_state_type" does not exist, skipping
DROP TYPE
psql:/usr/share/temboard/sql/alerting.sql:6: NOTICE:  table "state_changes" does not exist, skipping
DROP TABLE
psql:/usr/share/temboard/sql/alerting.sql:7: NOTICE:  table "check_changes" does not exist, skipping
DROP TABLE
psql:/usr/share/temboard/sql/alerting.sql:8: NOTICE:  table "check_states" does not exist, skipping
DROP TABLE
psql:/usr/share/temboard/sql/alerting.sql:9: NOTICE:  table "checks" does not exist, skipping
DROP TABLE
CREATE TYPE

The /usr/share/temboard/sql/upgrade-1.2-2.0.sql script ran with no messages.

When I try to start the temboard service I get an error:

[dgiffin@devpg-temp01 ~]$ sudo systemctl start temboard
Job for temboard.service failed because the control process exited with error code. See "systemctl status temboard.service" and "journalctl -xe" for details.

[dgiffin@devpg-temp01 ~]$ systemctl status temboard.service
● temboard.service - temBoard Web UI
   Loaded: loaded (/usr/lib/systemd/system/temboard.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2018-09-18 06:17:51 CDT; 26s ago
  Process: 23483 ExecStart=/usr/bin/temboard -c /etc/temboard/temboard.conf -d -p /var/run/temboard/temboard.pid (code=exited, status=1/FAILURE)
 Main PID: 31518 (code=exited, status=1/FAILURE)

[dgiffin@devpg-temp01 ~]$ sudo journalctl -xe
Sep 18 06:17:51 devpg-temp01.chi.accertify.net temboard[23483]: ImportError: No module named scheduler
Sep 18 06:17:51 devpg-temp01.chi.accertify.net systemd[1]: temboard.service: control process exited, code=exited status=1
Sep 18 06:17:51 devpg-temp01.chi.accertify.net systemd[1]: Failed to start temBoard Web UI.
-- Subject: Unit temboard.service has failed

Any idea what has gone wrong?

**Comment by julmon** [comment]
FYI, RPM packages for the version 2 have been moved on a new YUM repo, please take a look at this: https://temboard.readthedocs.io/en/latest/temboard-install-rpm/#rhel-centos-7

Once acces to this new YUM repo configured, please see this issue #405 

Regards,

**Comment by dgiffin** [comment]
From our SysOps:

Upon closer inspection it seems temboard do require some extra python modules, namely scheduler (in red below) to be able to start.

– Unit temboard.service has begun starting up.
 Sep 18 08:20:46 devpg-temp01.chi.accertify.net temboard[3684]: Traceback (most recent call last):
 Sep 18 08:20:46 devpg-temp01.chi.accertify.net temboard[3684]: File "/usr/bin/temboard", line 16, in <module>
 Sep 18 08:20:46 devpg-temp01.chi.accertify.net temboard[3684]: from temboardui.scheduler import taskmanager
 Sep 18 08:20:46 devpg-temp01.chi.accertify.net temboard[3684]: ImportError: No module named scheduler
 Sep 18 08:20:46 devpg-temp01.chi.accertify.net systemd[1]: temboard.service: control process exited, code=exited status=1
 Sep 18 08:20:46 devpg-temp01.chi.accertify.net systemd[1]: Failed to start temBoard Web UI.
– Subject: Unit temboard.service has failed

 

Looking at the code in line 16 you see what the problem is:

#!/usr/bin/python
1. coding: utf-8 

import logging.config
 import os
 import signal
 import socket
 import sys

import tornado.ioloop
 import tornado.web
 from tornado import autoreload

from sqlalchemy import create_engine

from temboardui.scheduler import taskmanager <- Line 16
 from temboardui.logger import generate_logging_config
 from temboardui.handlers.base import (
 BaseHandler,
 Error404Handler,
 )
 from temboardui.handlers.user import (
 AgentLoginHandler,
 LoginHandler,
 LoginJsonHandler,
 LogoutHandler,
 )
 from temboardui.handlers.home import (

**Comment by julmon** [comment]
Did you see my previous comment ?

> Once acces to this new YUM repo configured, please see this issue #405

**Comment by dgiffin** [comment]
Yes, that's sorted out the problem - thanks.
