### ISSUE TITLE
Status blank for 2nd PostgreSQL cluster on a host

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#407]
I have a host that is running 2 different PostgreSQL clusters on different ports, and I have 2 temboard-agents running, each connecting to a different database.

In the GUI I can see the Current status is displaying various Ok messages in the Dashboard screen, likewise in the Status screen. However, for the 2nd cluster on the host the Current status section of the Dashboard window is blank as is the Status window.

Is this expected behavior?

**Comment by julmon** [comment]
Hi @dgiffin 

This is a bug, PR #409 should fix it.

Thanks,

**Comment by julmon** [comment]
Maintenance release 2.1 is now available from YUM repos and fixes this issue
