### ISSUE TITLE
temBoard doesn't tell if an instance is stopped

### ISSUE THREAD

**Issue by pgiraud** [dalibo/temboard#418]
Currently, if an instance is stopped, the agent continues to collect data and sends it to the UI. However, the UI doesn't seem to handle this correctly. For example, the dashboard isn't updated. More importantly, the UI should tell the user that the instance is not available.

**Comment by dgiffin** [comment]
+1

**Comment by pgiraud** [comment]
Fixed via https://github.com/dalibo/temboard/pull/415
