### ISSUE TITLE
Bad handling of "Restart PostgreSQL" in the Settings / Configuration tool

### ISSUE THREAD

**Issue by jpargudo** [dalibo/temboard#42]
Hi there,

I use the 3 docker's quickstart thing to test temBoard deeper... when I go to Settings / Configuration tool of the 9.6 instance (port 5435 of the docker's images), and set shared_buffers from 128MB to 96MB, it asks me if I want to restart the PG server to apply changes... When I press OK, it nevers goes back to a normal state, like if the PG never restarts.

But it did the restart, applying the changes, so I have to dismiss, and I see it's applyied.

To me its a bad handling of a monitored PG instance ?

[Here's a video ](http://www.argudo.xyz/bug_restart.mp4) of what I have, to show you this with an example.

**Comment by julmon** [comment]
Hi,

Thank you for this report. This is a known issue, at least for me: restarting postgres using pg_ctl does not work properly, it hangs for a long time. I'm trying to get ride of this.

Regards,

**Comment by blogh** [comment]
Hi, 

I had the same issue on Ubuntu 14. 
I used the "-l <filename>" option of pg_ctl to make it work.

It's a problem I also encountered while playing with repmgr (https://github.com/2ndQuadrant/repmgr/issues/167) and with pg_ctl via ssh. Does is solves your problem ?

Regards,
Benoit

**Comment by julmon** [comment]
Hi,

This commit https://github.com/dalibo/temboard/commit/7c5a6b9583314b36a365191aeb823fb701bc0e71 should fix this issue.

Let me know if not.

Regards,

**Comment by jpargudo** [comment]
Ho,

Tested, seems to work fine! 
Thanks!
