### ISSUE TITLE
Can't see 2.1 in your repo

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#426]
Just checked your repo https://packages.temboard.io/yum/rhel7/

can't see 2.1?

**Comment by julmon** [comment]
RPM packages have been moved on a new yum repo since the release of version 2.0 : https://temboard.readthedocs.io/en/latest/temboard-install-rpm/#rhel-centos-7

**Comment by dgiffin** [comment]
Ah - sorry.
