### ISSUE TITLE
Alerts not clearing

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#443]
Running 2.1

I have a Cache Hit Ratio alert, but the current value is outside the alert levels (warning 90%, critical 80%).

**Comment by dgiffin** [comment]
Image attached.

**Comment by dgiffin** [comment]
Cool - got a rough ETA for that release?

**Comment by pgiraud** [comment]
We are considering backporting this fix in v2 in the next days.

**Comment by pgiraud** [comment]
@dgiffin v2.2 has just been released. Can you please have a try?

**Comment by dgiffin** [comment]
Will do!

**Comment by dgiffin** [comment]
Ran some tests in our sandbox environment, looks good - thanks!
