### ISSUE TITLE
Bad time shift handling on dashboard ?

### ISSUE THREAD

**Issue by julmon** [dalibo/temboard#460]
I'm facing an issue with dashboard charts, please take a look at the screenshot below:
![tbd-dashboard-timeshift](https://user-images.githubusercontent.com/920753/48418323-4fb07180-e755-11e8-9672-05ef6b6ae34c.png)

It seems the current charts values do not correspond to actual values displayed in the top right corners. FYI, the PC running the web browser where this issue occurs is 5 minutes late.

Thanks !

**Comment by pgiraud** [comment]
Looks like we're timezone proof. We're using `time.time()` which is supposed to be timezone independant.
https://github.com/dalibo/temboard-agent/blob/master/temboardagent/plugins/dashboard/metrics.py#L52

I just had a try by changing the timezone of the docker container running my agent, and it works as expected.

Also tried to run my browser on a different timezone. And it works well as well.

![capture du 2018-11-15 16-57-16](https://user-images.githubusercontent.com/319774/48564967-ba99ae00-e8f7-11e8-9fd3-c49977698be6.png)
![capture du 2018-11-15 16-57-34](https://user-images.githubusercontent.com/319774/48564977-be2d3500-e8f7-11e8-819e-e71f9631e0cd.png)
