### ISSUE TITLE
[activity] Stop auto refresh automatically on checkbox selection 

### ISSUE THREAD

**Issue by Rodac** [dalibo/temboard#472]
Could it be possible to stop automatically "auto refresh" when clicking on any session's checkbox (which are disabled by default)  and then enable again after terminating a session ?

**Comment by julmon** [comment]
Thanks for the report. Your proposal makes sense. We'll see with @pgiraud

**Comment by pgiraud** [comment]
Auto refresh is now paused when the user hovers any row in the activity table or when at least one of the checkboxes is checked. See #552
