### ISSUE TITLE
Timezone in supervision

### ISSUE THREAD

**Issue by bersace** [dalibo/temboard#49]
The supervision shows date in UTC.

```
temboard=# select * from metric_cpu_current order by datetime desc limit 4;
        datetime        | host_id | cpu  |                  record
------------------------+---------+------+------------------------------------------
 2017-03-08 14:25:02+00 |       1 | cpu3 | (,00:01:00.318868,2560,1970,55490,110,0)
 2017-03-08 14:25:02+00 |       1 | cpu2 | (,00:01:00.318846,2600,1700,55500,120,0)
```

In the following picture, the last item is one hour behind the system date on top of the screen.

![capture du 2017-03-08 15-29-03](https://cloud.githubusercontent.com/assets/542613/23707813/00cbba64-0414-11e7-8ae3-ec5d43a92ee8.png)

**Comment by pgiraud** [comment]
Fixed in #131. Closing.
