### ISSUE TITLE
https://yum.dalibo.org/labs/CentOS7Server-x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

### ISSUE THREAD

**Issue by seadba** [dalibo/temboard#533]
hello - running yum install temboard  - i get following msg
https://yum.dalibo.org/labs/CentOS7Server-x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

One of the configured repositories failed (Dalibo Labs - CentOS/RHEL 7Server - x86_64),

**Comment by julmon** [comment]
Hello,

On RHEL/CentOS 7 environnements, you should prefer RPM based installation.

Regards,

**Comment by bersace** [comment]
@seadba Can you dump here `/etc/rpm/macro.dist` ?

**Comment by seadba** [comment]
# dist macros.

%rhel 7
%dist .el7
%el7 1
~

**Comment by bersace** [comment]
@seadba thanks. I never saw $releasever evaluating to `7Server` instead of plain `7`. Which variant of CentOS 7 do you run ?

**Comment by seadba** [comment]
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.5 (Maipo)

**Comment by bersace** [comment]
@seadba can you retry ?

**Comment by bersace** [comment]
Closing stale issue. Please reopen if updates.
