### ISSUE TITLE
In V2.3 : auto-configure.sh script in case of the postgres cluster used by repository is not in default port (PGPORT <> 5432 )

### ISSUE THREAD

**Issue by paupi25** [dalibo/temboard#535]
Hy,

  in case of the Postgres cluster port (PGPORT) is not the default value to the Frontend temboard repository,  the auto-configure.sh script must be change in line 57 and  in line 152 when the script connect to cluster to test the connection. 

In detail : 
 - please change line 57 `if ! sudo -Eu ${PGUSER} psql -tc "SELECT 'Postgres connection working.';" ; then` by `if ! sudo -Eu ${PGUSER} psql -p $PGPORT -tc "SELECT 'Postgres connection working.';" ; then`
 - please change line 152  `if ! sudo -u temboard psql -Atc "SELECT 'CONNECTED';" "$dsn" | grep -q 'CONNECTED' ; then` by `if ! sudo -u temboard psql -p $PGPORT -Atc "SELECT 'CONNECTED';" "$dsn" | grep -q 'CONNECTED' ; then`

In this 2 cases we must and the PGPORT at the psql command to connect to the target cluster and to test the connection.

I have successfuly tested it. 

Regards

**Comment by bersace** [comment]
Same, i will upload a new release with the fix.

**Comment by bersace** [comment]
@paupi25 2.3.1 is uploaded on PyPI on other repositories. Can you test it too ?

**Comment by paupi25** [comment]
Ok I test by reinstalling temboard by PyPi tools
temboard vesion : 2.3.1

And all work fine with the use of  datbase in port 5433. Command I used : 
 - export PGPORT=5433 ; /usr/local/share/temboard/auto_configure.sh

Good Job.

Best regards

David Paupe

----- Mail d'origine -----
De: Étienne BERSAC <notifications@github.com>
À: dalibo/temboard <temboard@noreply.github.com>
Cc: paupi25 <david.paupe@free.fr>, Mention <mention@noreply.github.com>
Envoyé: Fri, 18 Jan 2019 15:08:21 +0100 (CET)
Objet: Re: [dalibo/temboard] In V2.3 : auto-configure.sh script in case of the postgres cluster used by repository is not in default port (PGPORT <> 5432 ) (#535)

@paupi25 2.3.1 is uploaded on PyPI on other repositories. Can you test it too ?—
