### ISSUE TITLE
No metrics

### ISSUE THREAD

**Issue by debnet** [dalibo/temboard#541]
Hello,

I followed the documentation in installing temboard for my local database instance, everything seems to works fine except metrics always empty ("No data available") whereas the home page Load average & TPS charts are correctly updated.

Does I do anything wrong?

![image](https://user-images.githubusercontent.com/634832/51612564-ff5a4a80-1f21-11e9-923b-c4d24b637403.png)

![image](https://user-images.githubusercontent.com/634832/51612586-0e40fd00-1f22-11e9-8a4b-20b6f9afb981.png)

**Comment by debnet** [comment]
By the way, I don't succeed to gather alerts too, the screen is empty.

**Comment by pgiraud** [comment]
It may take some times (5 minutes at least) before the first monitoring data is available. Please make sure that you don't have anything now.
If not, can you please have a look at the logs (both in the UI and the agent) to see if there's any relevant information.

**Comment by debnet** [comment]
It works, I got issues with domains. Almost everything in temboard rely on the result given by `hostname -f` but it's not easy when you have multiple domains.
