### ISSUE TITLE
deleting old instances

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard#606]
temboard v2.2

when we remove instances from the gui tool/webpage, the related data is not removed from the metadata tables in the temboard schema.

**Comment by dgiffin** [comment]
Any update on this?

**Comment by bsislow** [comment]
any update? this is still happening with version 3.

**Comment by bsislow** [comment]
bump... any update on this? we're missing some basic functionality here.

**Comment by pgiraud** [comment]
@bsislow Just to make sure we are on the same track, are you talking about the data collected for the metrics by the monitoring plugin?

**Comment by bsislow** [comment]
not sure about the metrics data, but the _instance_ is not removed in the monitoring.instances or monitoring.hosts tables - at the least. there are probably child dependencies.

here is where we delete the instance on the Instances page; the trash bin located in the red circle:

![image](https://user-images.githubusercontent.com/30243584/58957133-9b645000-8765-11e9-930b-c2b8f53e8389.png)

does this make sense?
