### ISSUE TITLE
cannot edit or delete instance when changing "show X entries" to nondefault

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard#607]
temboard v2.2

when going to settings->instances
then modifying "show X rows" from 10 to any other number, the edit and trash can icons next to each instance stop working.

**Comment by pgiraud** [comment]
Indeed, I'm able to reproduce. Thanks for the report.

**Comment by pgiraud** [comment]
As a workaround for now, you can reload the page once you have changed the bumber of rows to show.

**Comment by bsislow** [comment]
yes this is the workaround we use for now. thank you for looking into this.

**Comment by pgiraud** [comment]
Fixed in #610
