### ISSUE TITLE
Exclude virtual partition (fs) in monitoring file system usage

### ISSUE THREAD

**Issue by julmon** [dalibo/temboard#612]

**Comment by Kerthmash** [comment]
This has been open for quite some time. has there been any movement on excluding virtual volumes from temboard, I too am seeing alerts on all servers due to the mounted snap volumes.

**Comment by bersace** [comment]
Hi @Kerthmash, can you share a mount line for a snap volume ? 7.9 has improvements on this matter. We can tweak this further.

**Comment by Kerthmash** [comment]
certainly,  See the attached screenshot:
![volumes](https://user-images.githubusercontent.com/45573603/148771783-e877ba7f-33b9-4a4a-a986-1e8bf822caf9.png)

**Comment by bersace** [comment]
Ok, I suggest that temBoard ignores loopback devices.

**Comment by Kerthmash** [comment]
Just to confirm, are you saying that this is possible in version 7.9? or that it will be a future enhancement?

**Comment by bersace** [comment]
@Kerthmash 7.9 ignores network mount point and some kinds of filesystem like overlay. It does not ignore loopback device. I suggest to ignore all loopback devices in next release. What do you think of this ?

**Comment by Kerthmash** [comment]
I think that will be a welcome addition.  the way it is currently, the loopback devices are constantly in an alarm state, as the monitor thinks the drives are full.

**Comment by bersace** [comment]
@Kerthmash see https://github.com/dalibo/temboard-agent/pull/552

**Comment by bersace** [comment]
Will be in next release. Thanks @Kerthmash for the feedback.
