### ISSUE TITLE
temboard-agent communication

### ISSUE THREAD

**Issue by dagravito** [dalibo/temboard#626]
Hello
I've got some temboard agents to monitor behind firewall and I don't know exactly which ports do I have to open.
The port defined in the conf file :

[temboard]
port = 2345

Then the port for monitoring :

[monitoring]
collector_url = https://fqdn_hostname:8888/monitoring/collector

Do I need to open other ports ?
Can you help me ?
Thanks for your help.

**Comment by julmon** [comment]
Hello,

By default, temboard agents listen on port 2345 TCP, temboard UI listen on 8888 TCP.

About data flows, temboard UI communicate with agents (on 2345/TCP) using HTTPS. Agents send monitoring data to the UI (on 8888/TCP) using HTTPS.

If your FW is between the UI and the agents like this:
```
temboard UI (8888/TCP) <-----> FW <-----> temboard agents (2345/TCP)
```

You should allow incoming traffic to 2345/TCP and outcoming to 8888/TCP.

Hope this is clear.

**Comment by dagravito** [comment]
Hello Julien,
Understood.
This is working well !
Thanks
