### ISSUE TITLE
Internal Server Error on instance registering

### ISSUE THREAD

**Issue by ced75** [dalibo/temboard#629]
Hi,

I'm trying to install temBoard v3 on a monitoring server, install temBoard agent on a PostgreSQL server, and register it to the monitoring server.

On the monitoring server (Debian stretch), I successfully installed temBoard, with following steps:
```
sudo bash -c 'echo deb http://apt.dalibo.org/labs $(lsb_release -cs)-dalibo main > /etc/apt/sources.list.d/dalibo-labs.list'
wget --quiet -O - https://apt.dalibo.org/labs/debian-dalibo.asc | \
  sudo apt-key add -
sudo apt update
sudo apt install temboard
temboard --version
sudo systemctl status temboard.service
sudo systemctl start temboard
```

The temboard service started successfully.

Then, I connected to the server via a web browser with the following url : https://my-monitor-server:8888

It worked fine and I could changed the password of admin user (xxxxx for example).

On a postgresql other server (also under debian stretch, with PostgreSQL v10 on it), I installed the temboard agent with the following steps:
```
sudo  bash -c 'echo deb http://apt.dalibo.org/labs $(lsb_release -cs)-dalibo main > /etc/apt/sources.list.d/dalibo-labs.list'
wget --quiet -O - https://apt.dalibo.org/labs/debian-dalibo.asc | \
  sudo apt-key add -

sudo apt update

sudo apt install temboard-agent
temboard-agent --version

sudo /usr/share/temboard-agent/auto_configure.sh https://my-monitor-server:8888
```
It also seemed to work fine, since it produced the expected informations:

> Configuring temboard-agent in /etc/temboard-agent/10/main/temboard-agent.conf .
> Configuring temboard-agent to run on port 2345.
> For registration, use secret key blablablablabla .

Then, I added an agent-user like that:
```
sudo -u postgres temboard-agent-adduser -c /etc/temboard-agent/10/main/temboard-agent.conf
# Username : postgres
# password : yyyyy
```
I started the agent service on my PostgreSQL server with:
`sudo systemctl start temboard-agent@10-main.service`

Then, I tried to add the agent to the monitoring server, launching this command on the PostgreSQL server:
```
sudo -u postgres temboard-agent-register -c /etc/temboard-agent/10/main/temboard-agent.conf --host $(hostname --fqdn) --port 2345 --groups default https://my-monitor-server:8888
# Username : admin
# password : xxxxx
```
This produces the following error message: 

> Registering instance/agent to https://my-monitor-server:8888 ...
> CRITI: HTTP Error 500: Internal Server Error

Logs in /var/log/temboard_agent/10-main.log are:

> 2019-05-06 13:37:15,277 temboardagent[7032]: [probes] INFO: Loaded probe: tblspc_size
> 2019-05-06 13:37:15,277 temboardagent[7032]: [probes] INFO: Loaded probe: temp_files_size_delta
> 2019-05-06 13:37:15,277 temboardagent[7032]: [probes] INFO: Loaded probe: sessions
> 2019-05-06 13:37:15,277 temboardagent[7032]: [probes] INFO: Loaded probe: xacts
> 2019-05-06 13:37:15,277 temboardagent[7032]: [probes] INFO: Loaded probe: heap_bloat
> 2019-05-06 13:37:15,277 temboardagent[7032]: [probes] INFO: Loaded probe: loadavg
> 2019-05-06 13:37:15,277 temboardagent[7032]: [probes] INFO: Loaded probe: filesystems_size
> 2019-05-06 13:37:15,278 temboardagent[7032]: [probes] INFO: Loaded probe: cpu
> 2019-05-06 13:37:15,278 temboardagent[7032]: [probes] INFO: Loaded probe: bgwriter
> 2019-05-06 13:37:15,278 temboardagent[7032]: [probes] INFO: Loaded probe: memory

And in the monitoring server, there no files in /var/log/temboard.

Did I miss something?

Thanks in advance for your help.

**Comment by julmon** [comment]
Hello,

Did you find something in `/var/log/messages` file on the monitoring server ?
Could you copy/paste here the logging part of your `temboard.conf` file ?

Thanks,

**Comment by ced75** [comment]
Thanks for your answer.
There is nothing special in /var/log/messages file on monitoring server.

Here is the logging part of `temboard.conf` file:
```
[logging]
method = stderr
level = INFO

```

**Comment by julmon** [comment]
You should see temboard logs with `sudo journalctl -u temboard`

**Comment by ced75** [comment]
Yes.
The error message said that there were already an instance entry with that name.
I deleted the instance and added the agent again. It works!

Thanks for your help.
Kind regards

**Comment by ced75** [comment]
There still are things that do not work. For example, status screen remains empty.
Here are the log entries:
oct. 21 10:40:19 inv-monitor env[581]: Unhandled Error:
oct. 21 10:40:19 inv-monitor env[581]: Traceback (most recent call last):
oct. 21 10:40:19 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 227, in error_middleware
oct. 21 10:40:19 inv-monitor env[581]:     return func(request, *args)
oct. 21 10:40:19 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 408, in user_instance_middleware
oct. 21 10:40:19 inv-monitor env[581]:     return func(request, address, port, *args)
oct. 21 10:40:19 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 267, in instance_middleware
oct. 21 10:40:19 inv-monitor env[581]:     return callable_(request, *args)
oct. 21 10:40:19 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 431, in user_middleware
oct. 21 10:40:19 inv-monitor env[581]:     return func(request, *args)
oct. 21 10:40:19 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/alerting.py", line 91, in 
oct. 21 10:40:19 inv-monitor env[581]:     host_id, instance_id = get_request_ids(request)
oct. 21 10:40:19 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/tools.py", line 93, in get_request_
oct. 21 10:40:19 inv-monitor env[581]:     host_id = get_host_id(request.db_session, request.instance.hostname)
oct. 21 10:40:19 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/tools.py", line 75, in get_host_id
oct. 21 10:40:19 inv-monitor env[581]:     "Could not find registered host with hostname=%s" % hostname
oct. 21 10:40:19 inv-monitor env[581]: Exception: Could not find registered host with hostname=new-del1207w108.ign.fr
oct. 21 10:40:19 inv-monitor env[581]: Request failed: 500 Could not find registered host with hostname=new-del1207w108.ign.fr.
oct. 21 10:40:19 inv-monitor env[581]: Unhandled Error:
oct. 21 10:40:19 inv-monitor env[581]: Traceback (most recent call last):
oct. 21 10:40:19 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 227, in error_middleware
oct. 21 10:40:19 inv-monitor env[581]:     return func(request, *args)
oct. 21 10:40:19 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 408, in user_instance_middleware
oct. 21 10:40:19 inv-monitor env[581]:     return func(request, address, port, *args)
oct. 21 10:40:19 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 267, in instance_middleware
oct. 21 10:40:19 inv-monitor env[581]:     return callable_(request, *args)
oct. 21 10:40:19 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 431, in user_middleware
oct. 21 10:40:19 inv-monitor env[581]:     return func(request, *args)
oct. 21 10:40:19 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/alerting.py", line 48, in 
oct. 21 10:40:19 inv-monitor env[581]:     host_id, instance_id = get_request_ids(request)
oct. 21 10:40:19 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/tools.py", line 93, in get_request_
oct. 21 10:40:19 inv-monitor env[581]:     host_id = get_host_id(request.db_session, request.instance.hostname)
oct. 21 10:40:19 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/tools.py", line 75, in get_host_id
oct. 21 10:40:19 inv-monitor env[581]:     "Could not find registered host with hostname=%s" % hostname
oct. 21 10:40:19 inv-monitor env[581]: Exception: Could not find registered host with hostname=new-del1207w108.ign.fr
oct. 21 10:40:19 inv-monitor env[581]: 500 GET /server/new-del1207w108.ign.fr/2345/alerting/checks.json (172.27.3.45) 41.90ms
oct. 21 10:40:19 inv-monitor env[581]: Request failed: 500 Could not find registered host with hostname=new-del1207w108.ign.fr.
oct. 21 10:40:19 inv-monitor env[581]: 500 GET /server/new-del1207w108.ign.fr/2345/alerting/alerts.json (172.27.3.45) 25.98ms

**Comment by bersace** [comment]
Hi, is this still relevant ?

**Comment by ced75** [comment]
Hi,

No. Last versions of temBoard solved the problem.
I close the issue.
