### ISSUE TITLE
Metrics Show as UNDEF

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#636]
Sometimes we see a metric in the dashboard marked as UNDEF - it seems to occur in more than one database and with different metrics - after some time it seems to clear and metric shows as normal.

Any idea why this happens and how we can resolve it?

Thanks.

![image](https://user-images.githubusercontent.com/4103061/58149646-adb99680-7c5b-11e9-9112-88c284d1b43d.png)

**Comment by julmon** [comment]
Hello,

UNDEF status is set by default when temboard didn't get yet any data to check.
