### ISSUE TITLE
environement setup 

### ISSUE THREAD

**Issue by pmpetit** [dalibo/temboard#640]
Hello,
"Assuming that temboard-agent code is cloned along with temboard, create a docker-compose.override.yaml file with the following content:"
means : 
which folder structure should i have ? : 
~/gitHome/temboard
~/gitHome/temboard-agent

or 

~/gitHome/temboard
~/gitHome/temboard/temboard-agent

or 
~/gitHome/temboard + ~/gitHome/temboard-agent is the same folder

thanks

**Comment by pgiraud** [comment]
This is meant to be understood as if `temboard` and `temboard-agent` are sibblings in the same folder.
The path `../temboard-agent` in the `volumes` section of your `docker-compose.override.yml` file should point to the directory where the agent code has been cloned.
Does it make sense? Sorry if the documentation is not very clear.

**Comment by pmpetit** [comment]
i have cloned temboard and temboard-agent in 2 directories 

~/gitHome/temboard
~/gitHome/temboard-agent

start temboard using : 
![image](https://user-images.githubusercontent.com/4059185/59275986-b818f000-8c5d-11e9-9d09-8b8c1068edab.png)

everything is ok on //127.0.0.1:8888

but when i start teh agent :  

   ~/gitHome/temboard/temboard-agent    master   docker-compose up                                                                                                                                                ✔  15:26:28  🐳 
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating temboardagent_repository_1 ... 
Creating temboardagent_instance_1 ... 
Creating temboardagent_repository_1
Creating temboardagent_repository_1 ... done
Creating temboardagent_agent_1 ... 
Creating temboardagent_ui_1 ... 
Creating temboardagent_ui_1
Creating temboardagent_ui_1 ... error

ERROR: for temboardagent_ui_1  Cannot start service ui: driver failed programming external connectivity on endpoint temboardagent_ui_1 (4deea17ee5d509d3e7f005cfff4b9b65c52c270c00fafa2fb095dadff2c8d39d): Error starting userland proxy: listeCreating temboardagent_agent_1 ... done

ERROR: for ui  Cannot start service ui: driver failed programming external connectivity on endpoint temboardagent_ui_1 (4deea17ee5d509d3e7f005cfff4b9b65c52c270c00fafa2fb095dadff2c8d39d): Error starting userland proxy: listen tcp 0.0.0.0:8888: bind: address already in use
ERROR: Encountered errors while bringing up the project.
    ~/gitHome/temboard/temboard-agent    master  

**Comment by pmpetit** [comment]
sorry about that, i am just discovering hwo to contribute....

**Comment by pgiraud** [comment]
The `docker-compose up` command should be run in the temboard directory. Actually it's just the same command as mentioned in the previous section. You have to stop it and run it again.
Because you have an "override" file, the compose command will behave a bit differently and you will be able to run the agent using the cloned code instead of the docker image.
The documentation may need to be rewritten.

**Comment by pmpetit** [comment]
ok, thanks.
I will upgrade it in the next pr

**Comment by pmpetit** [comment]
i have an error starting the agent in debug mode : 

    ~/gitHome/temboard/temboard    master  2  docker-compose exec agent bash  
pip install -e /usr/local/src/temboard-agent/
ERROR: /usr/local/src/temboard-agent/ should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+

**Comment by pgiraud** [comment]
What does the following command show when run in the agent container?

```
ls -l /usr/local/src/temboard-agent/
```

**Comment by pgiraud** [comment]
I suspect that the volumes are not correctly created. Please ensure that the `docker-compose.override.yml` has the correct name and is in the `temboard` folder (not in the agent).

**Comment by pmpetit** [comment]
That was the problem (it was not in the correct folder)
