### ISSUE TITLE
"stretching" rendering issue with Chrome browser

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard#652]
see the video attachment which shows a desktop recording of a new rendering issue with an instance home page.

i am using Chrome version:
Version 75.0.3770.100 (Official Build) (64-bit)

[tb_render_issue.zip](https://github.com/dalibo/temboard/files/3355401/tb_render_issue.zip)

**Comment by dgiffin** [comment]
For info it displays fine in Internet Explorer v11.829.17134.0

**Comment by pgiraud** [comment]
@bsislow This is a known issue and it has already been fixed. See #644.
This fix is available in the 4.0b2 release.

**Comment by pgiraud** [comment]
@dgiffin Can you please open a new issue with a screenshot for the IE display problems?

**Comment by bsislow** [comment]
@pgiraud do you know when 4 will be officially released as we do not want to use a beta version in production?

thanks for your help.

**Comment by pgiraud** [comment]
@bsislow this is scheduled this friday.
