### ISSUE TITLE
temboard home page not displaying in Internet Explorer

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#653]
In Internet Explorer v11.829.17134.0, the temboard home page (IP:8888/home) doesn't display properly, although the database home pages do.
![temboard IE dashboard](https://user-images.githubusercontent.com/4103061/61027301-ba31b400-a3ad-11e9-8e9f-7fff6541273c.png)
![temboard IE homepage](https://user-images.githubusercontent.com/4103061/61027302-ba31b400-a3ad-11e9-9dc2-d7ac5e523817.png)

**Comment by pgiraud** [comment]
Can you please tell us which version of temBoard you are running?
Can you also tell if you get any javascript error in the browser console?

**Comment by dgiffin** [comment]
rpm -q temboard
temboard-3.0-1.el7.noarch

There are messages in the browser console:

![temboard IE console](https://user-images.githubusercontent.com/4103061/61110170-896d7f80-a47e-11e9-9004-a5ba51969cea.png)

**Comment by bersace** [comment]
Closing stale issue. Please reopen with updates from latest release.
