### ISSUE TITLE
temboard-agent service start fails on Debian Jessie

### ISSUE THREAD

**Issue by ced75** [dalibo/temboard#656]
Hi,

I have installed the last 4.0b1 temboard-agent on several Postgres servers without any problem, except on one server.
This server is the only one in Debian Jessie (the others have a Debian Stretch distribution).
The Postgres version on this server is 10.

Everything seems to be all right with the installation, up to the temboard-agent service start, which fails.

Here are the informations given by the systemctl status:

● temboard-agent@10-main.service - PostgreSQL Remote Control Agent 10/main
   Loaded: loaded (/usr/lib/systemd/system/temboard-agent@.service; enabled)
   Active: failed (Result: exit-code) since ven. 2019-07-19 13:50:30 CEST; 23min ago
  Process: 23416 ExecStart=/usr/bin/env SYSTEMD=1 temboard-agent -c /etc/temboard-agent/%I/temboard-agent.conf (code=exited, status=1/FAILURE)
 Main PID: 23416 (code=exited, status=1/FAILURE)

juil. 19 13:50:30 inv-prod env[23416]:   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2401, in requires
juil. 19 13:50:30 inv-prod env[23416]:     dm = self._dep_map
juil. 19 13:50:30 inv-prod env[23416]:   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2597, in _dep_map
juil. 19 13:50:30 inv-prod env[23416]:     self.__dep_map = self._compute_dependencies()
juil. 19 13:50:30 inv-prod env[23416]:   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2614, in _compute_dependencies
juil. 19 13:50:30 inv-prod env[23416]:     from _markerlib import compile as compile_marker
juil. 19 13:50:30 inv-prod env[23416]: ImportError: No module named _markerlib
juil. 19 13:50:30 inv-prod env[23416]: Failed to load monitoring.
juil. 19 13:50:30 inv-prod systemd[1]: temboard-agent@10-main.service: main process exited, code=exited, status=1/FAILURE
juil. 19 13:50:30 inv-prod systemd[1]: Unit temboard-agent@10-main.service entered failed state.

Any idea of what could be wrong?

Thanks in advance for your help.
Regards.

**Comment by julmon** [comment]
Could you try to upgrade `setuptools` python module ?

**Comment by ced75** [comment]
Sorry, I don't know Python very well.
How can I upgrade this module?

**Comment by julmon** [comment]
With `pip` :
`$ sudo pip install --upgrade setuptools`

But not sure this will work.

You should also take a look at this https://stackoverflow.com/questions/35780537/error-no-module-named-markerlib-when-installing-some-packages-on-virtualenv

**Comment by ced75** [comment]
I just installed the package python-setuptools with apt and it worked.
The service has started and is now active.

Thanks for your help.
