### ISSUE TITLE
Major Upgrade Problem, Now Unusable

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#657]
I have run an upgrade from v3 to v4 as per the docs, with the exception that our SysOps updated the temboard RPM before I had a chance to shutdown the service- I'm not sure that should be causing this problem though.....

I shutdown the temboard service (but the various temboard-agent processes on the hosts being monitored were NOT shutdown, it isn't mentioned in the documentation as being required)

I ran the upgrade script:
psql -U postgres -f /usr/share/temboard/sql/upgrade-3.0-4.0.sql temboard

but I received an error:
```
psql:/usr/share/temboard/sql/upgrade-monitoring-purge-instances.sql:128: NOTICE:  DROPING AND CREATING CONSTRAINT check_changes_check_id_fkey
DO
psql:/usr/share/temboard/sql/upgrade-monitoring-purge-instances.sql:146: NOTICE:  Droping data for instance 2
psql:/usr/share/temboard/sql/upgrade-monitoring-purge-instances.sql:146: NOTICE:  Droping data for instance 21
psql:/usr/share/temboard/sql/upgrade-monitoring-purge-instances.sql:146: ERROR:  update or delete on table "hosts" violates foreign key constraint "instances_host_id_fkey" on table "instances"
DETAIL:  Key (host_id)=(19) is still referenced from table "instances".
CONTEXT:  SQL statement "DELETE FROM hosts WHERE host_id = 19"
PL/pgSQL function inline_code_block line 13 at EXECUTE
psql:/usr/share/temboard/sql/upgrade-monitoring-purge-instances.sql:1018: ERROR:  current transaction is aborted, commands ignored until end of transaction block
ROLLBACK
psql:/usr/share/temboard/sql/upgrade-3.0-4.0.sql:94: WARNING:  there is no transaction in progress
COMMIT
```

Which I didn't see when I upgraded out test system.

I restarted the temboard service, but an unable to login via the GUI any more - logfiles are attached.
[temboard-upgrade-log.txt](https://github.com/dalibo/temboard/files/3416965/temboard-upgrade-log.txt)
[temboard.log.gz](https://github.com/dalibo/temboard/files/3416966/temboard.log.gz)

**Comment by pgiraud** [comment]
Hi @dgiffin
Thanks for the report and sorry for the inconvenience.
The problem is identified. I'll come back with a workaround as soon as possible.

**Comment by pgiraud** [comment]
@dgiffin in the general log we can see that the agents for dbpg11 and dbpg12 are failing to send data to the collector. Were the instances previously removed in the UI even if their agent are still running?

**Comment by dgiffin** [comment]
It's possible - I can't check the temboard GUI but I can see both of those hosts have a PostgreSQL instance and a temboard-agent running.

**Comment by pgiraud** [comment]
@dgiffin Could you please download the following SQL files somewhere on the machine and run the  `upgrade-3.0-4.0.sql` using psql?

https://raw.githubusercontent.com/pgiraud/temboard/purge_monitoring/share/sql/upgrade-monitoring-purge-instances.sql
https://raw.githubusercontent.com/pgiraud/temboard/purge_monitoring/share/sql/upgrade-3.0-4.0.sql

**Comment by pgiraud** [comment]
Please don't forget to do a backup of your temboard UI database before!

**Comment by dgiffin** [comment]
I took a backup :-) It's 41Gb though, so would really not have to go back to it!

Where do I need to put those 2 files in order for them to get picked up by the upgrade script?

**Comment by dgiffin** [comment]
The script seems to have completed with no errors (log attached).
[upgrade-3.0-4.0.txt](https://github.com/dalibo/temboard/files/3417596/upgrade-3.0-4.0.txt)

**Comment by dgiffin** [comment]
Do I restart the temboard service now or are there further steps I need to take?

**Comment by pgiraud** [comment]
You should be able to restart temboard and log in.

**Comment by dgiffin** [comment]
Yup, we're back up and running, thanks SO much for your quick response!

I didn't get the same errors upgrading our test system, can I assume that I do NOT have to run the same "fixit" there? The test GUI seesm to be working fine.

**Comment by pgiraud** [comment]
If the upgrade did run well on your testing environnement, this means that the upgrading script didn't fail because you don't have several instances running on the same host.
Indeed, you don't have to run the fix there.
