### ISSUE TITLE
temBoard v4 notifications come from empty email address

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard#662]
we just upgraded to temboard version 4 and notifications come from an empty email address. they arrive at the correct email address that we defined but that doesn't show up either.

how can we change the sender email address? i don't see how to do this anywhere in the documentation. thanks.

![image](https://user-images.githubusercontent.com/30243584/61666846-1b0a9780-ac9e-11e9-9243-9db171f7ea5b.png)

**Comment by pgiraud** [comment]
@bsislow have you tried to set the `smtp_from_addr` variable in your config?
https://github.com/dalibo/temboard/blob/master/share/temboard.conf#L54

**Comment by bsislow** [comment]
do we have to bounce temboard server after adding this?

**Comment by bsislow** [comment]
this worked, thank you.

is there an easier way to find the temboard conf file you posted here? i had no idea this existed...

https://github.com/dalibo/temboard/blob/master/share/temboard.conf#L54

it's not in the documentation.
