### ISSUE TITLE
Unable to start temboard

### ISSUE THREAD

**Issue by seuf** [dalibo/temboard#664]
When running temboard in kubernetes I have the following error :
```
Generating temboard.conf
wait-for-it: waiting 15 seconds for postgresql-temboard.temboard.svc:5432
wait-for-it: postgresql-temboard.temboard.svc:5432 is available after 0 seconds
Initialized role temboard and database temboard.
+ exec temboard
ERROR: Invalid temboard_port from environ: invalid literal for int() with base 10: 'tcp://10.107.29.224:8888'...
CRITI: Failed to load configuration.
```

I have set the following environment variables :
```
  - name: PGHOST
    value: postgresql-temboard.temboard.svc
  - name: PGUSER
    value: temboard
  - name: PGPASSWORD
    value: password
  - name: PGDATABASE
    value: temboard
  - name: TEMBOARD_SSL_CERT
    value: /etc/temboard/ssl/application.crt
  - name: TEMBOARD_SSL_KEY
    value: /etc/temboard/ssl/application.key
  - name: TEMBOARD_SSL_CA
    value: /etc/temboard/ssl/ca.crt
 - name: TEMBOARD_COOKIE_SECRET
    value: SomethingRandom
```

What is the `temboard_port` environment variable ? I've looked in the source code and didn't found any reference to this.
Is it a Tornado issue ?

Any idea ?

**Comment by julmon** [comment]
Hello,

This is not an environment variable, temboard `port` is configured in `temboard.conf` file, usually located in `/etc/temboard` folder.
This parameter must be an integer because it configures the TCP port on which temboard server is listening.

**Comment by seuf** [comment]
Yes. I have configured `port = 8888` in /etc/temboard/temboard.conf
I don't know why it's set to `tcp://10.107.29.224:8888`

**Comment by seuf** [comment]
Found it !
Kubernetes automatically export environment variable for earch service ports.
When overriding the entrypoint to show ̀env` variables, I see that a `TEMBOARD_PORT` variable was exported. I've just overrided it with `8888` and it finally started !
