### ISSUE TITLE
Custom fields (Contact/Costcenter) per PostgreSQL instance

### ISSUE THREAD

**Issue by wsescu** [dalibo/temboard#667]
Hello temBoard team

it would be great if it would be possible to add some custom fields to the PostgreSQL instances.

I am thinking about fields like:

Contact
Costcenter

Maybe some more, but these ones would be the most important ones.

Cheers
William

**Comment by pgiraud** [comment]
Would a generic "comment" field do the job?

**Comment by wsescu** [comment]
Hello @pgiraud 
yes, from my point of view, a generic comment field would do the job perfectly.
Cheers
William
