### ISSUE TITLE
Show temboard server version in the web UI

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/temboard#672]
The teamBoard version is not available from the UI, you have to do `temboard --version`.

It could be shown for example in an "About" box, in the Settings (with other informations like links to the repo, the doc...)

**Comment by Krysztophe** [comment]
In the same spirit, and showing the temboard-agent version in the instances list would be a good idea, too.

**Comment by bersace** [comment]
Done. To be released soon.

**Comment by Krysztophe** [comment]
thanks !
