### ISSUE TITLE
Feature Request: Flap Detection / Notification Retention

### ISSUE THREAD

**Issue by daamien** [dalibo/temboard#675]
Hi !

Here's a feature request from a Temboard user. 

Sometimes an alarm threshold is set a the right level but the state of the service is frequently going over and under that threshold. A classic example is when network issues are triggering a series of WARNING and RECOVERY state changes on a very short period. If a notification is sent for each change of state, this can lead to a high amount of notifications that would flood the end user and generate a lot of noise. 

There are different way to detection this flapping behaviour. One could add a retention period using the following logic :

> If the retention period is set to "2 minutes", alarm notifications are sent 2 minutes after the first 
> state change and only if the state remained above the threshold during 2 minutes. 
 
FTR, Nagios has more sophisticated approach: 

https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/flapping.html

**Comment by damienreyre** [comment]
Hi, 
Any news about this feature for temBoard ??
Cheers,

**Comment by missmoiselle** [comment]
Hi,
We've just decided what will be included in the next temBoard release (planned before summer) and it will not be part of it. 
However, as the request is relevant we keep it in mind for future versions. 
Tks again,

**Comment by daamien** [comment]
We closing this. The monitoring feature will probably receive a large oevrhaul in the forthcoming coming versions and flap detection is no longer in our scope.
