### ISSUE TITLE
Support for Monitoring of PostgreSQL 12.x Instances

### ISSUE THREAD

**Issue by wsescu** [dalibo/temboard#685]
Hello 

does temBoard support monitoring of PostgreSQL 12.x instances? 

Cheers
William

**Comment by bsislow** [comment]
We have several 12.x targets successfully implemented in temboard 4.0.

**Comment by pgiraud** [comment]
@wsescu sorry for the late answer.
For PG12 support, you need to run a rather recent version of temboard agent. At least 4.2 but I would recommend 5.1.
Monitoring and maintenance plugins should work.
However, we've been told about an issue with the configuration plugin recently. It has been fixed.
We intend to release a new version with the full support for PG12 and some other stuff soon.
