### ISSUE TITLE
Statements statistics plugin

### ISSUE THREAD

**Issue by julmon** [dalibo/temboard#690]
# Abstract

PostgreSQL provides for a long time a well known extension aiming to aggregate statistics about executed statements: [pg_stat_statements](https://www.postgresql.org/docs/current/pgstatstatements.html)
This extension is really useful when we want to have a closer look to SQL statements run on the databases.

On temboard side, we want:
- statistics must be reseted (with `pg_stat_statements_reset()`) right after the data have been read. That's why we call it a snapshot.
- snapshots are pulled from temboard UI
-  to history the snapshots taken from `pg_stat_statements` view
- snapshots should be taken every X minutes
- to keep MAX 30 days of snapshot history

## Plugin name

`statements`

# Agent

temboard agent should provide a new API to expose data from `pg_stat_statements` view and reset statistics. All the  [columns](https://www.postgresql.org/docs/current/pgstatstatements.html#PGSTATSTATEMENTS-COLUMNS) of the view should be exposed.

## Configuration

The agent needs to know which database hosts `pg_stat_statements` view, ie, where the extension has been created with `CREATE EXTENSION`. Default database could be `postgres`.

```ini
[statements]
dbname=postgres
```

## Get a snapshot

```
GET /statements?key=<secretkey>
```
| Parameter  | Desc.                 |
|----------------|-----------------------|
| `secretkey` | Agent key          | 

### Data

```json
 {
   "snapshot_datetime": "2020-03-17 17:31:25.0929+01",
   "data": [
     {
       "username": "postgres",
       "dbname ": "bench",
       "queryid": 125206108,
       "query": "SELECT pg_sleep($1)",
       "calls": 1,
       "total_time": 1001.583008,
       "min_time": 1001.583008,
       "max_time": 1001.583008,
       "mean_time": 1001.583008,
       "stddev_time": 0,
       "rows": 1,
       "shared_blks_hit": 0,
       "shared_blks_read": 0,
       "shared_blks_dirtied": 0,
       "shared_blks_written": 0,
       "local_blks_hit": 0,
       "local_blks_read": 0,
       "local_blks_dirtied": 0,
       "local_blks_written": 0,
       "temp_blks_read ": 0,
       "temp_blks_written": 0,
       "blk_read_time": 0,
       "blk_write_time": 0
     },
...
   ]
}
```

### Errors

| HTTP Code |  Error                                                                      |
|-----------------|-------------------------------------------------------------------|
| 404              | pg_stat_statements not enabled on the database |

# Server

`statements` plugin implementation on server (UI) side will be in charge of:
- pulling snapshots using agent's dedicated API every X minutes
- storing data into dedicated storage in temboard repository
- purging old data from temboard repository
- rendering data on a web page

## Configuration

We should be able to configure:
- the interval between each snapshot, expressed in seconds, minimum value could be 10 minutes
- the amount of data to keep in the history, expressed in days, maximum value must be 30 days

```ini
[statements]
snapshot_interval=600
keep_data=30
```

## Storage

Collected data will be stored into temboard database. A dedicated table must be created for it.

### Data partitioning and purge policy

Due to potential large volume of data, this table could be partitioned using `snapshot_timedate` as partitioning key. Having one partition per day will ease data purge because we just have to drop the unnecessary partition to apply purge policy.
WARNING: data partitioning requires recent PostgreSQL version.

## Background workers

We'll need the implementation of 2 background workers:
- One in charge of getting data snapshot every `snapshot_interval` seconds.
- One in charge of creating the data partition for NOW + 1 day and removing unnecessary data partition (purge policy). This worker should run once a day.

## UI

Finally, we want to render on the UI the data we've collected. We should present them with a table + chart.
The table should contain all the collected data, each column could be used to sort the data. We want to filter the data by: `queryid`, `dbname` or `username`.
User can be able to change the time interval, default could be one day from now.
The chart should help the user to identify quickly the time periods where lot of statements were caught.

**Comment by dlax** [comment]
Do we want the plugin to be enabled by default in the agent?

**Comment by julmon** [comment]
> Do we want the plugin to be enabled by default in the agent?

Yes, please.
