### ISSUE TITLE
Add users management API

### ISSUE THREAD

**Issue by l00ptr** [dalibo/temboard#693]
Hello,

It could be  nice to have an API to manage (Create, Read, Update, Delete)  the temboard (and agent) users. The idea is to be able to manage users for those who don't use a centralized idm backend (LDAP or other centralized user source) .

**Comment by bersace** [comment]
There is an undocumented JSON API at /json/settings.  Here is a Python client API based on this JSON API :

https://gitlab.com/dalibo/cornac/-/blob/master/service/cornac/temboard.py

**Comment by bersace** [comment]
temBoard 8 doesn't have users management on agent side. This issue is not relevant anymore.
