### ISSUE TITLE
LDAP Authentification

### ISSUE THREAD

**Issue by daamien** [dalibo/temboard#701]
- [ ] Temboard UI administrators can choose the authentification mode for a given user
- [ ] Temboard UI administrators can define an LDAP authentification server 
- [ ] Temboard UI administrators can create new users and "map" them to an LDAP user. If no LDAP role is provided, the same username is used for Temboard and for LDAP.
- [ ] Temboard UI administrators can modify and existing user and change its authentification mode

**Comment by l00ptr** [comment]
Common (basic) SSO solution use both LDAP backend and HTTP header "REMOTE_USER". So i think it could be great to think about  using / reading HTTP header when  implementing feature.
