### ISSUE TITLE
Agents version into the web interface

### ISSUE THREAD

**Issue by l00ptr** [dalibo/temboard#724]
Hello,

Some information about the agents are missing into the web interface. For each agent it could be great to see the version - not the version of postgres - but the version of the temboard-agents. 

With the possibility to mix temboard-agent v4 & temboard-agent v5, this feature will help me to identify what I still need to upgrade or not. (It will stay usefull if the temboard server keeps the ability to monitor differents versions of the agent in the future) 

It could also help to define which agents are in pull mode and which ones are in push mode. Actually i can't get this information from UI. 

I don't know if it's the same issue but it could be great to see this information when you add  new instance from the admin interface. 

Best regards,
l.

**Comment by bersace** [comment]
cf. #672

**Comment by bersace** [comment]
To be released in 8.
