### ISSUE TITLE
Upgrade Temboard 4.1 to 5.1 on Debian Stretch issue

### ISSUE THREAD

**Issue by ced75** [dalibo/temboard#736]
Hi,

I'm trying to upgrade my Temboard server from 4.1 to 5.1 using the Debian packages.
But the package install raises the following error:

> Dépaquetage de temboard (5.1-0dlb1stretch1) sur (4.1-0dlb1stretch1) ...
dpkg: erreur de traitement de l'archive /var/cache/apt/archives/temboard_5.1-0dlb1stretch1_amd64.deb (--unpack) :
 impossible d'ouvrir « /usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/sql/schema.py.dpkg-new »: Opération non permise
Des erreurs ont été rencontrées pendant l'exécution :
 /var/cache/apt/archives/temboard_5.1-0dlb1stretch1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

I'm applying the upgrade as a sudoer user, but the problem seems to come from a sql upgrade.
How can I resolve this issue?

Thanks in advance for your help,
Cedric

**Comment by l00ptr** [comment]
Hi ced75,

Could you provide some information about your system ? Coud you add the output of the following commands to this issue (without those info we can't help you):

```
sudo -l
```

```
apt-cache policy
```

```
cat /proc/mounts 
```

Could you tell if the /usr/lib/temboard  dir exist ? If this is the case, please could you share the result of this command :
```
namei -l  /usr/lib/temboard
```

Best regards,
L.

**Comment by ced75** [comment]
Hi, 

Thanks for your help.
Here are some additional informations about my system:

> lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.12 (stretch)
Release:	9.12
Codename:	stretch

> sudo -l
Entrées par défaut pour admin sur inv-monitor :
    env_reset, mail_badpass, secure_path=/usr/local/sbin\:/usr/local/bin\:/usr/sbin\:/usr/bin\:/sbin\:/bin

L'utilisateur admin peut utiliser les commandes suivantes sur inv-monitor :
    (ALL : ALL) ALL

> apt-cache policy
Fichiers du paquet :
 100 /var/lib/dpkg/status
     release a=now
 500 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main amd64 Packages
     release o=apt.postgresql.org,a=stretch-pgdg,n=stretch-pgdg,l=PostgreSQL for Debian/Ubuntu repository,c=main,b=amd64
     origin apt.postgresql.org
 500 http://apt.dalibo.org/labs stretch-dalibo/main all Packages
     release o=labs stretch-dalibo,a=stretch-dalibo,n=stretch-dalibo,l=labs stretch-dalibo,c=main,b=all
     origin apt.dalibo.org
 500 http://apt.dalibo.org/labs stretch-dalibo/main amd64 Packages
     release o=labs stretch-dalibo,a=stretch-dalibo,n=stretch-dalibo,l=labs stretch-dalibo,c=main,b=amd64
     origin apt.dalibo.org
 500 http://miroir.ign.fr/debian-security stretch/updates/contrib amd64 Packages
     release v=9,o=Debian,a=oldstable,n=stretch,l=Debian-Security,c=contrib,b=amd64
     origin miroir.ign.fr
 500 http://miroir.ign.fr/debian-security stretch/updates/non-free amd64 Packages
     release v=9,o=Debian,a=oldstable,n=stretch,l=Debian-Security,c=non-free,b=amd64
     origin miroir.ign.fr
 500 http://miroir.ign.fr/debian-security stretch/updates/main amd64 Packages
     release v=9,o=Debian,a=oldstable,n=stretch,l=Debian-Security,c=main,b=amd64
     origin miroir.ign.fr
 500 http://miroir.ign.fr/debian stretch/contrib amd64 Packages
     release v=9.12,o=Debian,a=oldstable,n=stretch,l=Debian,c=contrib,b=amd64
     origin miroir.ign.fr
 500 http://miroir.ign.fr/debian stretch/non-free amd64 Packages
     release v=9.12,o=Debian,a=oldstable,n=stretch,l=Debian,c=non-free,b=amd64
     origin miroir.ign.fr
 500 http://miroir.ign.fr/debian stretch/main amd64 Packages
     release v=9.12,o=Debian,a=oldstable,n=stretch,l=Debian,c=main,b=amd64
     origin miroir.ign.fr
Paquets épinglés :

> cat /proc/mounts
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=2020328k,nr_inodes=505082,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=405096k,mode=755 0 0
/dev/mapper/Vol1-systeme / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=36,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=8916 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
/dev/mapper/Vol1-var /var ext4 rw,relatime,data=ordered 0 0
/dev/mapper/Vol1-home /home ext4 rw,relatime,data=ordered 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
tmpfs /run/user/1001 tmpfs rw,nosuid,nodev,relatime,size=405092k,mode=700,uid=1001,gid=1001 0 0

/usr/lib/temboard directory exists.

> namei -l  /usr/lib/temboard
f: /usr/lib/temboard
drwxr-xr-x root root /
drwxr-xr-x root root usr
drwxr-xr-x root root lib
drwxr-xr-x root root temboard

Best regards,
Cedric

**Comment by ced75** [comment]
It seems that the upgrade worked this morning.
I don't know what happened last week.

Sorry for the disturbance and once again thanks for help.

Cedric

**Comment by bersace** [comment]
Pas de soucis. Je ferme.
