### ISSUE TITLE
Upgrade monitored PG cluster - actions required?

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#739]
If I upgrade a PG cluster that temboard is monitoring what (if any) actions do I need to take for temboard to continue to be able to monitor it?

**Comment by bersace** [comment]
Hi @dgiffin Ensure you run latest temBoard release to have support for latest Postgres releases.

**Comment by pgiraud** [comment]
You may need to go the settings section in temBoard interface, pretend you want to edit the instance then save without changing anything. TemBoard will make sure to retrieve the new information from the agent. After that the PG version should be up-to-date.

See #666
