### ISSUE TITLE
Filter Out Specific File Systems for "File systems usage" Check

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard#748]
We have a NFS backup filesystem that is mounted on every PostgreSQL host that we have. Over the weekend it exceeded the warning threshold in temboard and now the main UI dashboard shows **all** hosts in an overall "warning" state. This is a bit of a false alarm at a glance and we are wondering if an enhancement can be added where we can filter one or more file systems based on names or patterns against _all_ hosts in the system.

I wasn't sure if this was a UI or agent enhancement, apologies.

Thanks.

**Comment by bersace** [comment]
Hi Bob, that's a good catch.

> I wasn't sure if this was a UI or agent enhancement, apologies.

No worry. GitHub allows us to transfer issue from one project to another if needed.

**Comment by pgiraud** [comment]
Duplicate for #612
