### ISSUE TITLE
Activity : idle in transaction is marked as bold red

### ISSUE THREAD

**Issue by wsescu** [dalibo/temboard#769]
Dear temBoard Team

since the upgrade to temBoard Version 6.1 I see all the time a idle in transaction. The host meantioned in the SQL is always the temBoard monitoring instance itself.

```
SELECT anon_1.application_instances_agent_address AS anon_1_application_instances_agent_address, 
anon_1.application_instances_agent_port AS anon_1_application_instances_agent_port, 
anon_1.application_instances_agent_key AS anon_1_application_instances_agent_key, 
anon_1.application_instances_hostname AS anon_1_application_instances_hostname, 
anon_1.application_instances_cpu AS anon_1_application_instances_cpu, 
anon_1.application_instances_memory_size AS anon_1_application_instances_memory_size, 
anon_1.application_instances_pg_port AS anon_1_application_instances_pg_port, 
anon_1.application_instances_pg_version AS anon_1_application_instances_pg_version, 
anon_1.application_instances_pg_version_summary AS anon_1_application_instances_pg_version_summary, 
anon_1.application_instances_pg_data AS anon_1_application_instances_pg_data, 
anon_1.application_instances_notify AS anon_1_application_instances_notify, 
instance_groups_1.agent_address AS instance_groups_1_agent_address, 
instance_groups_1.agent_port AS instance_groups_1_agent_port, 
instance_groups_1.group_name AS instance_groups_1_group_name, 
instance_groups_1.group_kind AS instance_groups_1_group_kind, 
plugins_1.agent_address AS plugins_1_agent_address, 
plugins_1.agent_port AS plugins_1_agent_port, 
plugins_1.plugin_name AS plugins_1_plugin_name 
FROM (SELECT application.instances.agent_address AS application_instances_agent_address, 
application.instances.agent_port AS application_instances_agent_port, 
application.instances.agent_key AS application_instances_agent_key, 
application.instances.hostname AS application_instances_hostname, 
application.instances.cpu AS application_instances_cpu, 
application.instances.memory_size AS application_instances_memory_size, 
application.instances.pg_port AS application_instances_pg_port, 
application.instances.pg_version AS application_instances_pg_version, 
application.instances.pg_version_summary AS application_instances_pg_version_summary, 
application.instances.pg_data AS application_instances_pg_data, 
application.instances.notify AS application_instances_notify 
FROM application.instances 
WHERE application.instances.agent_address = 'mon.company.ch' AND application.instances.agent_port = '48888' LIMIT 1) AS anon_1 
LEFT OUTER JOIN application.instance_groups AS instance_groups_1 ON anon_1.application_instances_agent_address = instance_groups_1.agent_address 
AND anon_1.application_instances_agent_port = instance_groups_1.agent_port
```

I have set the parameter idle_in_transaction_session_timeout = 120000 on the temBoard instance, however, this is only a workaround and does not fix the issue itself.

Would be cool if you could advise how to fix this issue.

Best regards
William

**Comment by wsescu** [comment]
![image](https://user-images.githubusercontent.com/54099545/84864907-a986c500-b077-11ea-8a27-83e99e7e5991.png)

**Comment by bersace** [comment]
Hi @wsescu do you known which page of temBoard UI triggers this query ? It looks like it's temBoard homepage.

**Comment by bersace** [comment]
No, it looks like a simple call to `get_instance()`

**Comment by bersace** [comment]
@wsescu can you send us logs ?

**Comment by wsescu** [comment]
I have no idea which UI page triggers this query. The only thing I have observed, is that the hostname in the SQL which is idle in transaction, always is the temBoard monitoring host itself.
What logs do you need, the Agent or the Server logs.

**Comment by bersace** [comment]
I got it !

**Comment by bersace** [comment]
@wsescu I don't have long idled transactions. The PID is changing and time is still low as 0.15s. Do you have the same behaviour ?

**Comment by bersace** [comment]
It looks like it's just the Activity tab that is querying temboard database when refreshing the view. Can you details any issue other than this *idle in transaction* line appearing ?

**Comment by bersace** [comment]
Maybe should temBoard not mark as read a transaction idle for less than 1s.

**Comment by wsescu** [comment]
Yes. You are right. The PID is changing all the time. I did not notice that beforehand. However, it is always the same query.

**Comment by wsescu** [comment]
>Maybe should temBoard not mark as read a transaction idle for less than 1s
Yes. That would be a good idea. Else you would see always idle in transactions, which is very confusing.

**Comment by bersace** [comment]
@wsescu We have identified this misleading information and we'll fix this for a following major release, along other improvements on UX of this page.
