### ISSUE TITLE
Upgrade to 6.1 from 5.0 : temboard-migratedb fails

### ISSUE THREAD

**Issue by ced75** [dalibo/temboard#774]
Hi,

I'm trying to ugrade my temboard server from 5.0 to 6.1.
After the apt upgrade, the temboard service does not restart.
The error message indicates that Database is not up to date. Please use temboard-migratedb.

Then I try to execute temboard-migratedb with the following command:
sudo temboard-migratedb stamp

But I get a new error message:
CRITI: Failed to query Postgres server: (psycopg2.OperationalError) FATAL:  Peer authentication failed for user "temboard"
CRITI: 
CRITI: (Background on this error at: http://sqlalche.me/e/e3q8).

I do not have a linux "temboard" user. This seems to be new.
What should I do to perform the temboard-migratedb correctly?

Thanks in advance for your help,

Cedric

**Comment by bersace** [comment]
Salut @ced75 

Which user is running temboard service ? What is the output of `sudo DEBUG=y temboard-migratedb stamp` ?

**Comment by ced75** [comment]
Salut @bersace 

I think it is my admin user that should be the owner of temboard service, but I don't know how to check it since the service is down.

> sudo DEBUG=y temboard-migratedb stamp
> 2020-06-19 11:10:05,767 [31656] [app             ]  INFO: Starting temboard-migratedb 6.1.
> 2020-06-19 11:10:05,769 [31656] [app             ]  INFO: Found config file /etc/temboard/temboard.conf.
> 2020-06-19 11:10:05,769 [31656] [app             ] DEBUG: Reading /etc/temboard/temboard.conf.
> /usr/lib/temboard/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
>   """)
> 2020-06-19 11:10:05,777 [31656] [migratedb       ] DEBUG: Using Python 2.7.13 (/usr/bin/python2.7).
> 2020-06-19 11:10:05,777 [31656] [migratedb       ] DEBUG: Using Psycopg2 2.7.7 (dt dec pq3 ext lo64), Alembic 1.4.2 and SQLAlchemy 1.3.17
> 2020-06-19 11:10:05,784 [31656] [app             ] CRITI: Failed to query Postgres server: (psycopg2.OperationalError) FATAL:  Peer authentication failed for user "temboard"
> 2020-06-19 11:10:05,784 [31656] [app             ] CRITI: 
> 2020-06-19 11:10:05,784 [31656] [app             ] CRITI: (Background on this error at: http://sqlalche.me/e/e3q8).

**Comment by bersace** [comment]
@ced What about `systemctl cat temboard` ?

**Comment by ced75** [comment]
> Description=temBoard Web UI
> After=network.target
> 
> [Service]
> Type=simple
> User=temboard
> Group=temboard
> ExecStart=/usr/bin/env SYSTEMD=1 temboard -c /etc/temboard/temboard.conf
> 
> [Install]
> WantedBy=multi-user.target

**Comment by bersace** [comment]
Ok then try `sudo -u temboard temboard-migratedb stamp`

**Comment by ced75** [comment]
Yes, that did it!
Thanks a lot.
The documentation should perhaps be updated to avoid the same problem. What do you think about it?

**Comment by bersace** [comment]
@ced75 agree, we should state to run temboard-migratedb as same user as temboard service.

**Comment by ced75** [comment]
Thanks again, TemBoard server is up again.
The agent upgrade works fine.

**Comment by bersace** [comment]
Je rouvre pour mettre à jour la doc.
