### ISSUE TITLE
Invalid key after 6.0 upgrade

### ISSUE THREAD

**Issue by ced75** [dalibo/temboard#775]
Sorry, I have a new problem with v6.0 migration.

I upgraded the TemBoard agent on all my Postgres server.
For one server, in TemBoard interface, I get an "invalid key".
But the key in the configuration tool seems to be OK.

On the server, I tried to purge the agent with the purge.sh script mentionned in the documentation.
But there is no purge.sh script, on my server, neither in /usr/share/temboard-agent/share/ (documentation), nor in /usr/share/temboard-agent (path indicated in the error message when executing auto_configure.sh again).

How can I get the right key?

**Comment by bersace** [comment]
Salut,

key is in /etc/temboard-agent/XX/

Something like

```
[temboard]
...
# Key
key = SECRETKEYTOBECHANGED

[postgresql]
...
```

**Comment by bersace** [comment]
Right, purge.sh is missing. Avoid running purge unless you really want to lost all history of an agent.

**Comment by ced75** [comment]
In the config file, the key is SECRETKEYTOBECHANGED, curiously...
I tried to modify the key in Temboard interface to "SECRETKEYTOBECHANGED", but it did not work.
I also tried to put the old key in the /etc/temboard-agent/11/main/temboard-agent.conf file in place of SECRETKEYTOBECHANGED, then I restarted temboard-agent service.
But I still get the same "invalid key" error in Temboard interface for that server.

**Comment by ced75** [comment]
OK... I have found it.
The right config file is in /etc/temboard-agent/11/main/temboard-agent.conf.d/auto.conf.
Here is the rigth key.

It worked.

Thanks for your help again.
I think it is OK for me today.

Cedric

**Comment by bersace** [comment]
@ced75 does your temboard-agent.cont talk about auto.conf in the header. We should make this more explicit.

**Comment by ced75** [comment]
How can I find this information?

**Comment by bersace** [comment]
``` console
$ head /etc/temboard-agent/11/main/temboard-agent.conf
#
#   T E M B O A R D   A G E N T   C O N F I G U R A T I O N
#
# This file contains all possible settings of temBoard agent, with defaults for
# quickstart. temBoard agent overrides values of this file with .conf files
# found in directory named after this filename, with .d suffix. e.g.
# temboard-agent.conf.d/auto.conf is likely to override some values of this
# file.
#
...
```

**Comment by ced75** [comment]
OK. Thanks.
It does not:

```
postgres@inv-exp:/etc/temboard-agent/11/main$ head temboard-agent.conf
[temboard]
# Bind port.
port = 2345
# Bind address.
address = 0.0.0.0
# User & password file.
users = users
# Plugins in use.
plugins = ["monitoring", "dashboard", "pgconf", "administration", "activity", "maintenance"]
# SSL: certificat file path (.pem)
```

**Comment by bersace** [comment]
ok, that may be an old setup.

**Comment by ced75** [comment]
Sure, I'm upgrading temboard agent on these servers since version 3.x.
