### ISSUE TITLE
Cannot start temboard service under CentOS 7.6

### ISSUE THREAD

**Issue by jeanloesch** [dalibo/temboard#777]
Hi,

After installing temboard-6.0-1.el7.noarch and starting the service, the command "systemctl status temboard" command showed this error :
```
● temboard.service - temBoard Web UI
   Loaded: loaded (/usr/lib/systemd/system/temboard.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since lun. 2020-06-22 16:24:51 CEST; 4s ago
  Process: 95960 ExecStart=/usr/bin/env SYSTEMD=1 temboard -c /etc/temboard/temboard.conf (code=exited, status=1/FAILURE)
 Main PID: 95960 (code=exited, status=1/FAILURE)

juin 22 16:24:51 lin3e156.tlt env[95960]:     for step in self._migrations_fn(heads, self):
juin 22 16:24:51 lin3e156.tlt env[95960]:   File "/usr/lib/python2.7/site-packages/temboardui/model/__init__.py", line 88, in fn
juin 22 16:24:51 lin3e156.tlt env[95960]:     current_obj = next(iter(script.get_all_current(current)))
juin 22 16:24:51 lin3e156.tlt env[95960]: AttributeError: 'ScriptDirectory' object has no attribute 'get_all_current'
juin 22 16:24:51 lin3e156.tlt env[95960]: temboardui version is 6.0.
juin 22 16:24:51 lin3e156.tlt env[95960]: This is a bug!
juin 22 16:24:51 lin3e156.tlt env[95960]: Please report traceback to https://github.com/dalibo/temboard/issues! Thanks!
juin 22 16:24:51 lin3e156.tlt systemd[1]: temboard.service: main process exited, code=exited, status=1/FAILURE
juin 22 16:24:51 lin3e156.tlt systemd[1]: Unit temboard.service entered failed state.
juin 22 16:24:51 lin3e156.tlt systemd[1]: temboard.service failed.
```

Here are messages from journalctl -xe command 
```
Jun 22 16:21:49 lin3e156 systemd: Started temBoard Web UI.
Jun 22 16:21:49 lin3e156 env: INFO: Starting temboard 6.0.
Jun 22 16:21:49 lin3e156 env: INFO: Running on CentOS Linux 7 (Core).
Jun 22 16:21:49 lin3e156 env: INFO: Using Python 2.7.5 (/usr/bin/python).
Jun 22 16:21:49 lin3e156 env: INFO: Using Psycopg2 2.5.1 (dt dec pq3 ext), Tornado 4.2.1 and SQLAlchemy 0.9.8
Jun 22 16:21:49 lin3e156 env: setuptools is too old for plugin hotload.
Jun 22 16:21:49 lin3e156 env: If new plugin can't be found, just restart.
Jun 22 16:21:49 lin3e156 env: Loaded plugin 'activity'.
Jun 22 16:21:49 lin3e156 env: Loaded plugin 'dashboard'.
Jun 22 16:21:49 lin3e156 env: Loaded plugin 'monitoring'.
Jun 22 16:21:49 lin3e156 env: Loaded plugin 'pgconf'.
Jun 22 16:21:49 lin3e156 env: Loaded plugin 'maintenance'.
Jun 22 16:21:49 lin3e156 env: Unhandled error:
Jun 22 16:21:49 lin3e156 env: Traceback (most recent call last):
Jun 22 16:21:49 lin3e156 env:  File "/usr/lib/python2.7/site-packages/temboardui/toolkit/app.py", line 301, in entrypoint
Jun 22 16:21:49 lin3e156 env:    retcode = self.main(argv, environ)
Jun 22 16:21:49 lin3e156 env:  File "/usr/lib/python2.7/site-packages/temboardui/__main__.py", line 360, in main
Jun 22 16:21:49 lin3e156 env:    check_schema(self.config)
Jun 22 16:21:49 lin3e156 env:  File "/usr/lib/python2.7/site-packages/temboardui/model/__init__.py", line 106, in check_schema
Jun 22 16:21:49 lin3e156 env:    script.run_env()
Jun 22 16:21:49 lin3e156 env:  File "/usr/lib/python2.7/site-packages/alembic/script/base.py", line 397, in run_env
Jun 22 16:21:49 lin3e156 env:    util.load_python_file(self.dir, 'env.py')
Jun 22 16:21:49 lin3e156 env:  File "/usr/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
Jun 22 16:21:49 lin3e156 env:    module = load_module_py(module_id, path)
Jun 22 16:21:49 lin3e156 env:  File "/usr/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
```

Do you know what is going wrong ?

Thank you for your help.

**Comment by pgiraud** [comment]
This may be the same issue as reported in https://github.com/dalibo/temboard/issues/762
Can you please try to install temboard 6.1?

**Comment by jeanloesch** [comment]
Hi,

Temboard 6.1 is installed.
rpm -qa|grep -i temb
temboard-6.1-1.el7.noarch

The service is now running. However there are error messages :
systemctl status temboard
● temboard.service - temBoard Web UI
   Loaded: loaded (/usr/lib/systemd/system/temboard.service; enabled; vendor preset: disabled)
   Active: active (running) since mar. 2020-06-23 15:30:07 CEST; 4s ago
 Main PID: 26710 (temboard)
   CGroup: /system.slice/temboard.service
           ├─26710 temboard: web
           ├─26717 temboard: worker pool
           └─26718 temboard: scheduler

juin 23 15:30:10 lin3e156.tlt env[26710]:     return func(request, *args)
juin 23 15:30:10 lin3e156.tlt env[26710]:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/monitoring.py", line 82, in collector
juin 23 15:30:10 lin3e156.tlt env[26710]:     check_agent_request(request, hostname, instance)
juin 23 15:30:10 lin3e156.tlt env[26710]:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/monitoring.py", line 44, in chec...nt_request
juin 23 15:30:10 lin3e156.tlt env[26710]:     key)
juin 23 15:30:10 lin3e156.tlt env[26710]:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/tools.py", line 119, in check_agent_key
juin 23 15:30:10 lin3e156.tlt env[26710]:     raise Exception("Could not find agent key.")
juin 23 15:30:10 lin3e156.tlt env[26710]: Exception: Could not find agent key.
juin 23 15:30:10 lin3e156.tlt env[26710]: Request failed: 500 Could not find agent key..
juin 23 15:30:10 lin3e156.tlt env[26710]: 500 POST /monitoring/collector (10.37.116.98) 9.64ms


I have another question. Does temboard agent 6.0.1 work with Temboard 6.1 ?

Thanks.

**Comment by pgiraud** [comment]
Can you please have a look at https://github.com/dalibo/temboard/issues/775 ?

Yes temboard agents > 6.0 are compatible with temboard 6.1.

**Comment by pgiraud** [comment]
@jeanloesch did you manage to get it working? Can we close the issue?

**Comment by jeanloesch** [comment]
Hi,

I took a look at #775 but it is not related to the installation on the server but rather the agent.

**Comment by pgiraud** [comment]
Can you please go to the settings page for this instance and make sure there's a value for "Agent secret key"?

**Comment by jeanloesch** [comment]
Hi,

Which instance ? I am not sure I understand. Maybe I missed something.
One year ago, I installed Temboard 3 and the installation went smoothly without any problems on both server side and agent side.

Let me describe my current environment as I want to start from scratch and install Temboard 6.

On my CentOs VM, there is an postgres Instance (v12.3).
postgres  89872  89871  0 Jun22 ?        00:00:00 postgres: PG_TEMBOARD_PFI: logger
postgres  89874  89871  0 Jun22 ?        00:00:01 postgres: PG_TEMBOARD_PFI: checkpointer
postgres  89875  89871  0 Jun22 ?        00:00:23 postgres: PG_TEMBOARD_PFI: background writer
postgres  89876  89871  0 Jun22 ?        00:00:03 postgres: PG_TEMBOARD_PFI: walwriter
postgres  89877  89871  0 Jun22 ?        00:00:07 postgres: PG_TEMBOARD_PFI: autovacuum launcher
postgres  89878  89871  0 Jun22 ?        00:00:15 postgres: PG_TEMBOARD_PFI: stats collector
postgres  89879  89871  0 Jun22 ?        00:00:00 postgres: PG_TEMBOARD_PFI: logical replication launcher

This instance is my temboard repository and I don't want to monitor it. So temboard agent don't have to be installed on the VM.
Though, I have to install Temboard server (TemboardUI).
That's what I did with all the problems you are aware.
I don't understand why I got errors about "agent key". There is no agent yet.

Am I missing anything about the architecture of Temboard ? Did I misunderstand anything ?

Thank you.

**Comment by bersace** [comment]
Hi @jeanloesch do you have updates on this issue ? I confirm your understanding of temBoard architecture. You only need an agent per instance you want to monitor. temBoard UI can store its data in an unmanaged instance. temBoard UI does not need an agent to store data in a Postgres instance.

**Comment by daamien** [comment]
This issue has been inactive for several weeks. Unless you can provide new elements to the discussion, we will close it in a few days.
