### ISSUE TITLE
Heap bloat ratio estimation undefined

### ISSUE THREAD

**Issue by ced75** [dalibo/temboard#784]
Hi,

I'm using temboard 6 to monitor several servers with PostgreSQL 12.
On one server, heap bloat ratio estimation appears as "undefined", whereas it is OK on all others.
On this server, the main database has pgstattuple extension (which could be required for bloat estimation?).

Is there something missing (SQL script for example) on this server?

Thanks in advance for your help.
Kind regards,

Cedric

**Comment by pgiraud** [comment]
Is this error still accurate?
Have you tried to install a new version of the agent?
Some improvements have been done on the query which estimates the bloat.

**Comment by ced75** [comment]
With the last 5.7 version, the problem has been solved.
Regards,

Cedric
