### ISSUE TITLE
create_repository.sh does not work if pg is on a different port

### ISSUE THREAD

**Issue by orgrim** [dalibo/temboard#804]
The `temboard-migratedb` command does not use the PG* environment variables, so the calls in https://github.com/dalibo/temboard/blob/master/share/create_repository.sh#L17-L18:

```
if ! temboard-migratedb check ; then
    temboard-migratedb upgrade
```

only work with non default host/port/etc if the configuration file is provided with `--config`

**Comment by bersace** [comment]
@orgrim as a workaround temboard-migratedb supports `TEMBOARD_REPOSITORY_HOST`, `TEMBOARD_REPOSITORY_PORT`, `TEMBOARD_REPOSITORY_USER`, `TEMBOARD_REPOSITORY_PASSWORD` and `TEMBOARD_REPOSITORY_DBNAME` like `temboard`.

**Comment by pgiraud** [comment]
@bersace can you confirm the current issue can be closed now?

**Comment by bersace** [comment]
@pgiraud :+1:
