### ISSUE TITLE
auto_configure.sh no longer work - user connection done at the wrong place

### ISSUE THREAD

**Issue by l00ptr** [dalibo/temboard#809]
auto_configure.sh no longer work since the v6 of temboard

We check the DB connection with the temboard role before creating it - So this test will always fail except if we created the user before (manually or by any other means). 

We can fix this problem by moving the check done there https://github.com/dalibo/temboard/blob/v6/share/auto_configure.sh#L162 after the repository creation.

**Comment by pgiraud** [comment]
It has been fixed via #810.
Backported in v6 via 866e076e99ef2d3bc5fe54995ce4a5164f8b69f8
