### ISSUE TITLE
Temboard not present on the Dalibo Labs YUM repository

### ISSUE THREAD

**Issue by egaultier** [dalibo/temboard#859]
Hello

On CentOs 8, 
I add then Dalibo Labs YUM repository with problem
yum makecache OK (fast don't work) 

But When I search temboard : 

![image](https://user-images.githubusercontent.com/67147948/94564010-c1213c80-0267-11eb-8cf2-f28138a8056e.png)

Only temboard.agent is found.

Thank you for your help.

Gaultier Emmanuel

**Comment by pgiraud** [comment]
Unfortunately temboard UI is not available for CentOS8 yet. Sorry for the inconvenience.

**Comment by pgiraud** [comment]
You can still consider installing temboard using pypi.

**Comment by egaultier** [comment]
OK.

I will test with pypi or install on another server

Thank you for your quick answers.
