### ISSUE TITLE
Unable to connect to postgres

### ISSUE THREAD

**Issue by xroman70** [dalibo/temboard#869]
Getting "Unable to connect to postgres" on main temboard web page for newly added agent.
![temboard_unable](https://user-images.githubusercontent.com/59317572/95602943-04c83300-0a2c-11eb-87f4-032bf5761468.jpg)

**Comment by xroman70** [comment]
output for "systemctl status temboard": 

 env[28188]:   File "/usr/lib64/python2.7/urllib2.py", line 475, in error
 env[28188]:     return self._call_chain(*args)
 env[28188]:   File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
 env[28188]:     result = func(*args)
 env[28188]:   File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
 env[28188]:     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
 env[28188]: HTTPError: HTTP Error 401: Unauthorized
 env[28188]: Job 769b45de is dead
 env[28188]: Job output : {'content': None, 'type': (5,)}
 env[28188]: Received Message={'content': {'status': 16, 'output': None, 'stop_datetime': datetime.datetime(20...ype': 1}

 env[28188]:     return func(request, *args)
 env[28188]:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/monitoring.py", l...a_metric
 env[28188]:     host_id, instance_id = get_request_ids(request)
 env[28188]:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/tools.py", line 93, in get...uest_ids
 env[28188]:     host_id = get_host_id(request.db_session, request.instance.hostname)
 env[28188]:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/tools.py", line 75, in get_host_id
 env[28188]:     "Could not find registered host with hostname=%s" % hostname
 env[28188]: Exception: Could not find registered host with hostname=dev-gt-db-01.prv.gen.io
 env[28188]: Request failed: 500 Could not find registered host with hostname=dev-gt-db-01.prv.gen.io.
 env[28188]: 500 GET /server/dev-gt-db-01.prv.gen.io/2345/monitoring/data/load1?start=2020-10-09T14:57... 73.69ms

**Comment by pgiraud** [comment]
@xroman70 Sorry for the late answer. Apparently temboard managed

First of all, the error "Exception: Could not find registered host with hostname=dev-gt-db-01.prv.gen.io" is not very critical. It usually appear when you try to show information about an instance. The monitoring plugin hasn't collected any data yet. This error usually disappears after the first minutes.

For the "Unable to connect to postgres", we have to investigate with you a bit more.
Do you see any system metrics in the dashboard page for the instance? This would mean that temboard is able to reach the agent.
Do you also have "Unable to connect to postgres" errors on the dashboard page? If so, can you please check for any errors in the logs on the agent side?

**Comment by xroman70** [comment]
I don't see system metrics for the instance. Yes, the error ""Unable to connect to postgres" is visible on dashboard page. Agent side errors: 
 env[1960]: client: ip-172-22-10-56 request: "GET /discover HTTP/1.1" 200 - 14.03ms
 env[1960]: {'error': 'Invalid key'}
 env[1960]: Traceback (most recent call last):
 env[1960]:   File "/usr/lib/python2.7/site-packages/temboardagent/httpd.py", line 132, in response
 env[1960]:     (code, message) = self.route_request()
 env[1960]:   File "/usr/lib/python2.7/site-packages/temboardagent/httpd.py", line 248, in route_request
 env[1960]:     raise HTTPError(401, "Invalid key")
 env[1960]: HTTPError: Invalid key
 env[1960]: {'error': 'Invalid key'}
 env[1960]: client: ip-172-22-10-56.ec2.internal request: "GET /monitoring/history?key=SECRETKEYTOBECHANGED..

**Comment by pgiraud** [comment]
Can you make sure that the `key` in the `[temboard]` in the configuration for the agent matches the one you can see in the UI in the settings for this instance?
You may have changed the key after the agent was registered.

**Comment by xroman70** [comment]
The key value has been changed in auto.conf to math with one from the settings for the instance. No errors to report. Thank you.

**Comment by xroman70** [comment]
Solution has been provided.
