### ISSUE TITLE
Temboard 7.3: instances do not appear in the main screen

### ISSUE THREAD

**Issue by ced75** [dalibo/temboard#874]
Hi,

I upgraded to Temboard 7.3 and all my instances disappeared from the main screen.
So I reinstalled a new fresh agent on one of my PostgreSQL servers. The install seemed to work, since it appears in the instances list in settings:
![image](https://user-images.githubusercontent.com/12892581/96691947-c6186e00-1385-11eb-9553-a844dfdb814e.png)

But the main screen remains empty:
![image](https://user-images.githubusercontent.com/12892581/96691693-7f2a7880-1385-11eb-877e-a27f8d99274a.png)

What could cause this problem?

Thanks in advance for your help.

**Comment by pgiraud** [comment]
Apparently there's a javascript error (see the raw value in the Groups button).
Can you open the developper tools in your browser and see if you can find any JS error?
Also, are there any errors in the temboard UI logs?

**Comment by ced75** [comment]
Thanks for your answer.
Could you remind me where I can find temboard UI logs?

**Comment by pgiraud** [comment]
https://github.com/dalibo/temboard/issues/629#issuecomment-489997673

**Comment by ced75** [comment]
Curiously, it works again.
But I did nothing special for this, except I opened Temboard from Chrome instead of Firefox. 
It also works in Firefox now.
Very weird...

**Comment by pgiraud** [comment]
Indeed, very weird.

**Comment by ced75** [comment]
Here are logs generated when I go to the status screen:
oct. 21 11:02:44 inv-monitor env[581]: Traceback (most recent call last):
oct. 21 11:02:44 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 227, in error_middleware
oct. 21 11:02:44 inv-monitor env[581]:     return func(request, *args)
oct. 21 11:02:44 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 408, in user_instance_middleware
oct. 21 11:02:44 inv-monitor env[581]:     return func(request, address, port, *args)
oct. 21 11:02:44 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 267, in instance_middleware
oct. 21 11:02:44 inv-monitor env[581]:     return callable_(request, *args)
oct. 21 11:02:44 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 431, in user_middleware
oct. 21 11:02:44 inv-monitor env[581]:     return func(request, *args)
oct. 21 11:02:44 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/alerting.py", line 91, in checks
oct. 21 11:02:44 inv-monitor env[581]:     host_id, instance_id = get_request_ids(request)
oct. 21 11:02:44 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/tools.py", line 93, in get_request_ids
oct. 21 11:02:44 inv-monitor env[581]:     host_id = get_host_id(request.db_session, request.instance.hostname)
oct. 21 11:02:44 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/tools.py", line 75, in get_host_id
oct. 21 11:02:44 inv-monitor env[581]:     "Could not find registered host with hostname=%s" % hostname
oct. 21 11:02:44 inv-monitor env[581]: Exception: Could not find registered host with hostname=new-del1207w108.ign.fr
oct. 21 11:02:44 inv-monitor env[581]: Request failed: 500 Could not find registered host with hostname=new-del1207w108.ign.fr.
oct. 21 11:02:44 inv-monitor env[581]: 500 GET /server/new-del1207w108.ign.fr/2345/alerting/checks.json (172.27.3.45) 16.15ms

The screen remains empty.

**Comment by pgiraud** [comment]
This error is not very clear. It usually appears when temboard hasn't retrieved any monitoring info from agent yet.
Because it's a new agent, temboard will first have to collect some data. It should happen after several minutes. Then the host will be known as per the monitoring plugin.

Can you confirm that the status page is not empty anymore?

**Comment by ced75** [comment]
No, the page remains empty.
And the dashboard only shows partial informations:
![image](https://user-images.githubusercontent.com/12892581/96702394-fe25ae00-1391-11eb-8793-c61dbf527e76.png)

**Comment by ced75** [comment]
I've exactly the same issue on a new added server.

**Comment by pgiraud** [comment]
Can you please show us the content of the `monitoring.hosts` table?

**Comment by ced75** [comment]
The table is empty.

**Comment by pgiraud** [comment]
Can you please search in the logs if there's any other error? It looks like temboard is unable to collect any monitoring data.

**Comment by ced75** [comment]
Something like that ?
oct. 21 13:40:07 inv-monitor env[581]: Traceback (most recent call last):
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 227, in error_middleware
oct. 21 13:40:07 inv-monitor env[581]:     return func(request, *args)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 408, in user_instance_middleware
oct. 21 13:40:07 inv-monitor env[581]:     return func(request, address, port, *args)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 267, in instance_middleware
oct. 21 13:40:07 inv-monitor env[581]:     return callable_(request, *args)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 431, in user_middleware
oct. 21 13:40:07 inv-monitor env[581]:     return func(request, *args)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/monitoring.py", line 156, 
oct. 21 13:40:07 inv-monitor env[581]:     host_id, instance_id = get_request_ids(request)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/tools.py", line 93, in get_request_
oct. 21 13:40:07 inv-monitor env[581]:     host_id = get_host_id(request.db_session, request.instance.hostname)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/tools.py", line 75, in get_host_id
oct. 21 13:40:07 inv-monitor env[581]:     "Could not find registered host with hostname=%s" % hostname
oct. 21 13:40:07 inv-monitor env[581]: Exception: Could not find registered host with hostname=new-del1207w108.ign.fr
oct. 21 13:40:07 inv-monitor env[581]: Request failed: 500 Could not find registered host with hostname=new-del1207w108.ign.fr.
oct. 21 13:40:07 inv-monitor env[581]: 500 GET /server/new-del1207w108.ign.fr/2345/monitoring/data/tps?start=2020-10-21T10:40:07.769Z&end=2020-10-21T11:40:07.
oct. 21 13:40:07 inv-monitor env[581]: Unhandled Error:
oct. 21 13:40:07 inv-monitor env[581]: Traceback (most recent call last):
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 227, in error_middleware
oct. 21 13:40:07 inv-monitor env[581]:     return func(request, *args)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 408, in user_instance_middleware
oct. 21 13:40:07 inv-monitor env[581]:     return func(request, address, port, *args)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 267, in instance_middleware
oct. 21 13:40:07 inv-monitor env[581]:     return callable_(request, *args)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 431, in user_middleware
oct. 21 13:40:07 inv-monitor env[581]:     return func(request, *args)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/monitoring.py", line 156, 
oct. 21 13:40:07 inv-monitor env[581]:     host_id, instance_id = get_request_ids(request)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/tools.py", line 93, in get_request_
oct. 21 13:40:07 inv-monitor env[581]:     host_id = get_host_id(request.db_session, request.instance.hostname)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/tools.py", line 75, in get_host_id
oct. 21 13:40:07 inv-monitor env[581]:     "Could not find registered host with hostname=%s" % hostname
oct. 21 13:40:07 inv-monitor env[581]: Exception: Could not find registered host with hostname=test-inv-prod.ign.fr
oct. 21 13:40:07 inv-monitor env[581]: Request failed: 500 Could not find registered host with hostname=test-inv-prod.ign.fr.
oct. 21 13:40:07 inv-monitor env[581]: Unhandled Error:
oct. 21 13:40:07 inv-monitor env[581]: Traceback (most recent call last):
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 227, in error_middleware
oct. 21 13:40:07 inv-monitor env[581]:     return func(request, *args)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 408, in user_instance_middleware
oct. 21 13:40:07 inv-monitor env[581]:     return func(request, address, port, *args)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 267, in instance_middleware
oct. 21 13:40:07 inv-monitor env[581]:     return callable_(request, *args)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 431, in user_middleware
oct. 21 13:40:07 inv-monitor env[581]:     return func(request, *args)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/monitoring.py", line 156, 
oct. 21 13:40:07 inv-monitor env[581]:     host_id, instance_id = get_request_ids(request)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/tools.py", line 93, in get_request_
oct. 21 13:40:07 inv-monitor env[581]:     host_id = get_host_id(request.db_session, request.instance.hostname)
oct. 21 13:40:07 inv-monitor env[581]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/tools.py", line 75, in get_host_id
oct. 21 13:40:07 inv-monitor env[581]:     "Could not find registered host with hostname=%s" % hostname
oct. 21 13:40:07 inv-monitor env[581]: Exception: Could not find registered host with hostname=test-inv-prod.ign.fr
oct. 21 13:40:07 inv-monitor env[581]: Request failed: 500 Could not find registered host with hostname=test-inv-prod.ign.fr.

**Comment by pgiraud** [comment]
Unfortunately this is not the kind of errors I'm looking for. These errors most probably appeared after trying to display the "monitoring" page using the interface.

**Comment by pgiraud** [comment]
Please contact me directly
pierre (dot) giraud (at) dalibo (dot) com

**Comment by bsislow** [comment]
Was there any traction on this? We are experiencing the same issue.

**Comment by ced75** [comment]
In my personal case, a full reinstall and a version upgrade of temBoard solved the problem.

Sometimes, the problem occurs when temBoard server and temBoard agent are not at the same version level.
Update the temBoard agent can be usefull.

**Comment by bsislow** [comment]
Upgrading to temboard UI 7.4 fixed this - thank you!
