### ISSUE TITLE
Metrics: Cannot Select Actual Time Range

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard#878]
on the monitoring/metrics page, i cannot select a "real" time range after selecting the "from" range. see below. when i select "from" november 6th, why can't i select november 6th as the "to" time range as well? i'm trying to look at a very narrow time range on the night of the 6th...

![image](https://user-images.githubusercontent.com/30243584/98553922-c198f400-2265-11eb-9ef4-5c3f1c843f0c.png)

fyi

```
$ rpm -qa| grep temboard
temboard-agent-7.0a6-1.el7.noarch
```

if i manually input the date range as such, i get "invalid date" even though the date is not invalid:

![image](https://user-images.githubusercontent.com/30243584/98554169-0a50ad00-2266-11eb-8575-23564856211e.png)

thanks.

**Comment by pgiraud** [comment]
@bsislow A version 7.4 of temBoard has just been released. There's a fix for your problem. Can you please have a try and let us know?
Please make sure that you browser cache is cleared.
