### ISSUE TITLE
Statements Plugin shows SQL twice even if never executed 

### ISSUE THREAD

**Issue by wsescu** [dalibo/temboard#879]
Dear temBoard team

we do have an issue with the Statements plugin in a way, that SQL statements appear twice, even if never executed.
Please take a look at the attached screenshot. (I did a sort by Calls)
e.g. the UPDATE and SELECT was only executed as user robot but never executed as user robot_admin

![image](https://user-images.githubusercontent.com/54099545/100203242-a20af800-2f02-11eb-90e9-f899d0212790.png)

I am running temBoard version 7.3 and agent version 7.4.

Best regards
William

**Comment by pgiraud** [comment]
Thanks for the report. That's weird indeed.
I hope I can find some time soon to dig into this.

**Comment by wsescu** [comment]
Hello @pgiraud 

we do have this issue on every database where we have different users which starts with the same string, e.g.

<user>
<user>_ro
<user>_rw
<user>_admin

Looks like that the SQL statement which collects the data has something like <user>%, or maybe a wrong join condition.

Cheers
William

**Comment by pgiraud** [comment]
Thanks for the tip.

**Comment by pgiraud** [comment]
I could reproduce the bug or actually something similar.

**Comment by pgiraud** [comment]
@wsescu I just release a version 7.4 of temboard (UI). The problem you reported should be fixed. Can you please confirm?

**Comment by wsescu** [comment]
Hello Pierre
thanks for the new release. I will test it immediately as soon as I'll be back from holiday.
Cheers
William

**Comment by wsescu** [comment]
Hello @pgiraud 
After upgrading to temBoard to 7.4, the issue is fixed. 
Thank you very much.
Cheers
William
