### ISSUE TITLE
bloat ratio estimation only on postgres database after agent upgrade from 6 to 7

### ISSUE THREAD

**Issue by clmntpllr** [dalibo/temboard#896]
Hi,
My UI is 7.3. I’ve upgraded my agents to 7.6 using pypi.
Now for the two metrics : « BTree index bloat ratio estimation » and « Heap bloat ratio estimation », the only database listed is « postgres ». The other databases appear on the other metrics as they did before.

Thx for that project.
Regards,
Clément

**Comment by clmntpllr** [comment]
Hello,
I've upgraded both the UI and agents to 7.10.
And everything went back to a normal state ;)

**Comment by bersace** [comment]
Super !
