### ISSUE TITLE
Empty monitoring graphs, no particular error

### ISSUE THREAD

**Issue by ced75** [dalibo/temboard#897]
Hi,

I do not have any graph in the monitoring view of the two monitored servers.
It used to work a few weeks ago.
Here is the temboard UI version:
```
temBoard 7.5
System Debian GNU/Linux 10 (buster)
Python 2.7.16 (/usr/bin/python2.7)
psycopg2 2.7.7 (dt dec pq3 ext lo64)
Tornado 5.1.1
SQLAlchemy 1.3.22
alembic 1.4.3
```
Here is the agent version:
 INFO: Starting temboard-agent 7.6.
7.6

There is no particular error message in temboard services logs.

Could it be related to the 2.7 python version on the temboard server?

Thanks in advance for your help.
Regards,

Cedric

**Comment by bersace** [comment]
Hi @ced75 

Do you have messages in agent logs ?

**Comment by ced75** [comment]
Hi @bersace ,

Hard to say, since the server has been replaced. Probably a problem of Python version.
On the new server, every monitoring graph is filled correctly.

I close the bug, because it is no more reproducible.
