### ISSUE TITLE
Installation on an off-line server

### ISSUE THREAD

**Issue by Zig3tPuce** [dalibo/temboard#904]
All of our production infrastructure is offline for security reasons.
Where can I download the CentOS rpms from ? If not possible, how can I install temboard ?

**Comment by bersace** [comment]
Hi @Zig3tPuce , thanks for reaching.

To ensure dependencies, I recommend you to follow installation documentation and just replace yum install by yum download, push the downloaded packages to your servers and follow regular installation instruction.

Anyway, you should find our rpms at https://yum.dalibo.org/labs/CentOS7-x86_64/ .
