### ISSUE TITLE
Steps for PostgreSQL Upgrade

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#905]
I am going to be upgrading from PG12 to PG13 - what (if any) are the steps I need to take with the temboard-agent installed on the host?

**Comment by bersace** [comment]
Hi @dgiffin,

If you upgrade in-place, just go to agent edit dialog in UI and refresh introspection of the Postgres instance. Sadly, this will live your agent identified as `12/XXX` while it's managing a `13/XXX`.

If you change the port or the host of the cluster, I suggest you to reinstanciate a new agent. But you'll loose history in the UI.

That would be better for temboard to provide a script to transition an agent when upgrading PostgreSQL.

**Comment by dgiffin** [comment]
An agent upgrade script would be great, until then I think we'll need to keep the historical data and live with the "wrong" agent identifier. Hopefully the agent upgrade script would let us fix that later.
