### ISSUE TITLE
Sql Error in log file

### ISSUE THREAD

**Issue by egaultier** [dalibo/temboard#918]
Hi 

The errors below are repeated over and over :

![image](https://user-images.githubusercontent.com/67147948/121511377-d8b0e780-c9e8-11eb-882f-6258f7cc81db.png)

Have you an idea why ?

Thank

Emmanuel

**Comment by bersace** [comment]
Salut @egaultier ,

Looks like temboard can't access metas table. Either the search_path is wrong or the database has not beend properly initialized. How did you install temBoard ?

**Comment by egaultier** [comment]
Hi 

I follow the web page https://temboard.readthedocs.io/en/v7/installation/

No error during installation.

![image](https://user-images.githubusercontent.com/67147948/121650812-410bd180-ca9a-11eb-9144-62d6dcbfcc05.png)

Merci

**Comment by pgiraud** [comment]
@egaultier did you install temboard using packages or with `pip`?
Which version of temboard are you runnning?

**Comment by pgiraud** [comment]
Can you also please tell us what the current version of your database is?
```SQL
select * from application.alembic_version ;
```

**Comment by egaultier** [comment]
Hi @pgiraud 

With package. I followed the website documentation for Redhat.

![image](https://user-images.githubusercontent.com/67147948/122021030-952df300-cdc5-11eb-82c4-3fc2812c16c6.png)

**Comment by egaultier** [comment]
Pg 13.3

![image](https://user-images.githubusercontent.com/67147948/122021559-0ec5e100-cdc6-11eb-8ca2-f5eeb987cfeb.png)

**Comment by pgiraud** [comment]
Looks like there is an issue with the script modifying the permissions. My bad.
Can you please run the following SQL commands?
```SQL
    GRANT ALL ON SCHEMA statements TO temboard;
    GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA statements TO temboard;
    GRANT ALL ON ALL TABLES IN SCHEMA statements TO temboard;
    GRANT ALL ON ALL SEQUENCES IN SCHEMA statements TO temboard;
```

**Comment by egaultier** [comment]
After execute your SQL Commands, it's OK

![image](https://user-images.githubusercontent.com/67147948/122023764-1edec000-cdc8-11eb-9c54-82042d8b8498.png)

No more error in postgres log and in temboard log.

Two issues resolved at the same time !!!

Thank for your help.

Have good day.
Emmanuel
