### ISSUE TITLE
No Data in statements view

### ISSUE THREAD

**Issue by egaultier** [dalibo/temboard#919]
Hi
 
Sorry new issue/question

Pg12
temboard-agent 7.7

I installed pg_stat_statements extension but in statements view on Temboard, there is No data.

![image](https://user-images.githubusercontent.com/67147948/121893874-c3a4c300-cd1e-11eb-8bfa-5ecd364cea49.png)

Extension installed in postgres db since few days.

![image](https://user-images.githubusercontent.com/67147948/121894004-e9ca6300-cd1e-11eb-8231-2aed7bd99eb8.png)

Parameter in postgres.conf : 

![image](https://user-images.githubusercontent.com/67147948/121894087-01a1e700-cd1f-11eb-9a31-e8571f90c3ee.png)

Info in temboard-agent.conf

![image](https://user-images.githubusercontent.com/67147948/121894191-226a3c80-cd1f-11eb-9464-58d8ce98bec1.png)

If I do a select with psql on server, I have result :

![image](https://user-images.githubusercontent.com/67147948/121894340-5180ae00-cd1f-11eb-9de5-eafa5ee6489f.png)

Did I miss something?

Thank for you help

Emmanuel

**Comment by egaultier** [comment]
I have the same issue on all db in Temboard.

**Comment by wsescu** [comment]
Dear @egaultier 

have you activated the statements plugin in the instance properties?

![2021-06-15_08h22_36](https://user-images.githubusercontent.com/54099545/122003206-116b0b00-cdb3-11eb-8068-5c6e4448e69e.png)

And by the way ... I would remove the statements section from the Agent configuration file temboard-agent.conf entirely.
This is not needed from my point of view. (And restart the Agent afterwards)

Cheers
William

**Comment by egaultier** [comment]
Dear @wsescu

Yes the statements plugin is active in instance properties ?

I remove the statement section in temboard-agent.conf. No change, No data in Statement view.

**Comment by wsescu** [comment]
Do you see any errors in the agent log file? Are there any errors in the server log file?

**Comment by egaultier** [comment]
No data in statements schema

![image](https://user-images.githubusercontent.com/67147948/122014622-9fe58980-cdbf-11eb-92a2-9812543a6941.png)


I actived the logging option with file method in temboard.conf.

I have a lot of errors :

![image](https://user-images.githubusercontent.com/67147948/122015323-4af64300-cdc0-11eb-9ae8-42ae567b6174.png)

![image](https://user-images.githubusercontent.com/67147948/122015471-6b260200-cdc0-11eb-8c1d-daa5e054979f.png)

I think this issue is linked with issue 918.

Thank you for your help

Emmanuel

**Comment by wsescu** [comment]
I'm wondering why your owner is postgres. On my temboard instance the owner is temboard.

You might have a ownership/permission issue.

```
(postgres@[local]:58888)[temboard]> \dt+ statements.
                                   List of relations
   Schema   |             Name              | Type  |  Owner   |  Size   | Description
------------+-------------------------------+-------+----------+---------+-------------
 statements | metas                         | table | temboard | 216 kB  |
 statements | statements                    | table | temboard | 3164 MB |
 statements | statements_history            | table | temboard | 92 GB   |
 statements | statements_history_current    | table | temboard | 5404 MB |
 statements | statements_history_current_db | table | temboard | 8608 kB |
 statements | statements_history_db         | table | temboard | 250 MB  |
 statements | statements_src_tmp            | table | temboard | 118 MB  |
(7 rows)
```

**Comment by egaultier** [comment]
I don't know. No error during temboard installation

list of schema in temboard DB 

![image](https://user-images.githubusercontent.com/67147948/122018814-80e8f680-cdc3-11eb-894a-0077a979945a.png)

**Comment by wsescu** [comment]
On my installation it looks different. The connection details are:

```
$ cat /etc/temboard/temboard.conf
...
[repository]
host = host01
port = 58888
user = temboard
password = ********************************
dbname = temboard
...
```
And the owner of all schemas is temboard.

```
(postgres@[local]:58888)[temboard]> \dn+
                            List of schemas
    Name     |  Owner   |  Access privileges   |      Description
-------------+----------+----------------------+------------------------
 application | temboard | temboard=UC/temboard |
 monitoring  | temboard | temboard=UC/temboard |
 public      | temboard | temboard=UC/temboard+| standard public schema
             |          | =UC/temboard         |
 statements  | temboard | temboard=UC/temboard |
(4 rows)
```

**Comment by egaultier** [comment]
Resolved at the same time as the issue 918
