### ISSUE TITLE
Cannot install Temboard server and Temboard agent (My servers cannot access internet)

### ISSUE THREAD

**Issue by vkibit** [dalibo/temboard#926]
Hi,

is there any detailed way for installing both temboard server and temboard agent by downloading all packages and dependencies without internet access ?
My servers cannot access internet so the installation guide described here https://temboard.readthedocs.io/en/master/temboard-install-sources/
or here https://temboard.readthedocs.io/en/v2/temboard-install-rpm/
does not work for me.

The OS is : CentOS Linux release 7.9.2009 x86_64

Thanks for your help.

Best regards,

Vital

**Comment by bersace** [comment]
Hi @vkibit , it is not documented. Basically, you replace `yum install` by `yum download`, move the packages, then `yum install *.rpm`. I let you see the documentation of yum. Regards

**Comment by vkibit** [comment]
Hi @bersace,

thank you for response.
I went through that way, it didn't seem to work. Certainly a dependencies' issue.
I will try again.

Regards

**Comment by vkibit** [comment]
Hi @bersace,

after having installed temboard using python pipe, I have the below output :

[infoger@PF9SOABDM064 ~]$ temboard --version
 INFO: Starting temboard 7.8.
ERROR: Unhandled error:
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/local/lib/python3.6/site-packages/temboardui/toolkit/app.py", line 298, in entrypoint
ERROR:     retcode = self.main(argv, environ)
ERROR:   File "/usr/local/lib/python3.6/site-packages/temboardui/__main__.py", line 342, in main
ERROR:     args = parser.parse_args(argv)
ERROR:   File "/usr/lib64/python3.6/argparse.py", line 1734, in parse_args
ERROR:     args, argv = self.parse_known_args(args, namespace)
ERROR:   File "/usr/lib64/python3.6/argparse.py", line 1766, in parse_known_args
ERROR:     namespace, args = self._parse_known_args(args, namespace)
ERROR:   File "/usr/lib64/python3.6/argparse.py", line 1972, in _parse_known_args
ERROR:     start_index = consume_optional(start_index)
ERROR:   File "/usr/lib64/python3.6/argparse.py", line 1912, in consume_optional
ERROR:     take_action(action, args, option_string)
ERROR:   File "/usr/lib64/python3.6/argparse.py", line 1840, in take_action
ERROR:     action(self, namespace, argument_values, option_string)
ERROR:   File "/usr/local/lib/python3.6/site-packages/temboardui/__main__.py", line 191, in __call__
ERROR:     print(format_version().strip())
ERROR:   File "/usr/local/lib/python3.6/site-packages/temboardui/version.py", line 21, in format_version
ERROR:     return VERSION_FMT % inspect_versions()
ERROR:   File "/usr/local/lib/python3.6/site-packages/temboardui/version.py", line 26, in inspect_versions
ERROR:     from psycopg2 import __version__ as psycopg2_version
ERROR: ModuleNotFoundError: No module named 'psycopg2'
ERROR: temboardui version is 7.8.
ERROR: This is a bug!
ERROR: Please report traceback to https://github.com/dalibo/temboard/issues! Thanks!

Could you help me about to solve that, please.

Thanks.

Regards

**Comment by bersace** [comment]
Hi @vkibit,

The documentation at https://temboard.readthedocs.io/en/v7/installation/ describe how to choose the psycopg2 package and suggests to use `psycopg2-binary` from PyPI.

temBoard should raise a clean error for this.

Regards,
Étienne

**Comment by daamien** [comment]
a new "offline installation" section was added to the documentation
