### ISSUE TITLE
Could not send notification mail

### ISSUE THREAD

**Issue by Mika313** [dalibo/temboard#927]
Hello all,

I configured `notification` section in configuration file but i have this following error when i click on "test email notification button":
```
[web] ERROR: Request failed: 500 Could not send mail; No suitable authentication method found.
[web] ERROR: SMTP connection may be misconfigured..
```
 Hereunder is my configuration file:
```
[notifications]
# SMTP host
smtp_host = remote.smtp.host
# SMTP port
smtp_port = 12
smtp_tls = False
smtp_login = service_account
smtp_password = 'password'
smtp_from_addr = user@company.org
```
Is there an issue in the configuration?

Temboard version is 7.4

Thanks and Regards.

**Comment by bersace** [comment]
Hi @Mika313 thanks for reaching.

you should not protect password with quotes. The quotes are included in the password. Can you try without quotes ?

Regards

**Comment by Mika313** [comment]
Thank you @wsescu for yout advice.
@bersace i left the project but i will try at the next opportunity.
Thank you all.
