### ISSUE TITLE
Can not update instance group properties since temBoard update to 7.9

### ISSUE THREAD

**Issue by wsescu** [dalibo/temboard#962]
Dear Dalibo team

since the update to temBoard version 7.9, I can not select any user groups any more.

![image](https://user-images.githubusercontent.com/54099545/148074267-ad18ad91-8ed0-4a10-a0f8-d5b99c71d7dd.png)

If you click on User groups, you can not select any new group anymore. Have testet different browsers, and had the same issue with all of them.

Cheers
William

**Comment by daamien** [comment]
Thanks ! I can reproduce the problem, the issue also appears with the "user groups" selector in the "Update user properties" window

However the "Instance groups" selector works fine in the "Update instance properties" window

**Comment by daamien** [comment]
@wsescu : what was your previous version ? Did you upgrade from 7.8 or an earlier version ?

**Comment by wsescu** [comment]
Dear @daamien 

yes, I did an upgrade from 7.8 to 7.9.

Cheers, William

**Comment by bersace** [comment]
I don't know why, but the javascript tooltip flickers and breaks a lot of dropdown selectors.

**Comment by bersace** [comment]
Will be in next release.
