### ISSUE TITLE
temboard UI using Docker

### ISSUE THREAD

**Issue by fahadshery** [dalibo/temboard#978]
Hi,

I really liked your project and thank you for your efforts for making it public!

I have a few postgres servers running over `FreeBSD`.
I have also some Ubuntu servers running docker for monitoring purposes.

I was wondering if its possible to run the temboard agent on FreeBSD?
Then setup the GUI using docker?

Cheers,

**Comment by bersace** [comment]
We plan to make UI cloud native, and agent too. Thus you may execute agent remotely. We don't have yet plan to support FreeBSD, but that's a cool OS well supported by PostgreSQL, we should support it one day, once we have made temBoard cloud native.
