### ISSUE TITLE
Error during upgarde to 7.10

### ISSUE THREAD

**Issue by egaultier** [dalibo/temboard#991]
Hi

When I execute this command  sudo -u temboard temboard-migratedb upgrade

I have this error : 

INFO: Starting temboard-migratedb 7.10.
 INFO: Found config file /etc/temboard/temboard.conf.
 INFO: Running on Red Hat Enterprise Linux Server 7.9 (Maipo).
 INFO: Using Python 2.7.5 (/usr/bin/python) and Tornado 4.2.1 .
 INFO: Using libpq 13.5, Psycopg2 2.8.6 (dt dec pq3 ext lo64) and SQLAlchemy 0.9.8 .
 INFO: Context impl PostgresqlImpl.
 INFO: Will assume transactional DDL.
 INFO: Running upgrade 67f52879da15 -> 55ab971bde17, metrics-archive-deadlock
ERROR: Unhandled error:
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/toolkit/app.py", line 298, in entrypoint
ERROR:     retcode = self.main(argv, environ)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/migratedb.py", line 51, in main
ERROR:     command(args)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/migratedb.py", line 67, in command_upgrade
ERROR:     alembic.command.upgrade(alembic_cfg, 'head')
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/command.py", line 174, in upgrade
ERROR:     script.run_env()
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/script/base.py", line 397, in run_env
ERROR:     util.load_python_file(self.dir, 'env.py')
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
ERROR:     module = load_module_py(module_id, path)
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
ERROR:     mod = imp.load_source(module_id, path, fp)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 100, in <module>
ERROR:     run_migrations_online()
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 94, in run_migrations_online
ERROR:     context.run_migrations()
ERROR:   File "<string>", line 8, in run_migrations
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
ERROR:     self.get_context().run_migrations(**kw)
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
ERROR:     step.migration_fn(**kw)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/model/alembic/versions/20211112_2d55ab971bde17_metrics_archive_deadlock.py", line 30, in upgrade
ERROR:     op.get_bind().execute(sqlfile(name))
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
ERROR:     return meth(self, multiparams, params)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
ERROR:     return connection._execute_clauseelement(self, multiparams, params)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
ERROR:     compiled_sql, distilled_params
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
ERROR:     context)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
ERROR:     exc_info
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
ERROR:     reraise(type(exception), exception, tb=exc_tb)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
ERROR:     context)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
ERROR:     cursor.execute(statement, parameters)
ERROR: ProgrammingError: (InsufficientPrivilege) must be owner of function history_tables
ERROR:  "SET search_path TO monitoring, public;\n\nCREATE OR REPLACE FUNCTION archive_current_metrics(table_name TEXT, record_type TEXT, query TEXT) RETURNS TABLE(tblname TEXT, nb_rows INTEGER)\nLANGUAGE plpgsql\nAS $$\nDECLARE\n  v_table_current TEXT;\n  v_table_history TEXT;\n  v_query TEXT;\n  i INTEGER;\nBEGIN\n  v_table_current := table_name || '_current';\n  v_table_history := table_name || '_history';\n  -- Lock _current table to prevent concurrent updates\n  EXECUTE 'LOCK TABLE ' || v_table_current || ' IN SHARE MODE NOWAIT';\n  v_query := replace(query, '#history_table#', v_table_history);\n  v_query := replace(v_query, '#current_table#', v_table_current);\n  v_query := replace(v_query, '#record_type#', record_type);\n  -- Move data into _history table\n  EXECUTE v_query;\n  GET DIAGNOSTICS i = ROW_COUNT;\n  -- Truncate _current table\n  EXECUTE 'TRUNCATE '||v_table_current;\n  -- Return each history table name and the number of rows inserted\n  RETURN QUERY SELECT v_table_history, i;\nEND;\n$$;\n\nDROP FUNCTION IF EXISTS history_tables();\n\nCREATE OR REPLACE FUNCTION aggregate_data_single(table_name TEXT, record_type TEXT, query TEXT) RETURNS TABLE(tblname TEXT, nb_rows INTEGER)\nLANGUAGE plpgsql\nAS $$\nDECLARE\n  v_agg_periods TEXT[] := array['30m', '6h'];\n  v_agg_table TEXT;\n  i_period TEXT;\n  v_query TEXT;\n  i INTEGER;\nBEGIN\n  -- Build and run 'aggregate' query for type of metric.\n  FOREACH i_period IN ARRAY v_agg_periods LOOP\n    v_agg_table := table_name || '_' || i_period || '_current';\n    v_query := replace(query, '#agg_table#', v_agg_table);\n    v_query := replace(v_query, '#interval#', i_period);\n    v_query := replace(v_query, '#record_type#', record_type);\n    v_query := replace(v_query, '#name#', table_name);\n    EXECUTE v_query;\n    GET DIAGNOSTICS i = ROW_COUNT;\n    RETURN QUERY SELECT v_agg_table, i;\n  END LOOP;\nEND;\n$$;\n\nDROP FUNCTION IF EXISTS aggregate_data();\n" {}
ERROR: temboardui version is 7.10.
ERROR: This is a bug!
ERROR: Please report traceback to https://github.com/dalibo/temboard/issues! Thanks!

Thank you for your help

Emmanuel

**Comment by bersace** [comment]
Hi @egaultier . You need to execute `/usr/share/temboard/sql/reassign.sql` as postgres user to fix permissions. Then rerun temboard-migratedb.

**Comment by egaultier** [comment]
Thank you for your quickly answer.

Now It's ok with this 2 commands.

Emmanuel
