### ISSUE TITLE
cannot connect to postgresql with pg_hba condition that UNIX socket state was rejected.

### ISSUE THREAD

**Issue by fathoniinsansilmi** [dalibo/temboard#997]
"local" is for Unix domain socket connections only
local   all             all                                     reject

any solution for this condition to monitoring db in temboard?
agent 7.10
temboard ui 7.10

**Comment by bersace** [comment]
Hi @fathoniinsansilmi . As of now, temboard agent requires superuser access using local UNIX socket only. It's common to restrict superuser access to local socket.

**Comment by daamien** [comment]
TODO: add a explanation about this in the documentation here:

https://temboard.readthedocs.io/en/latest/agent_configure/#postgresql-section
